from gi_stub_gen.schema.function import FunctionSchema


TYPE_INFO_GET_TAG_AS_STRING = FunctionSchema(
    name="get_tag_as_string",
    namespace="GIRepository",
    is_method=True,
    is_deprecated=False,
    deprecation_warnings=None,
    docstring="[manual-override] Python-only helper to get the tag name.",
    args=[],
    is_callback=False,
    can_throw_gerror=False,
    is_async=False,
    is_constructor=False,
    is_getter=False,
    is_setter=False,
    may_return_null=False,
    return_hint="str",
    return_hint_namespace=None,
    skip_return=False,
    wrap_vfunc=False,
    line_comment=None,
    function_type="FunctionInfo",
    is_overload=False,
)
"""Manual override for GIRepository.TypeInfo.get_tag_as_string()."""

FUNCTION_INFO_GET_ARGUMENTS = FunctionSchema(
    name="get_arguments",
    namespace="GIRepository",
    is_method=True,
    is_deprecated=False,
    deprecation_warnings=None,
    docstring="[manual-override] Python-only helper to get the arguments.",
    args=[],
    is_callback=False,
    can_throw_gerror=False,
    is_async=False,
    is_constructor=False,
    is_getter=False,
    is_setter=False,
    may_return_null=False,
    return_hint="list[ArgInfo]",
    return_hint_namespace="GIRepository",
    skip_return=False,
    wrap_vfunc=False,
    line_comment=None,
    function_type="FunctionInfo",
    is_overload=False,
)
