"""
Manual overrides for GObject.GEnum and GObject.GFlags
to represent them as subclasses of enum.IntEnum and enum.IntFlag respectively.

They are manually put inside GObject during alias parsing.
This is because in GObject module they are an alias to gi._gi.GEnum and gi._gi.GFlags

"""

from gi_stub_gen.schema.class_ import ClassFieldSchema, ClassSchema
from gi_stub_gen.schema.function import FunctionSchema, FunctionArgumentSchema

GENUM_SCHEMA = ClassSchema(
    namespace="GObject",
    name="GEnum",
    bases=["enum.IntEnum"],
    docstring="From pygobject 3.52 GEnum are integrated with enum.IntEnum"
    " see https://pygobject.gnome.org/changelog.html [manual-override]",
    props=[],
    required_gi_import="enum",
    fields=[
        ClassFieldSchema(
            name="__gtype__",
            type_hint_name="GType",
            type_hint_namespace="GObject",
            may_be_null=False,
            line_comment=None,
            is_deprecated=False,
            deprecation_warnings=None,
            docstring="The GType of the enum.",
            is_readable=True,
            is_writable=False,
        ),
    ],
    methods=[
        FunctionSchema(
            name="value_name",
            namespace="",
            is_method=True,
            is_deprecated=False,
            deprecation_warnings=None,
            docstring="The name of the value.",
            args=[],
            is_callback=False,
            can_throw_gerror=False,
            is_async=False,
            is_constructor=False,
            is_getter=True,
            is_setter=False,
            may_return_null=False,
            return_hint="str",
            return_hint_namespace=None,
            skip_return=False,
            wrap_vfunc=False,
            line_comment=None,
            function_type="FunctionInfo",
            is_overload=False,
        ),
        FunctionSchema(
            name="value_nick",
            namespace="",
            is_method=True,
            is_deprecated=False,
            deprecation_warnings=None,
            docstring="The nickname of the value.",
            args=[],
            is_callback=False,
            can_throw_gerror=False,
            is_async=False,
            is_constructor=False,
            is_getter=True,
            is_setter=False,
            may_return_null=False,
            return_hint="str",
            return_hint_namespace=None,
            skip_return=False,
            wrap_vfunc=False,
            line_comment=None,
            function_type="FunctionInfo",
            is_overload=False,
        ),
    ],
    python_methods=[],
    signals=[],
    extra=[],
    is_deprecated=False,
)
'''
Representation of GEnum for manual override

class GEnum(IntEnum):
    """
    From pygobject 3.52 GEnum are integrated with enum.IntEnum
    see https://pygobject.gnome.org/changelog.html
    """

    __gtype__: GObject.GType
    value_name: str
    """The name of the value."""

    value_nick: str
    """The nickname of the value."""
'''
GFLAG_SCHEMA = ClassSchema(
    namespace="GObject",
    name="GFlags",
    bases=["enum.IntFlag"],
    docstring="From pygobject 3.52 GFlags "
    "are integrated with enum.Flag"
    " see https://pygobject.gnome.org/changelog.html [manual-override]",
    required_gi_import="enum",
    props=[],
    fields=[
        ClassFieldSchema(
            name="__gtype__",
            type_hint_name="GType",
            type_hint_namespace="GObject",
            may_be_null=False,
            line_comment=None,
            is_deprecated=False,
            deprecation_warnings=None,
            docstring="The GType of the enum.",
            is_readable=True,
            is_writable=False,
        ),
    ],
    methods=[
        FunctionSchema(
            name="first_value_name",
            namespace="",
            is_method=True,
            is_deprecated=False,
            deprecation_warnings=None,
            docstring="The name of the first value.",
            args=[],
            is_callback=False,
            can_throw_gerror=False,
            is_async=False,
            is_constructor=False,
            is_getter=True,
            is_setter=False,
            may_return_null=False,
            return_hint="str",
            return_hint_namespace=None,
            skip_return=False,
            wrap_vfunc=False,
            line_comment=None,
            function_type="FunctionInfo",
            is_overload=False,
        ),
        FunctionSchema(
            name="first_value_nick",
            namespace="",
            is_method=True,
            is_deprecated=False,
            deprecation_warnings=None,
            docstring="The nickname of the first value.",
            args=[],
            is_callback=False,
            can_throw_gerror=False,
            is_async=False,
            is_constructor=False,
            is_getter=True,
            is_setter=False,
            may_return_null=False,
            return_hint="str",
            return_hint_namespace=None,
            skip_return=False,
            wrap_vfunc=False,
            line_comment=None,
            function_type="FunctionInfo",
            is_overload=False,
        ),
        FunctionSchema(
            name="value_names",
            namespace="",
            is_method=True,
            is_deprecated=False,
            deprecation_warnings=None,
            docstring="The names of the values.",
            args=[],
            is_callback=False,
            can_throw_gerror=False,
            is_async=False,
            is_constructor=False,
            is_getter=True,
            is_setter=False,
            may_return_null=False,
            return_hint="list[str]",
            return_hint_namespace=None,
            skip_return=False,
            wrap_vfunc=False,
            line_comment=None,
            function_type="FunctionInfo",
            is_overload=False,
        ),
        FunctionSchema(
            name="value_nicks",
            namespace="",
            is_method=True,
            is_deprecated=False,
            deprecation_warnings=None,
            docstring="The nicknames of the values.",
            args=[],
            is_callback=False,
            can_throw_gerror=False,
            is_async=False,
            is_constructor=False,
            is_getter=True,
            is_setter=False,
            may_return_null=False,
            return_hint="list[str]",
            return_hint_namespace=None,
            skip_return=False,
            wrap_vfunc=False,
            line_comment=None,
            function_type="FunctionInfo",
            is_overload=False,
        ),
    ],
    python_methods=[],
    signals=[],
    extra=[],
    is_deprecated=False,
)
'''
Representation of GFlags for manual override

class GFlags(IntFlag):
    """
    From pygobject 3.52 GFlags are integrated with enum.Flag
    see https://pygobject.gnome.org/changelog.html
    """

    __gtype__: GObject.GType
    first_value_name: str
    first_value_nick: str
    value_names: list[str]
    value_nicks: list[str]
'''

# OBJECT_CONNECT = FunctionSchema(
#     name="connect",
#     namespace="GObject",
#     is_method=True,
#     is_deprecated=False,
#     deprecation_warnings=None,
#     docstring="Connect a callback to the given signal with optional user data.",
#     args=[
#         FunctionArgumentSchema(
#             namespace="GObject",
#             name="detailed_signal",
#             direction="IN",
#             is_callback=False,
#             may_be_null=False,
#             is_optional=False,
#             is_deprecated=False,
#             is_caller_allocates=False,
#             tag_as_string="",
#             get_array_length=-1,
#             py_type_name="str",
#             py_type_namespace=None,
#             line_comment=None,
#             default_value=None,
#         ),
#         FunctionArgumentSchema(
#             namespace="GObject",
#             name="handler",
#             direction="IN",
#             is_callback=True,
#             may_be_null=False,
#             is_optional=False,
#             is_deprecated=False,
#             is_caller_allocates=False,
#             tag_as_string="",
#             get_array_length=-1,
#             py_type_name="typing.Callable[..., typing.Any]",
#             py_type_namespace="typing",
#             line_comment=None,
#             default_value=None,
#         ),
#         FunctionArgumentSchema(
#             namespace="GObject",
#             name="*data",
#             direction="IN",
#             is_callback=False,
#             may_be_null=True,
#             is_optional=True,
#             is_deprecated=False,
#             is_caller_allocates=False,
#             tag_as_string="",
#             get_array_length=-1,
#             py_type_name="typing.Any",
#             py_type_namespace="typing",
#             line_comment=None,
#             default_value=None,
#         ),
#     ],
#     is_callback=False,
#     can_throw_gerror=False,
#     is_async=False,
#     is_constructor=False,
#     is_getter=False,
#     is_setter=False,
#     may_return_null=False,
#     return_hint="int",
#     return_hint_namespace=None,
#     skip_return=False,
#     wrap_vfunc=False,
#     line_comment=None,
#     function_type="FunctionInfo",
#     is_overload=False,
# )

OBJECT_EMIT = FunctionSchema(
    name="emit",
    namespace="GObject",
    is_method=True,
    is_deprecated=False,
    deprecation_warnings=None,
    docstring="Emit a signal.",
    args=[
        FunctionArgumentSchema(
            namespace="GObject",
            name="detailed_signal",
            direction="IN",
            is_callback=False,
            may_be_null=False,
            is_optional=False,
            is_deprecated=False,
            is_caller_allocates=False,
            tag_as_string="",
            get_array_length=-1,
            py_type_name="str",
            py_type_namespace=None,
            line_comment=None,
            default_value=None,
            is_pointer=False,
        ),
        FunctionArgumentSchema(
            namespace="GObject",
            name="*args",
            direction="IN",
            is_callback=False,
            may_be_null=False,
            is_optional=False,
            is_deprecated=False,
            is_caller_allocates=False,
            tag_as_string="",
            get_array_length=-1,
            py_type_name="Any",
            py_type_namespace="typing",
            line_comment=None,
            default_value=None,
            is_pointer=False,
        ),
    ],
    is_callback=False,
    can_throw_gerror=False,
    is_async=False,
    is_constructor=False,
    is_getter=False,
    is_setter=False,
    may_return_null=False,
    return_hint="Any",
    return_hint_namespace="typing",
    skip_return=False,
    wrap_vfunc=False,
    line_comment=None,
    function_type="FunctionInfo",
    is_overload=False,
)

# OBJECT_DISCONNECT = FunctionSchema(
#     name="disconnect",
#     namespace="GObject",
#     is_method=True,
#     is_deprecated=False,
#     deprecation_warnings=None,
#     docstring="Disconnect a signal handler.",
#     args=[
#         FunctionArgumentSchema(
#             namespace="GObject",
#             name="handler_id",
#             direction="IN",
#             is_callback=False,
#             may_be_null=False,
#             is_optional=False,
#             is_deprecated=False,
#             is_caller_allocates=False,
#             tag_as_string="",
#             get_array_length=-1,
#             py_type_name="int",
#             py_type_namespace=None,
#             line_comment=None,
#             default_value=None,
#         ),
#     ],
#     is_callback=False,
#     can_throw_gerror=False,
#     is_async=False,
#     is_constructor=False,
#     is_getter=False,
#     is_setter=False,
#     may_return_null=False,
#     return_hint="None",
#     return_hint_namespace=None,
#     skip_return=False,
#     wrap_vfunc=False,
#     line_comment=None,
#     function_type="FunctionInfo",
#     is_overload=False,
# )

# OBJECT_HANDLER_BLOCK = FunctionSchema(
#     name="handler_block",
#     namespace="GObject",
#     is_method=True,
#     is_deprecated=False,
#     deprecation_warnings=None,
#     docstring="Block a signal handler.",
#     args=[
#         FunctionArgumentSchema(
#             namespace="GObject",
#             name="handler_id",
#             direction="IN",
#             is_callback=False,
#             may_be_null=False,
#             is_optional=False,
#             is_deprecated=False,
#             is_caller_allocates=False,
#             tag_as_string="",
#             get_array_length=-1,
#             py_type_name="int",
#             py_type_namespace=None,
#             line_comment=None,
#             default_value=None,
#         ),
#     ],
#     is_callback=False,
#     can_throw_gerror=False,
#     is_async=False,
#     is_constructor=False,
#     is_getter=False,
#     is_setter=False,
#     may_return_null=False,
#     return_hint="None",
#     return_hint_namespace=None,
#     skip_return=False,
#     wrap_vfunc=False,
#     line_comment=None,
#     function_type="FunctionInfo",
#     is_overload=False,
# )

# OBJECT_HANDLER_UNBLOCK = FunctionSchema(
#     name="handler_unblock",
#     namespace="GObject",
#     is_method=True,
#     is_deprecated=False,
#     deprecation_warnings=None,
#     docstring="Unblock a signal handler.",
#     args=[
#         FunctionArgumentSchema(
#             namespace="GObject",
#             name="handler_id",
#             direction="IN",
#             is_callback=False,
#             may_be_null=False,
#             is_optional=False,
#             is_deprecated=False,
#             is_caller_allocates=False,
#             tag_as_string="",
#             get_array_length=-1,
#             py_type_name="int",
#             py_type_namespace=None,
#             line_comment=None,
#             default_value=None,
#         ),
#     ],
#     is_callback=False,
#     can_throw_gerror=False,
#     is_async=False,
#     is_constructor=False,
#     is_getter=False,
#     is_setter=False,
#     may_return_null=False,
#     return_hint="None",
#     return_hint_namespace=None,
#     skip_return=False,
#     wrap_vfunc=False,
#     line_comment=None,
#     function_type="FunctionInfo",
#     is_overload=False,
# )

OBJECT_WEAK_REF = FunctionSchema(
    name="weak_ref",
    namespace="GObject",
    is_method=True,
    is_deprecated=False,
    deprecation_warnings=None,
    docstring="Creates a weak reference to the object.",
    args=[
        FunctionArgumentSchema(
            namespace="GObject",
            name="callback",
            direction="IN",
            is_callback=True,
            may_be_null=True,
            is_optional=True,
            is_deprecated=False,
            is_caller_allocates=False,
            tag_as_string="",
            get_array_length=-1,
            py_type_name="Callable[[typing.Any], None]",
            py_type_namespace="typing",
            line_comment=None,
            default_value="None",
            is_pointer=False,
        ),
    ],
    is_callback=False,
    can_throw_gerror=False,
    is_async=False,
    is_constructor=False,
    is_getter=False,
    is_setter=False,
    may_return_null=False,
    return_hint="Any",
    return_hint_namespace="typing",
    skip_return=False,
    wrap_vfunc=False,
    line_comment=None,
    function_type="FunctionInfo",
    is_overload=False,
)

OBJECT_HANDLER_DEFAULT = FunctionSchema(
    name="handler_default",
    namespace="GObject",
    is_method=True,
    is_deprecated=False,
    deprecation_warnings=None,
    docstring="Set the default handler for a signal.",
    args=[
        FunctionArgumentSchema(
            namespace="GObject",
            name="callback",
            direction="IN",
            is_callback=True,
            may_be_null=True,
            is_optional=True,
            is_deprecated=False,
            is_caller_allocates=False,
            tag_as_string="",
            get_array_length=-1,
            py_type_name="Callable[[typing.Any], None]",
            py_type_namespace="typing",
            line_comment=None,
            default_value="None",
            is_pointer=False,
        ),
    ],
    is_callback=False,
    can_throw_gerror=False,
    is_async=False,
    is_constructor=False,
    is_getter=False,
    is_setter=False,
    may_return_null=False,
    return_hint="None",
    return_hint_namespace=None,
    skip_return=False,
    wrap_vfunc=False,
    line_comment=None,
    function_type="FunctionInfo",
    is_overload=False,
)
