# pyright: reportIncompatibleMethodOverride=false
"""
Stub template for a GI Repository Module.

Generated by gi-stub-gen, version 0.0.1.
Module: freetype2
Date: 2026-07-02
"""
# we disable method override report for pyright in generated stubs,
# causes too many false positives

from __future__ import annotations
from typing_extensions import deprecated  # noqa: F401
import typing_extensions  # noqa: F401

import builtins

# gi.repository imports needed by this Stub
from gi.repository import GObject
###############################################################
# classes
###############################################################

class Bitmap(GObject.GPointer, metaclass=GObject.GType): ...
class Face(GObject.GPointer, metaclass=GObject.GType): ...
class Library(GObject.GPointer, metaclass=GObject.GType): ...

###############################################################
# Constants
###############################################################

_namespace: str = ...
_version: str = ...
###############################################################
# Unknowns/Not Parsed
###############################################################

# type: lock, element not parsed are:
#     - _lock
