# pyright: reportIncompatibleMethodOverride=false
"""
Stub template for a GI Repository Module.

Generated by gi-stub-gen, version 0.0.1.
Module: PangoCairo
Date: 2026-06-19
"""
# we disable method override report for pyright in generated stubs,
# causes too many false positives

from __future__ import annotations
from typing_extensions import deprecated  # noqa: F401
import typing_extensions  # noqa: F401

import _thread
import builtins
import typing

# gi.repository imports needed by this Stub
from gi.repository import Pango
from gi.repository import cairo
###############################################################
# Functions
###############################################################

def context_get_font_options(
    context: Pango.Context,
) -> cairo.FontOptions | None: ...
def context_get_resolution(
    context: Pango.Context,
) -> float: ...
def context_set_font_options(
    context: Pango.Context,
    options: cairo.FontOptions | None = None,
) -> None: ...
def context_set_resolution(
    context: Pango.Context,
    dpi: float,
) -> None: ...
def context_set_shape_renderer(
    context: Pango.Context,
    func: ShapeRendererFunc | None = None,
    *data: object | None,
) -> None: ...
def create_context(
    cr: cairo.Context,
) -> Pango.Context: ...
def create_layout(
    cr: cairo.Context,
) -> Pango.Layout: ...
def error_underline_path(
    cr: cairo.Context,
    x: float,
    y: float,
    width: float,
    height: float,
) -> None: ...
def font_map_get_default() -> Pango.FontMap: ...
def font_map_new() -> Pango.FontMap: ...
def font_map_new_for_font_type(
    fonttype: cairo.FontType,
) -> Pango.FontMap | None: ...
def glyph_string_path(
    cr: cairo.Context,
    font: Pango.Font,
    glyphs: Pango.GlyphString,
) -> None: ...
def layout_line_path(
    cr: cairo.Context,
    line: Pango.LayoutLine,
) -> None: ...
def layout_path(
    cr: cairo.Context,
    layout: Pango.Layout,
) -> None: ...
def show_error_underline(
    cr: cairo.Context,
    x: float,
    y: float,
    width: float,
    height: float,
) -> None: ...
def show_glyph_item(
    cr: cairo.Context,
    text: str,
    glyph_item: Pango.GlyphItem,
) -> None: ...
def show_glyph_string(
    cr: cairo.Context,
    font: Pango.Font,
    glyphs: Pango.GlyphString,
) -> None: ...
def show_layout(
    cr: cairo.Context,
    layout: Pango.Layout,
) -> None: ...
def show_layout_line(
    cr: cairo.Context,
    line: Pango.LayoutLine,
) -> None: ...
def update_context(
    cr: cairo.Context,
    context: Pango.Context,
) -> None: ...
def update_layout(
    cr: cairo.Context,
    layout: Pango.Layout,
) -> None: ...

###############################################################
# classes
###############################################################

class Font(builtins.object):
    class Props: ...

    @builtins.property
    def props(self) -> Props: ...

    # gi Methods
    def __init__(self) -> None:
        """
        Initialize Font object with properties.
        """
    def get_scaled_font(self) -> cairo.ScaledFont | None: ...

class FontMap(builtins.object):
    class Props: ...

    @builtins.property
    def props(self) -> Props: ...

    # gi Methods
    def __init__(self) -> None:
        """
        Initialize FontMap object with properties.
        """
    @staticmethod
    def get_default() -> Pango.FontMap: ...
    def get_font_type(self) -> cairo.FontType: ...
    def get_resolution(self) -> float: ...
    @staticmethod
    def new() -> Pango.FontMap: ...
    @staticmethod
    def new_for_font_type(fonttype: cairo.FontType) -> Pango.FontMap | None: ...
    def set_default(self) -> None: ...
    def set_resolution(self, dpi: float) -> None: ...

###############################################################
# Callbacks
###############################################################

class ShapeRendererFunc(typing.Protocol):
    """
    This callback was used in:
        PangoCairo.context_set_shape_renderer
    """
    #  cr
    def __call__(
        self,
        cr: cairo.Context,
        attr: Pango.AttrShape,
        do_path: bool,
        *data: object | None,
    ) -> None: ...

###############################################################
# Aliases
###############################################################

_lock = _thread._lock  # type: ignore
###############################################################
# Constants
###############################################################

_namespace: str = ...
_version: str = ...
