# pyright: reportIncompatibleMethodOverride=false
"""
Stub template for a GI Repository Module.

Generated by gi-stub-gen, version 0.0.1.
Module: GIRepository
Date: 2025-12-24
"""
# we disable method override report for pyright in generated stubs,
# causes too many false positives

from __future__ import annotations
from typing_extensions import deprecated  # noqa: F401
import typing_extensions  # noqa: F401
import gi  # noqa: F401

import _thread
import enum

# gi.repository imports needed by this Stub
from gi.repository import GLib
from gi.repository import GObject
###############################################################
# Functions
###############################################################

@staticmethod
def invoke_error_quark() -> int:
    """
    Get the error quark which represents [type@GIRepository.InvokeError].
    """
    ...

@staticmethod
def type_tag_argument_from_hash_pointer(
    storage_type: TypeTag,
    hash_pointer: object | None = None,
) -> Argument:
    """
    Convert a data pointer from a GLib data structure to a
    [type@GIRepository.Argument].

    GLib data structures, such as [type@GLib.List], [type@GLib.SList], and
    [type@GLib.HashTable], all store data pointers.

    In the case where the list or hash table is storing single types rather than
    structs, these data pointers may have values stuffed into them via macros
    such as `GPOINTER_TO_INT`.

    Use this function to ensure that all values are correctly extracted from
    stuffed pointers, regardless of the machine’s architecture or endianness.

    This function fills in the appropriate field of @arg with the value extracted
    from @hash_pointer, depending on @storage_type.
    """
    ...

@staticmethod
def type_tag_hash_pointer_from_argument(
    storage_type: TypeTag,
    arg: Argument,
) -> object | None:
    """
    Convert a [type@GIRepository.Argument] to data pointer for use in a GLib
    data structure.

    GLib data structures, such as [type@GLib.List], [type@GLib.SList], and
    [type@GLib.HashTable], all store data pointers.

    In the case where the list or hash table is storing single types rather than
    structs, these data pointers may have values stuffed into them via macros
    such as `GPOINTER_TO_INT`.

    Use this function to ensure that all values are correctly stuffed into
    pointers, regardless of the machine’s architecture or endianness.

    This function returns a pointer stuffed with the appropriate field of @arg,
    depending on @storage_type.
    """
    ...

@staticmethod
def type_tag_to_string(
    type: TypeTag,
) -> str:
    """
    Obtain a string representation of @type
    """
    ...

###############################################################
# Enums/Flags
###############################################################

class ArrayType(enum.IntEnum):
    """
    The type of array in a [class@GIRepository.TypeInfo]."""

    C = 0
    """
    a C array, `char[]` for instance
    """
    ARRAY = 1
    """
    a [type@GLib.Array] array
    """
    PTR_ARRAY = 2
    """
    a [type@GLib.PtrArray] array
    """
    BYTE_ARRAY = 3
    """
    a [type@GLib.ByteArray] array
    """

class Direction(enum.IntEnum):
    """
    The direction of a [class@GIRepository.ArgInfo]."""

    IN = 0
    OUT = 1
    """
    ‘out’ argument.
    """
    INOUT = 2
    """
    ‘in and out’ argument.
    """

class FieldInfoFlags(enum.IntFlag):
    """
    Flags for a [class@GIRepository.FieldInfo]."""

    READABLE = 1
    """
    field is readable.
    """
    WRITABLE = 2
    """
    field is writable.
    """

class FunctionInfoFlags(enum.IntFlag):
    """
    Flags for a [class@GIRepository.FunctionInfo] struct."""

    IS_METHOD = 1
    """
    is a method.
    """
    IS_CONSTRUCTOR = 2
    """
    is a constructor.
    """
    IS_GETTER = 4
    """
    is a getter of a [class@GIRepository.PropertyInfo].
    """
    IS_SETTER = 8
    """
    is a setter of a [class@GIRepository.PropertyInfo].
    """
    WRAPS_VFUNC = 16
    """
    represents a virtual function.
    """
    IS_ASYNC = 32

class InvokeError(enum.IntEnum):
    """
    An error occurring while invoking a function via
    [method@GIRepository.FunctionInfo.invoke]."""

    FAILED = 0
    """
    invocation failed, unknown error.
    """
    SYMBOL_NOT_FOUND = 1
    """
    symbol couldn’t be found in any of the
      libraries associated with the typelib of the function.
    """
    ARGUMENT_MISMATCH = 2
    """
    the arguments provided didn’t match
      the expected arguments for the function’s type signature.
    """

class RepositoryError(enum.IntEnum):
    """
    An error code used with `GI_REPOSITORY_ERROR` in a [type@GLib.Error]
    returned from a [class@GIRepository.Repository] routine."""

    TYPELIB_NOT_FOUND = 0
    """
    the typelib could not be found.
    """
    NAMESPACE_MISMATCH = 1
    """
    the namespace does not match the
      requested namespace.
    """
    NAMESPACE_VERSION_CONFLICT = 2
    """
    the version of the
      typelib does not match the requested version.
    """
    LIBRARY_NOT_FOUND = 3
    """
    the library used by the typelib
      could not be found.
    """

class RepositoryLoadFlags(enum.IntFlag):
    """
    Flags that control how a typelib is loaded."""

    NONE = 0
    """
    No flags set.
    """
    LAZY = 1
    """
    Lazily load the typelib.
    """

class ScopeType(enum.IntEnum):
    """
    Scope type of a [class@GIRepository.ArgInfo] representing callback,
    determines how the callback is invoked and is used to decided when the invoke
    structs can be freed."""

    INVALID = 0
    """
    The argument is not of callback type.
    """
    CALL = 1
    """
    The callback and associated `user_data` is only
      used during the call to this function.
    """
    ASYNC = 2
    NOTIFIED = 3
    """
    The callback and associated
      `user_data` is used until the caller is notified via the
      [type@GLib.DestroyNotify].
    """
    FOREVER = 4
    """
    The callback and associated `user_data` is
      used until the process terminates
    """

class Transfer(enum.IntEnum):
    """
    `GITransfer` specifies who’s responsible for freeing the resources after an
    ownership transfer is complete.

    The transfer is the exchange of data between two parts, from the callee to
    the caller.

    The callee is either a function/method/signal or an object/interface where a
    property is defined. The caller is the side accessing a property or calling a
    function.

    In the case of a containing type such as a list, an array or a hash table the
    container itself is specified differently from the items within the
    container. Each container is freed differently, check the documentation for
    the types themselves for information on how to free them."""

    NOTHING = 0
    """
    Transfer nothing from the callee (function or the type
      instance the property belongs to) to the caller. The callee retains the
      ownership of the transfer and the caller doesn’t need to do anything to
      free up the resources of this transfer.
    """
    CONTAINER = 1
    """
    Transfer the container (list, array, hash table) from
      the callee to the caller. The callee retains the ownership of the
      individual items in the container and the caller has to free up the
      container resources ([func@GLib.List.free],
      [func@GLib.HashTable.destroy], etc) of this transfer.
    """
    EVERYTHING = 2
    """
    Transfer everything, e.g. the container and its
      contents from the callee to the caller. This is the case when the callee
      creates a copy of all the data it returns. The caller is responsible for
      cleaning up the container and item resources of this transfer.
    """

class TypeTag(enum.IntEnum):
    """
    The type tag of a [class@GIRepository.TypeInfo]."""

    VOID = 0
    """
    void
    """
    BOOLEAN = 1
    """
    boolean
    """
    INT8 = 2
    """
    8-bit signed integer
    """
    UINT8 = 3
    """
    8-bit unsigned integer
    """
    INT16 = 4
    """
    16-bit signed integer
    """
    UINT16 = 5
    """
    16-bit unsigned integer
    """
    INT32 = 6
    """
    32-bit signed integer
    """
    UINT32 = 7
    """
    32-bit unsigned integer
    """
    INT64 = 8
    """
    64-bit signed integer
    """
    UINT64 = 9
    """
    64-bit unsigned integer
    """
    FLOAT = 10
    """
    float
    """
    DOUBLE = 11
    """
    double floating point
    """
    GTYPE = 12
    """
    a [type@GObject.Type]
    """
    UTF8 = 13
    """
    a UTF-8 encoded string
    """
    FILENAME = 14
    """
    a filename, encoded in the same encoding
      as the native filesystem is using.
    """
    ARRAY = 15
    """
    an array
    """
    INTERFACE = 16
    """
    an extended interface object
    """
    GLIST = 17
    """
    a [type@GLib.List]
    """
    GSLIST = 18
    """
    a [type@GLib.SList]
    """
    GHASH = 19
    """
    a [type@GLib.HashTable]
    """
    ERROR = 20
    """
    a [type@GLib.Error]
    """
    UNICHAR = 21
    """
    Unicode character
    """

class VFuncInfoFlags(enum.IntFlag):
    """
    Flags of a [class@GIRepository.VFuncInfo] struct."""

    CHAIN_UP = 1
    """
    chains up to the parent type
    """
    OVERRIDE = 2
    """
    overrides
    """
    NOT_OVERRIDE = 4
    """
    does not override
    """

###############################################################
# classes
###############################################################

class ArgInfo(BaseInfo):
    """
    `GIArgInfo` represents an argument of a callable.

    An argument is always part of a [class@GIRepository.CallableInfo].
    """

    # gi Fields
    @property
    def padding(self) -> list | None: ...

    # gi Methods
    def __init__(self) -> None:
        """
        Generated __init__ stub method. order not guaranteed.
        """
    def get_closure_index(self) -> tuple[bool, int | None]: ...
    def get_destroy_index(self) -> tuple[bool, int | None]: ...
    def get_direction(self) -> Direction: ...
    def get_ownership_transfer(self) -> Transfer: ...
    def get_scope(self) -> ScopeType: ...
    def get_type_info(self) -> TypeInfo: ...
    def is_caller_allocates(self) -> bool: ...
    def is_optional(self) -> bool: ...
    def is_return_value(self) -> bool: ...
    def is_skip(self) -> bool: ...
    def load_type_info(self) -> TypeInfo: ...
    def may_be_null(self) -> bool: ...

    ...

class Argument(GObject.GPointer):
    # gi Fields
    v_boolean: bool = ...
    v_double: float = ...
    v_float: float = ...
    v_int: int = ...
    v_int16: int = ...
    v_int32: int = ...
    v_int64: int = ...
    v_int8: int = ...
    v_long: int = ...
    v_short: int = ...
    v_size: int = ...
    v_ssize: int = ...
    v_string: str = ...
    v_uint: int = ...
    v_uint16: int = ...
    v_uint32: int = ...
    v_uint64: int = ...
    v_uint8: int = ...
    v_ulong: int = ...
    v_ushort: int = ...

    # gi Methods
    def __init__(self) -> None:
        """
        Generated __init__ stub method. order not guaranteed.
        """

    ...

class AttributeIter(GObject.GPointer):
    # gi Methods
    def __init__(self) -> None:
        """
        Generated __init__ stub method. order not guaranteed.
        """

    ...

class BaseInfo(object):
    """
    `GIBaseInfo` is the common base struct of all other Info structs
    accessible through the [class@GIRepository.Repository] API.

    All info structures can be cast to a `GIBaseInfo`, for instance:

    ```c
       GIFunctionInfo *function_info = …;
       GIBaseInfo *info = (GIBaseInfo *) function_info;
    ```

    Most [class@GIRepository.Repository] APIs returning a `GIBaseInfo` are
    actually creating a new struct; in other words,
    [method@GIRepository.BaseInfo.unref] has to be called when done accessing the
    data.

    `GIBaseInfo` structuress are normally accessed by calling either
    [method@GIRepository.Repository.find_by_name],
    [method@GIRepository.Repository.find_by_gtype] or
    [method@GIRepository.get_info].

    ```c
    GIBaseInfo *button_info =
      gi_repository_find_by_name (NULL, "Gtk", "Button");

    // use button_info…

    gi_base_info_unref (button_info);
    ```
    """
    class Props: ...
    props: Props = ...

    # gi Methods
    def __init__(self) -> None:
        """
        Generated __init__ stub method. order not guaranteed.
        """
    def clear(self) -> None: ...
    def equal(self, info2: BaseInfo) -> bool: ...
    def get_attribute(self, name: str) -> str | None: ...
    def get_container(self) -> BaseInfo: ...
    def get_name(self) -> str | None: ...
    def get_namespace(self) -> str: ...
    def get_typelib(self) -> Typelib: ...
    def is_deprecated(self) -> bool: ...
    def iterate_attributes(self, iterator: AttributeIter) -> tuple[bool, AttributeIter, str, str]: ...
    def ref(self) -> BaseInfo: ...
    def unref(self) -> None: ...

    ...

class BaseInfoClass(GObject.GPointer):
    # gi Methods
    def __init__(self) -> None:
        """
        Generated __init__ stub method. order not guaranteed.
        """

    ...

class BaseInfoStack(GObject.GPointer):
    # gi Fields
    @property
    def dummy0(self) -> int: ...
    @property
    def dummy1(self) -> list | None: ...
    @property
    def dummy2(self) -> list | None: ...
    @property
    def dummy3(self) -> list | None: ...

    # gi Methods
    def __init__(self) -> None:
        """
        Generated __init__ stub method. order not guaranteed.
        """

    ...

class CallableInfo(BaseInfo):
    """
    `GICallableInfo` represents an entity which is callable.

    Examples of callable are:

     - functions ([class@GIRepository.FunctionInfo])
     - virtual functions ([class@GIRepository.VFuncInfo])
     - callbacks ([class@GIRepository.CallbackInfo]).

    A callable has a list of arguments ([class@GIRepository.ArgInfo]), a return
    type, direction and a flag which decides if it returns `NULL`.
    """

    # gi Methods
    def __init__(self) -> None:
        """
        Generated __init__ stub method. order not guaranteed.
        """
    def can_throw_gerror(self) -> bool: ...
    def get_arguments(self) -> list[ArgInfo]:
        """
        [manual-override] Python-only helper to get the arguments.
        """
    def get_async_function(self) -> CallableInfo | None: ...
    def get_caller_owns(self) -> Transfer: ...
    def get_finish_function(self) -> CallableInfo | None: ...
    def get_instance_ownership_transfer(self) -> Transfer: ...
    def get_return_attribute(self, name: str) -> str | None: ...
    def get_return_type(self) -> TypeInfo: ...
    def get_sync_function(self) -> CallableInfo | None: ...
    def invoke(
        self, function: object | None, in_args: list, n_in_args: int, out_args: list, n_out_args: int
    ) -> tuple[bool, Argument]: ...
    def is_async(self) -> bool: ...
    def is_method(self) -> bool: ...
    def iterate_return_attributes(self, iterator: AttributeIter) -> tuple[bool, AttributeIter, str, str]: ...
    def load_arg(self, n: int) -> ArgInfo: ...
    def load_return_type(self) -> TypeInfo: ...
    def may_return_null(self) -> bool: ...
    def skip_return(self) -> bool: ...

    ...

class CallbackInfo(CallableInfo):
    """
    `GICallbackInfo` represents a callback.
    """

    # gi Methods
    def __init__(self) -> None:
        """
        Generated __init__ stub method. order not guaranteed.
        """

    ...

class ConstantInfo(BaseInfo):
    """
    `GIConstantInfo` represents a constant.

    A constant has a type associated – which can be obtained by calling
    [method@GIRepository.ConstantInfo.get_type_info] – and a value – which can be
    obtained by calling [method@GIRepository.ConstantInfo.get_value].
    """

    # gi Methods
    def __init__(self) -> None:
        """
        Generated __init__ stub method. order not guaranteed.
        """
    def get_type_info(self) -> TypeInfo: ...

    ...

class EnumInfo(RegisteredTypeInfo):
    """
    A `GIEnumInfo` represents an enumeration.

    The `GIEnumInfo` contains a set of values (each a
    [class@GIRepository.ValueInfo]) and a type.

    The [class@GIRepository.ValueInfo] for a value is fetched by calling
    [method@GIRepository.EnumInfo.get_value] on a `GIEnumInfo`.
    """

    # gi Methods
    def __init__(self) -> None:
        """
        Generated __init__ stub method. order not guaranteed.
        """
    def get_error_domain(self) -> str | None: ...
    def get_method(self, n: int) -> FunctionInfo: ...
    def get_n_methods(self) -> int: ...
    def get_n_values(self) -> int: ...
    def get_storage_type(self) -> TypeTag: ...
    def get_value(self, n: int) -> ValueInfo: ...

    ...

class FieldInfo(BaseInfo):
    """
    A `GIFieldInfo` struct represents a field of a struct, union, or object.

    The `GIFieldInfo` is fetched by calling
    [method@GIRepository.StructInfo.get_field],
    [method@GIRepository.UnionInfo.get_field] or
    [method@GIRepository.ObjectInfo.get_field].

    A field has a size, type and a struct offset associated and a set of flags,
    which are currently `GI_FIELD_IS_READABLE` or `GI_FIELD_IS_WRITABLE`.

    See also: [type@GIRepository.StructInfo], [type@GIRepository.UnionInfo],
    [type@GIRepository.ObjectInfo]
    """

    # gi Methods
    def __init__(self) -> None:
        """
        Generated __init__ stub method. order not guaranteed.
        """
    def get_flags(self) -> FieldInfoFlags: ...
    def get_offset(self) -> int: ...
    def get_size(self) -> int: ...
    def get_type_info(self) -> TypeInfo: ...

    ...

class FlagsInfo(EnumInfo):
    """
    A `GIFlagsInfo` represents an enumeration which defines flag values
    (independently set bits).

    The `GIFlagsInfo` contains a set of values (each a
    [class@GIRepository.ValueInfo]) and a type.

    The [class@GIRepository.ValueInfo] for a value is fetched by calling
    [method@GIRepository.EnumInfo.get_value] on a `GIFlagsInfo`.
    """

    # gi Methods
    def __init__(self) -> None:
        """
        Generated __init__ stub method. order not guaranteed.
        """

    ...

class FunctionInfo(CallableInfo):
    """
    `GIFunctionInfo` represents a function, method or constructor.

    To find out what kind of entity a `GIFunctionInfo` represents, call
    [method@GIRepository.FunctionInfo.get_flags].

    See also [class@GIRepository.CallableInfo] for information on how to retrieve
    arguments and other metadata.
    """

    # gi Methods
    def __init__(self) -> None:
        """
        Generated __init__ stub method. order not guaranteed.
        """
    def get_flags(self) -> FunctionInfoFlags: ...
    def get_property(self) -> PropertyInfo | None: ...
    def get_symbol(self) -> str: ...
    def get_vfunc(self) -> VFuncInfo | None: ...

    ...

class InterfaceInfo(RegisteredTypeInfo):
    """
    `GIInterfaceInfo` represents a `GInterface` type.

    A `GInterface` has methods, fields, properties, signals,
    interfaces, constants, virtual functions and prerequisites.
    """

    # gi Methods
    def __init__(self) -> None:
        """
        Generated __init__ stub method. order not guaranteed.
        """
    def find_method(self, name: str) -> FunctionInfo | None: ...
    def find_signal(self, name: str) -> SignalInfo | None: ...
    def find_vfunc(self, name: str) -> VFuncInfo | None: ...
    def get_constant(self, n: int) -> ConstantInfo: ...
    def get_iface_struct(self) -> StructInfo | None: ...
    def get_method(self, n: int) -> FunctionInfo: ...
    def get_n_constants(self) -> int: ...
    def get_n_methods(self) -> int: ...
    def get_n_prerequisites(self) -> int: ...
    def get_n_properties(self) -> int: ...
    def get_n_signals(self) -> int: ...
    def get_n_vfuncs(self) -> int: ...
    def get_prerequisite(self, n: int) -> BaseInfo: ...
    def get_property(self, n: int) -> PropertyInfo: ...
    def get_signal(self, n: int) -> SignalInfo: ...
    def get_vfunc(self, n: int) -> VFuncInfo: ...

    ...

class ObjectInfo(RegisteredTypeInfo):
    """
    `GIObjectInfo` represents a classed type.

    Classed types in [type@GObject.Type] inherit from
    [type@GObject.TypeInstance]; the most common type is [class@GObject.Object].

    A `GIObjectInfo` doesn’t represent a specific instance of a classed type,
    instead this represent the object type (i.e. the class).

    A `GIObjectInfo` has methods, fields, properties, signals, interfaces,
    constants and virtual functions.
    """

    # gi Methods
    def __init__(self) -> None:
        """
        Generated __init__ stub method. order not guaranteed.
        """
    def find_method(self, name: str) -> FunctionInfo | None: ...
    def find_method_using_interfaces(self, name: str) -> tuple[FunctionInfo | None, BaseInfo | None]: ...
    def find_signal(self, name: str) -> SignalInfo | None: ...
    def find_vfunc(self, name: str) -> VFuncInfo | None: ...
    def find_vfunc_using_interfaces(self, name: str) -> tuple[VFuncInfo | None, BaseInfo | None]: ...
    def get_abstract(self) -> bool: ...
    def get_class_struct(self) -> StructInfo | None: ...
    def get_constant(self, n: int) -> ConstantInfo: ...
    def get_field(self, n: int) -> FieldInfo: ...
    def get_final(self) -> bool: ...
    def get_fundamental(self) -> bool: ...
    def get_get_value_function_name(self) -> str | None: ...
    def get_interface(self, n: int) -> InterfaceInfo: ...
    def get_method(self, n: int) -> FunctionInfo: ...
    def get_n_constants(self) -> int: ...
    def get_n_fields(self) -> int: ...
    def get_n_interfaces(self) -> int: ...
    def get_n_methods(self) -> int: ...
    def get_n_properties(self) -> int: ...
    def get_n_signals(self) -> int: ...
    def get_n_vfuncs(self) -> int: ...
    def get_parent(self) -> ObjectInfo | None: ...
    def get_property(self, n: int) -> PropertyInfo: ...
    def get_ref_function_name(self) -> str | None: ...
    def get_set_value_function_name(self) -> str | None: ...
    def get_signal(self, n: int) -> SignalInfo: ...
    def get_type_init_function_name(self) -> str: ...
    def get_type_name(self) -> str: ...
    def get_unref_function_name(self) -> str | None: ...
    def get_vfunc(self, n: int) -> VFuncInfo: ...

    ...

class PropertyInfo(BaseInfo):
    """
    `GIPropertyInfo` represents a property in a [class@GObject.Object].

    A property belongs to either a [class@GIRepository.ObjectInfo] or a
    [class@GIRepository.InterfaceInfo].
    """

    # gi Methods
    def __init__(self) -> None:
        """
        Generated __init__ stub method. order not guaranteed.
        """
    def get_flags(self) -> GObject.ParamFlags: ...
    def get_getter(self) -> FunctionInfo | None: ...
    def get_ownership_transfer(self) -> Transfer: ...
    def get_setter(self) -> FunctionInfo | None: ...
    def get_type_info(self) -> TypeInfo: ...

    ...

class RegisteredTypeInfo(BaseInfo):
    """
    `GIRegisteredTypeInfo` represents an entity with a [type@GObject.Type]
    associated.

    Could be either a [class@GIRepository.EnumInfo],
    [class@GIRepository.InterfaceInfo], [class@GIRepository.ObjectInfo],
    [class@GIRepository.StructInfo] or a [class@GIRepository.UnionInfo].

    A registered type info struct has a name and a type function.

    To get the name call [method@GIRepository.RegisteredTypeInfo.get_type_name].
    Most users want to call [method@GIRepository.RegisteredTypeInfo.get_g_type]
    and don’t worry about the rest of the details.

    If the registered type is a subtype of `G_TYPE_BOXED`,
    [method@GIRepository.RegisteredTypeInfo.is_boxed] will return true, and
    [method@GIRepository.RegisteredTypeInfo.get_type_name] is guaranteed to
    return a non-`NULL` value. This is relevant for the
    [class@GIRepository.StructInfo] and [class@GIRepository.UnionInfo]
    subclasses.
    """

    # gi Methods
    def __init__(self) -> None:
        """
        Generated __init__ stub method. order not guaranteed.
        """
    def get_g_type(self) -> GObject.GType: ...
    def get_type_init_function_name(self) -> str | None: ...
    def get_type_name(self) -> str | None: ...
    def is_boxed(self) -> bool: ...

    ...

class Repository(GObject.Object):
    """
    `GIRepository` is used to manage repositories of namespaces. Namespaces
    are represented on disk by type libraries (`.typelib` files).

    The individual pieces of API within a type library are represented by
    subclasses of [class@GIRepository.BaseInfo]. These can be found using
    methods like [method@GIRepository.Repository.find_by_name] or
    [method@GIRepository.Repository.get_info].

    You are responsible for ensuring that the lifetime of the
    [class@GIRepository.Repository] exceeds that of the lifetime of any of its
    [class@GIRepository.BaseInfo]s. This cannot be guaranteed by using internal
    references within libgirepository as that would affect performance.

    ### Discovery of type libraries

    `GIRepository` will typically look for a `girepository-1.0` directory
    under the library directory used when compiling gobject-introspection. On a
    standard Linux system this will end up being `/usr/lib/girepository-1.0`.

    It is possible to control the search paths programmatically, using
    [method@GIRepository.Repository.prepend_search_path]. It is also possible to
    modify the search paths by using the `GI_TYPELIB_PATH` environment variable.
    The environment variable takes precedence over the default search path
    and the [method@GIRepository.Repository.prepend_search_path] calls.

    ### Namespace ordering

    In situations where namespaces may be searched in order, or returned in a
    list, the namespaces will be returned in alphabetical order, with all fully
    loaded namespaces being returned before any lazily loaded ones (those loaded
    with `GI_REPOSITORY_LOAD_FLAG_LAZY`). This allows for deterministic and
    reproducible results.

    Similarly, if a symbol (such as a `GType` or error domain) is being searched
    for in the set of loaded namespaces, the namespaces will be searched in that
    order. In particular, this means that a symbol which exists in two namespaces
    will always be returned from the alphabetically-higher namespace. This should
    only happen in the case of `Gio` and `GioUnix`/`GioWin32`, which all refer to
    the same `.so` file and expose overlapping sets of symbols. Symbols should
    always end up being resolved to `GioUnix` or `GioWin32` if they are platform
    dependent, rather than `Gio` itself.
    """

    # gi Methods
    def __init__(self) -> None:
        """
        Generated __init__ stub method. order not guaranteed.
        """
    @staticmethod
    def dump(input_filename: str, output_filename: str) -> bool: ...
    def enumerate_versions(self, namespace_: str) -> tuple[list, int | None]: ...
    @staticmethod
    def error_quark() -> int: ...
    def find_by_error_domain(self, domain: int) -> EnumInfo | None: ...
    def find_by_gtype(self, gtype: GObject.GType) -> BaseInfo | None: ...
    def find_by_name(self, namespace_: str, name: str) -> BaseInfo | None: ...
    def get_c_prefix(self, namespace_: str) -> str | None: ...
    def get_dependencies(self, namespace_: str) -> tuple[list, int | None]: ...
    def get_immediate_dependencies(self, namespace_: str) -> tuple[list, int | None]: ...
    def get_info(self, namespace_: str, idx: int) -> BaseInfo: ...
    def get_library_path(self) -> tuple[list, int | None]: ...
    def get_loaded_namespaces(self) -> tuple[list, int | None]: ...
    def get_n_infos(self, namespace_: str) -> int: ...
    def get_object_gtype_interfaces(self, gtype: GObject.GType) -> tuple[int, list]: ...
    @staticmethod
    def get_option_group() -> GLib.OptionGroup: ...
    def get_search_path(self) -> tuple[list, int | None]: ...
    def get_shared_libraries(self, namespace_: str) -> tuple[list | None, int | None]: ...
    def get_typelib_path(self, namespace_: str) -> str | None: ...
    def get_version(self, namespace_: str) -> str: ...
    def is_registered(self, namespace_: str, version: str | None = None) -> bool: ...
    def load_typelib(self, typelib: Typelib, flags: RepositoryLoadFlags) -> str: ...
    @classmethod
    def new(cls) -> Repository: ...
    def prepend_library_path(self, directory: str) -> None: ...
    def prepend_search_path(self, directory: str) -> None: ...
    def require(self, namespace_: str, version: str | None, flags: RepositoryLoadFlags) -> Typelib: ...
    def require_private(
        self, typelib_dir: str, namespace_: str, version: str | None, flags: RepositoryLoadFlags
    ) -> Typelib: ...

    ...

class RepositoryClass(GObject.GPointer):
    # gi Fields
    @property
    def parent_class(self) -> GObject.ObjectClass | None: ...

    # gi Methods
    def __init__(self) -> None:
        """
        Generated __init__ stub method. order not guaranteed.
        """

    ...

class SignalInfo(CallableInfo):
    """
    `GISignalInfo` represents a signal.

    It’s a sub-struct of [class@GIRepository.CallableInfo] and contains a set of
    flags and a class closure.

    See [class@GIRepository.CallableInfo] for information on how to retrieve
    arguments and other metadata from the signal.
    """

    # gi Methods
    def __init__(self) -> None:
        """
        Generated __init__ stub method. order not guaranteed.
        """
    def get_class_closure(self) -> VFuncInfo | None: ...
    def get_flags(self) -> GObject.SignalFlags: ...
    def true_stops_emit(self) -> bool: ...

    ...

class StructInfo(RegisteredTypeInfo):
    """
    `GIStructInfo` represents a generic C structure type.

    A structure has methods and fields.
    """

    # gi Methods
    def __init__(self) -> None:
        """
        Generated __init__ stub method. order not guaranteed.
        """
    def find_field(self, name: str) -> FieldInfo | None: ...
    def find_method(self, name: str) -> FunctionInfo | None: ...
    def get_alignment(self) -> int: ...
    def get_copy_function_name(self) -> str | None: ...
    def get_field(self, n: int) -> FieldInfo: ...
    def get_free_function_name(self) -> str | None: ...
    def get_method(self, n: int) -> FunctionInfo: ...
    def get_n_fields(self) -> int: ...
    def get_n_methods(self) -> int: ...
    def get_size(self) -> int: ...
    def is_foreign(self) -> bool: ...
    def is_gtype_struct(self) -> bool: ...

    ...

class TypeInfo(BaseInfo):
    """
    `GITypeInfo` represents a type, including information about direction and
    transfer.

    You can retrieve a type info from an argument (see
    [class@GIRepository.ArgInfo]), a function’s return value (see
    [class@GIRepository.FunctionInfo]), a field (see
    [class@GIRepository.FieldInfo]), a property (see
    [class@GIRepository.PropertyInfo]), a constant (see
    [class@GIRepository.ConstantInfo]) or for a union discriminator (see
    [class@GIRepository.UnionInfo]).

    A type can either be a of a basic type which is a standard C primitive
    type or an interface type. For interface types you need to call
    [method@GIRepository.TypeInfo.get_interface] to get a reference to the base
    info for that interface.
    """

    # gi Fields
    @property
    def padding(self) -> list | None: ...

    # gi Methods
    def __init__(self) -> None:
        """
        Generated __init__ stub method. order not guaranteed.
        """
    def argument_from_hash_pointer(self, hash_pointer: object | None = None) -> Argument: ...
    def get_array_fixed_size(self) -> tuple[bool, int | None]: ...
    def get_array_length_index(self) -> tuple[bool, int | None]: ...
    def get_array_type(self) -> ArrayType: ...
    def get_interface(self) -> BaseInfo | None: ...
    def get_param_type(self, n: int) -> TypeInfo | None: ...
    def get_storage_type(self) -> TypeTag: ...
    def get_tag(self) -> TypeTag: ...
    def get_tag_as_string(self) -> str:
        """
        [manual-override] Python-only helper to get the tag name.
        """
    def hash_pointer_from_argument(self, arg: Argument) -> object | None: ...
    def is_pointer(self) -> bool: ...
    def is_zero_terminated(self) -> bool: ...

    ...

class Typelib(GObject.GBoxed):
    # gi Methods
    def __init__(self) -> None:
        """
        Generated __init__ stub method. order not guaranteed.
        """
    def get_namespace(self) -> str: ...
    @classmethod
    def new_from_bytes(cls, bytes: GLib.Bytes) -> Typelib: ...
    def ref(self) -> Typelib: ...
    def symbol(self, symbol_name: str) -> tuple[bool, object | None]: ...
    def unref(self) -> None: ...

    ...

class UnionInfo(RegisteredTypeInfo):
    """
    `GIUnionInfo` represents a union type.

    A union has methods and fields.  Unions can optionally have a
    discriminator, which is a field deciding what type of real union
    fields is valid for specified instance.
    """

    # gi Methods
    def __init__(self) -> None:
        """
        Generated __init__ stub method. order not guaranteed.
        """
    def find_method(self, name: str) -> FunctionInfo | None: ...
    def get_alignment(self) -> int: ...
    def get_copy_function_name(self) -> str | None: ...
    def get_discriminator(self, n: int) -> ConstantInfo | None: ...
    def get_discriminator_offset(self) -> tuple[bool, int | None]: ...
    def get_discriminator_type(self) -> TypeInfo | None: ...
    def get_field(self, n: int) -> FieldInfo: ...
    def get_free_function_name(self) -> str | None: ...
    def get_method(self, n: int) -> FunctionInfo: ...
    def get_n_fields(self) -> int: ...
    def get_n_methods(self) -> int: ...
    def get_size(self) -> int: ...
    def is_discriminated(self) -> bool: ...

    ...

class UnresolvedInfo(BaseInfo):
    """
    `GIUnresolvedInfo` represents an unresolved symbol.
    """

    # gi Methods
    def __init__(self) -> None:
        """
        Generated __init__ stub method. order not guaranteed.
        """

    ...

class VFuncInfo(CallableInfo):
    """
    `GIVFuncInfo` represents a virtual function.

    A virtual function is a callable object that belongs to either a
    [type@GIRepository.ObjectInfo] or a [type@GIRepository.InterfaceInfo].
    """

    # gi Methods
    def __init__(self) -> None:
        """
        Generated __init__ stub method. order not guaranteed.
        """
    def get_address(self, implementor_gtype: GObject.GType) -> object | None: ...
    def get_flags(self) -> VFuncInfoFlags: ...
    def get_invoker(self) -> FunctionInfo | None: ...
    def get_offset(self) -> int: ...
    def get_signal(self) -> SignalInfo | None: ...

    ...

class ValueInfo(BaseInfo):
    """
    A `GIValueInfo` represents a value in an enumeration.

    The `GIValueInfo` is fetched by calling
    [method@GIRepository.EnumInfo.get_value] on a [class@GIRepository.EnumInfo].
    """

    # gi Methods
    def __init__(self) -> None:
        """
        Generated __init__ stub method. order not guaranteed.
        """
    def get_value(self) -> int: ...

    ...

###############################################################
# Aliases
###############################################################

_lock = _thread._lock  # type: ignore
###############################################################
# Constants
###############################################################

TYPE_TAG_N_TYPES: int = ...
_namespace: str = ...
_version: str = ...
###############################################################
# Unknowns/Not Parsed
###############################################################
