# pyright: reportIncompatibleMethodOverride=false
"""
Stub template for a GI Repository Module.

Generated by gi-stub-gen, version 0.0.1.
Module: CudaGst
Date: 2026-07-15
"""
# we disable method override report for pyright in generated stubs,
# causes too many false positives

from __future__ import annotations
from typing_extensions import deprecated  # noqa: F401
import typing_extensions  # noqa: F401

import builtins
import enum

# gi.repository imports needed by this Stub
from gi.repository import GObject
###############################################################
# Enums/Flags
###############################################################

class GLDeviceList(enum.IntEnum):
    GL_DEVICE_LIST_ALL = 1

class address_mode(enum.IntEnum):
    WRAP = 0
    CLAMP = 1
    MIRROR = 2
    BORDER = 3

class array_format(enum.IntEnum):
    INT8 = 1
    INT16 = 2

class device_attribute(enum.IntEnum):
    TEXTURE_ALIGNMENT = 14
    UNIFIED_ADDRESSING = 41
    COMPUTE_CAPABILITY_MAJOR = 75
    COMPUTE_CAPABILITY_MINOR = 76
    VIRTUAL_MEMORY_MANAGEMENT_SUPPORTED = 102
    HANDLE_TYPE_POSIX_FILE_DESCRIPTOR_SUPPORTED = 103
    HANDLE_TYPE_WIN32_HANDLE_SUPPORTED = 104
    HANDLE_TYPE_WIN32_KMT_HANDLE_SUPPORTED = 105
    MEMORY_POOLS_SUPPORTED = 115

class event_flags(enum.IntEnum):
    DEFAULT = 0
    BLOCKING_SYNC = 1
    DISABLE_TIMING = 2
    INTERPROCESS = 4

class externalMemoryHandleType(enum.IntEnum):
    OPAQUE_FD = 1
    OPAQUE_WIN32 = 2
    OPAQUE_WIN32_KMT = 3
    D3D12_HEAP = 4
    D3D12_RESOURCE = 5
    D3D11_RESOURCE = 6
    D3D11_RESOURCE_KMT = 7
    NVSCIBUF = 8

class externalSemaphoreHandleType(enum.IntEnum):
    OPAQUE_FD = 1
    OPAQUE_WIN32 = 2
    OPAQUE_WIN32_KMT = 3
    D3D12_FENCE = 4
    D3D11_FENCE = 5
    NVSCISYNC = 6
    D3D11_KEYED_MUTEX = 7
    D3D11_KEYED_MUTEX_KMT = 8
    TIMELINE_SEMAPHORE_FD = 9
    TIMELINE_SEMAPHORE_WIN32 = 10

class filter_mode(enum.IntEnum):
    POINT = 0
    LINEAR = 1

class graphicsMapResourceFlags(enum.IntEnum):
    NONE = 0
    READ_ONLY = 1
    WRITE_DISCARD = 2

class graphicsRegisterFlags(enum.IntEnum):
    NONE = 0
    READ_ONLY = 1
    WRITE_DISCARD = 2
    SURFACE_LOAD_STORE = 4
    TEXTURE_GATHER = 8

class ipcMem_flags(enum.IntEnum):
    IPC_MEM_LAZY_ENABLE_PEER_ACCESS = 1

class limit(enum.IntEnum):
    STACK_SIZE = 0
    PRINTF_FIFO_SIZE = 1
    MALLOC_HEAP_SIZE = 2
    DEV_RUNTIME_SYNC_DEPTH = 3
    DEV_RUNTIME_PENDING_LAUNCH_COUNT = 4
    MAX_L2_FETCH_GRANULARITY = 5
    PERSISTING_L2_CACHE_SIZE = 6
    SHMEM_SIZE = 7
    CIG_ENABLED = 8
    CIG_SHMEM_FALLBACK_ENABLED = 9

class memAccess_flags(enum.IntEnum):
    NONE = 0
    READ = 1
    READWRITE = 3
    MAX = 2147483647

class memAllocationGranularity_flags(enum.IntEnum):
    MINIMUM = 0
    RECOMMENDED = 1

class memAllocationHandleType(enum.IntEnum):
    NONE = 0
    POSIX_FILE_DESCRIPTOR = 1
    WIN32 = 2
    WIN32_KMT = 4
    MAX = 2147483647

class memAllocationType(enum.IntEnum):
    INVALID = 0
    PINNED = 1
    MAX = 2147483647

class memLocationType(enum.IntEnum):
    INVALID = 0
    DEVICE = 1
    MAX = 2147483647

class memPool_attribute(enum.IntEnum):
    REUSE_FOLLOW_EVENT_DEPENDENCIES = 1
    REUSE_ALLOW_OPPORTUNISTIC = 2
    REUSE_ALLOW_INTERNAL_DEPENDENCIES = 3
    RELEASE_THRESHOLD = 4
    RESERVED_MEM_CURRENT = 5
    RESERVED_MEM_HIGH = 6
    USED_MEM_CURRENT = 7
    USED_MEM_HIGH = 8

class memorytype(enum.IntEnum):
    HOST = 1
    DEVICE = 2
    ARRAY = 3
    UNIFIED = 4

class resourceViewFormat(enum.IntEnum):
    RES_VIEW_FORMAT_NONE = 0

class resourcetype(enum.IntEnum):
    ARRAY = 0
    MIPMAPPED_ARRAY = 1
    LINEAR = 2
    PITCH2D = 3

class result(enum.IntEnum):
    SUCCESS = 0
    ERROR_NO_DEVICE = 100
    ERROR_ALREADY_MAPPED = 208
    ERROR_NOT_SUPPORTED = 801

class stream_flags(enum.IntEnum):
    DEFAULT = 0
    NON_BLOCKING = 1

###############################################################
# classes
###############################################################

class DA_ARRAY3D_DESCRIPTOR(GObject.GPointer, metaclass=GObject.GType):
    # gi Fields
    Depth: int = ...
    Flags: int = ...
    Format: array_format = ...
    Height: int = ...
    NumChannels: int = ...
    Width: int = ...

class DA_EXTERNAL_MEMORY_BUFFER_DESC(GObject.GPointer, metaclass=GObject.GType):
    # gi Fields
    flags: int = ...
    offset: object | None = ...
    reserved: list[int] | None = ...
    size: object | None = ...

class DA_EXTERNAL_MEMORY_MIPMAPPED_ARRAY_DESC(GObject.GPointer, metaclass=GObject.GType):
    # gi Fields
    arrayDesc: DA_ARRAY3D_DESCRIPTOR | None = ...
    numLevels: int = ...
    offset: object | None = ...
    reserved: list[int] | None = ...

class DA_MEMCPY2D(GObject.GPointer, metaclass=GObject.GType):
    # gi Fields
    Height: int = ...
    WidthInBytes: int = ...
    dstArray: object | None = ...
    dstDevice: int = ...
    dstHost: object | None = ...
    dstMemoryType: memorytype = ...
    dstPitch: int = ...
    dstXInBytes: int = ...
    dstY: int = ...
    srcArray: object | None = ...
    srcDevice: int = ...
    srcHost: object | None = ...
    srcMemoryType: memorytype = ...
    srcPitch: int = ...
    srcXInBytes: int = ...
    srcY: int = ...

class DA_RESOURCE_DESC(GObject.GPointer, metaclass=GObject.GType):
    # gi Fields
    flags: int = ...
    resType: resourcetype = ...

class DA_RESOURCE_VIEW_DESC(GObject.GPointer, metaclass=GObject.GType):
    # gi Fields
    depth: int = ...
    firstLayer: int = ...
    firstMipmapLevel: int = ...
    format: resourceViewFormat = ...
    height: int = ...
    lastLayer: int = ...
    lastMipmapLevel: int = ...
    reserved: list[int] | None = ...
    width: int = ...

class DA_TEXTURE_DESC(GObject.GPointer, metaclass=GObject.GType):
    # gi Fields
    addressMode: list[address_mode] | None = ...
    borderColor: list[float] | None = ...
    filterMode: filter_mode = ...
    flags: int = ...
    maxAnisotropy: int = ...
    maxMipmapLevelClamp: float = ...
    minMipmapLevelClamp: float = ...
    mipmapFilterMode: filter_mode = ...
    mipmapLevelBias: float = ...
    reserved: list[int] | None = ...

class ipcEventHandle(GObject.GPointer, metaclass=GObject.GType):
    # gi Fields
    reserved: list[int] | None = ...

class ipcMemHandle(GObject.GPointer, metaclass=GObject.GType):
    # gi Fields
    reserved: list[int] | None = ...

class memAccessDesc(GObject.GPointer, metaclass=GObject.GType):
    # gi Fields
    flags: memAccess_flags = ...
    location: memLocation | None = ...

class memAllocationProp(GObject.GPointer, metaclass=GObject.GType):
    # gi Fields
    allocFlags: memAllocationPropAllocFlags | None = ...
    location: memLocation | None = ...
    requestedHandleTypes: memAllocationHandleType = ...
    type: memAllocationType = ...
    win32HandleMetaData: object | None = ...

class memAllocationPropAllocFlags(GObject.GPointer, metaclass=GObject.GType):
    # gi Fields
    compressionType: int = ...
    gpuDirectRDMACapable: int = ...
    reserved: bytes | None = ...
    usage: int = ...

class memLocation(GObject.GPointer, metaclass=GObject.GType):
    # gi Fields
    id: int = ...
    type: memLocationType = ...

class memPoolProps(GObject.GPointer, metaclass=GObject.GType):
    # gi Fields
    allocType: memAllocationType = ...
    handleTypes: memAllocationHandleType = ...
    location: memLocation | None = ...
    maxSize: int = ...
    reserved: bytes | None = ...
    win32SecurityAttributes: object | None = ...

class uuid(GObject.GPointer, metaclass=GObject.GType):
    # gi Fields
    bytes: list[int] | None = ...

###############################################################
# Constants
###############################################################

IPC_HANDLE_SIZE: int = ...
TRSF_READ_AS_INTEGER: int = ...
VERSION: int = ...
_namespace: str = ...
_version: str = ...
###############################################################
# Unknowns/Not Parsed
###############################################################

# type: lock, element not parsed are:
#     - _lock
