# pyright: reportIncompatibleMethodOverride=false
"""
Stub template for a GI Repository Module.

Generated by gi-stub-gen, version 0.0.1.
Module: GstAllocators
Date: 2026-07-02
"""
# we disable method override report for pyright in generated stubs,
# causes too many false positives

from __future__ import annotations
from typing_extensions import deprecated  # noqa: F401
import typing_extensions  # noqa: F401

import _thread
import builtins
import enum
import typing

# gi.repository imports needed by this Stub
from gi.repository import GObject
from gi.repository import Gst
###############################################################
# Functions
###############################################################

def dmabuf_memory_get_fd(
    mem: Gst.Memory,
) -> int:
    """
    Return the file descriptor associated with `mem`.
    """
    ...

def drm_dumb_memory_export_dmabuf(
    mem: Gst.Memory,
) -> Gst.Memory:
    """
    Exports a DMABuf from the DRM Bumb buffer object. One can check if this
    feature is supported using `gst_drm_dumb_allocator_has_prime_export`;
    """
    ...

def drm_dumb_memory_get_handle(
    mem: Gst.Memory,
) -> int:
    """
    Return the DRM buffer object handle associated with `mem`.
    """
    ...

def fd_memory_get_fd(
    mem: Gst.Memory,
) -> int:
    """
    Get the fd from `mem`. Call `gst_is_fd_memory` to check if `mem` has
    an fd.
    """
    ...

def is_dmabuf_memory(
    mem: Gst.Memory,
) -> bool:
    """
    Check if `mem` is dmabuf memory.
    """
    ...

def is_drm_dumb_memory(
    mem: Gst.Memory,
) -> bool: ...
def is_fd_memory(
    mem: Gst.Memory,
) -> bool:
    """
    Check if `mem` is memory backed by an fd
    """
    ...

def is_phys_memory(
    mem: Gst.Memory,
) -> bool: ...
def phys_memory_get_phys_addr(
    mem: Gst.Memory,
) -> int: ...

###############################################################
# Enums/Flags
###############################################################

class FdMemoryFlags(enum.IntFlag):
    """
    Various flags to control the operation of the fd backed memory."""

    NONE = 0
    """
    no flag
    """
    KEEP_MAPPED = 1
    """
    once the memory is mapped,
           keep it mapped until the memory is destroyed.
    """
    MAP_PRIVATE = 2
    """
    do a private mapping instead of
           the default shared mapping.
    """
    DONT_CLOSE = 4
    """
    don't close the file descriptor when
           the memory is freed. Since: 1.10
    """

###############################################################
# classes
###############################################################

class DRMDumbAllocator(Gst.Allocator):
    """
    Private intance object for GstDRMDumbAllocator.
    """

    class Props(Gst.Allocator.Props):
        drm_device_path: str  # [drm-device-path]: changed because contained invalid characters
        drm_fd: int  # [drm-fd]: changed because contained invalid characters

    @builtins.property
    def props(self) -> Props: ...

    # gi Methods
    def __init__(
        self,
        drm_device_path: str | None = None,
        drm_fd: int | None = None,
        name: str | None = None,
        parent: Gst.Object | None = None,
    ) -> None:
        """
        Initialize DRMDumbAllocator object with properties.
        """
    def alloc(self, drm_fourcc: int, width: int, height: int) -> tuple[Gst.Memory, int]:
        """
            Allocated a DRM buffer object for the specific `drm_fourcc`, `width` and
        `height`. Note that the DRM Dumb allocation interface is agnostic to the
        pixel format. This `drm_fourcc` is converted into a bpp (bit-per-pixel)
        number and the height is scaled according to the sub-sampling.
        """
    def has_prime_export(self) -> bool:
        """
        This function allow verifying if the driver support dma-buf exportation.
        """

    # python methods (overrides?)
    @classmethod
    def new_with_device_path(
        cls,
        drm_device_path: str,
    ) -> DRMDumbAllocator | None:
        """
        [is-override: Note this method is an override in Python of the original gi implementation.]

        new_with_device_path(drm_device_path:str) -> Gst.Allocator or None
        """
    @classmethod
    def new_with_fd(
        cls,
        drm_fd: int,
    ) -> DRMDumbAllocator | None:
        """
        [is-override: Note this method is an override in Python of the original gi implementation.]

        new_with_fd(drm_fd:int) -> Gst.Allocator or None
        """

    # Signals
    @typing.overload
    def connect(
        self,
        detailed_signal: typing.Literal["deep-notify"],
        handler: typing.Callable[[typing_extensions.Self, Gst.Object, GObject.ParamSpec], None],
        *args: typing.Any,
    ) -> int: ...
    @typing.overload
    def connect(
        self,
        detailed_signal: typing.Literal["notify"],
        handler: typing.Callable[[typing_extensions.Self, GObject.ParamSpec], None],
        *args: typing.Any,
    ) -> int: ...
    @typing.overload
    def connect(
        self,
        detailed_signal: typing.Literal["notify::drm_device_path"],
        handler: typing.Callable[[typing_extensions.Self, GObject.ParamSpec, typing.Any], None],
        *args: typing.Any,
    ) -> int: ...
    @typing.overload
    def connect(
        self,
        detailed_signal: typing.Literal["notify::drm_fd"],
        handler: typing.Callable[[typing_extensions.Self, GObject.ParamSpec, typing.Any], None],
        *args: typing.Any,
    ) -> int: ...
    @typing.overload
    def connect(
        self,
        detailed_signal: typing.Literal["notify::name"],
        handler: typing.Callable[[typing_extensions.Self, GObject.ParamSpec, typing.Any], None],
        *args: typing.Any,
    ) -> int: ...
    @typing.overload
    def connect(
        self,
        detailed_signal: typing.Literal["notify::parent"],
        handler: typing.Callable[[typing_extensions.Self, GObject.ParamSpec, typing.Any], None],
        *args: typing.Any,
    ) -> int: ...
    @typing.overload
    def connect(  # type: ignore otherwise pylance will complain and we should repeat all parent overloads here..
        self, detailed_signal: str, handler: typing.Callable[..., typing.Any], *args: typing.Any
    ) -> int: ...

class DRMDumbAllocatorClass(GObject.GPointer, metaclass=GObject.GType):
    # gi Fields
    @builtins.property
    def parent_class(self) -> Gst.AllocatorClass | None:
        """
        Parent Class.
        """

class DmaBufAllocator(FdAllocator):
    """
    Base class for allocators with dmabuf-backed memory
    """

    # gi Fields
    @builtins.property
    def _gst_reserved(self) -> list | None: ...
    @builtins.property
    def parent(self) -> FdAllocator | None: ...

    # gi Methods
    def __init__(self, name: str | None = None, parent: Gst.Object | None = None) -> None:
        """
        Initialize DmaBufAllocator object with properties.
        """
    @staticmethod
    def alloc(allocator: Gst.Allocator, fd: int, size: int) -> Gst.Memory | None:
        """
        Return a GstMemory that wraps a dmabuf file descriptor.
        """
    @staticmethod
    def alloc_with_flags(allocator: Gst.Allocator, fd: int, size: int, flags: FdMemoryFlags) -> Gst.Memory | None:
        """
        Return a GstMemory that wraps a dmabuf file descriptor.
        """

    # python methods (overrides?)
    @classmethod
    def new(
        cls,
    ) -> DmaBufAllocator:
        """
        [is-override: Note this method is an override in Python of the original gi implementation.]

        new() -> Gst.Allocator
        """

    # Signals
    @typing.overload
    def connect(
        self,
        detailed_signal: typing.Literal["deep-notify"],
        handler: typing.Callable[[typing_extensions.Self, Gst.Object, GObject.ParamSpec], None],
        *args: typing.Any,
    ) -> int: ...
    @typing.overload
    def connect(
        self,
        detailed_signal: typing.Literal["notify"],
        handler: typing.Callable[[typing_extensions.Self, GObject.ParamSpec], None],
        *args: typing.Any,
    ) -> int: ...
    @typing.overload
    def connect(
        self,
        detailed_signal: typing.Literal["notify::name"],
        handler: typing.Callable[[typing_extensions.Self, GObject.ParamSpec, typing.Any], None],
        *args: typing.Any,
    ) -> int: ...
    @typing.overload
    def connect(
        self,
        detailed_signal: typing.Literal["notify::parent"],
        handler: typing.Callable[[typing_extensions.Self, GObject.ParamSpec, typing.Any], None],
        *args: typing.Any,
    ) -> int: ...
    @typing.overload
    def connect(  # type: ignore otherwise pylance will complain and we should repeat all parent overloads here..
        self, detailed_signal: str, handler: typing.Callable[..., typing.Any], *args: typing.Any
    ) -> int: ...

class DmaBufAllocatorClass(GObject.GPointer, metaclass=GObject.GType):
    # gi Fields
    @builtins.property
    def _gst_reserved(self) -> list | None: ...
    @builtins.property
    def parent_class(self) -> FdAllocatorClass | None: ...

class FdAllocator(Gst.Allocator):
    """
    Base class for allocators with fd-backed memory
    """

    # gi Fields
    @builtins.property
    def parent(self) -> Gst.Allocator | None: ...

    # gi Methods
    def __init__(self, name: str | None = None, parent: Gst.Object | None = None) -> None:
        """
        Initialize FdAllocator object with properties.
        """
    @staticmethod
    def alloc(allocator: Gst.Allocator, fd: int, size: int, flags: FdMemoryFlags) -> Gst.Memory | None:
        """
        Return a GstMemory that wraps a generic file descriptor.
        """
    @staticmethod
    def alloc_full(
        allocator: Gst.Allocator, fd: int, maxsize: int, offset: int, size: int, flags: FdMemoryFlags
    ) -> Gst.Memory | None:
        """
        Return a GstMemory that wraps a generic file descriptor.
        """

    # python methods (overrides?)
    @classmethod
    def new(
        cls,
    ) -> FdAllocator:
        """
        [is-override: Note this method is an override in Python of the original gi implementation.]

        new() -> Gst.Allocator
        """

    # Signals
    @typing.overload
    def connect(
        self,
        detailed_signal: typing.Literal["deep-notify"],
        handler: typing.Callable[[typing_extensions.Self, Gst.Object, GObject.ParamSpec], None],
        *args: typing.Any,
    ) -> int: ...
    @typing.overload
    def connect(
        self,
        detailed_signal: typing.Literal["notify"],
        handler: typing.Callable[[typing_extensions.Self, GObject.ParamSpec], None],
        *args: typing.Any,
    ) -> int: ...
    @typing.overload
    def connect(
        self,
        detailed_signal: typing.Literal["notify::name"],
        handler: typing.Callable[[typing_extensions.Self, GObject.ParamSpec, typing.Any], None],
        *args: typing.Any,
    ) -> int: ...
    @typing.overload
    def connect(
        self,
        detailed_signal: typing.Literal["notify::parent"],
        handler: typing.Callable[[typing_extensions.Self, GObject.ParamSpec, typing.Any], None],
        *args: typing.Any,
    ) -> int: ...
    @typing.overload
    def connect(  # type: ignore otherwise pylance will complain and we should repeat all parent overloads here..
        self, detailed_signal: str, handler: typing.Callable[..., typing.Any], *args: typing.Any
    ) -> int: ...

class FdAllocatorClass(GObject.GPointer, metaclass=GObject.GType):
    # gi Fields
    @builtins.property
    def parent_class(self) -> Gst.AllocatorClass | None: ...

class PhysMemoryAllocator(builtins.object):
    class Props: ...

    @builtins.property
    def props(self) -> Props: ...

    # gi Methods
    def __init__(self) -> None:
        """
        Initialize PhysMemoryAllocator object with properties.
        """

class PhysMemoryAllocatorInterface(GObject.GPointer, metaclass=GObject.GType):
    """
    Marker interface for allocators with physical address backed memory
    """

    # gi Fields
    @builtins.property
    def get_phys_addr(self) -> get_phys_addrPhysMemoryAllocatorInterfaceCB:
        """
         Implementations shall return the physicall memory address
        that is backing the provided memory, or 0 if none.
        """
    @builtins.property
    def parent_iface(self) -> GObject.TypeInterface | None: ...

class ShmAllocator(FdAllocator):
    """
    This is a subclass of GstFdAllocator that implements the
    `gst_allocator_alloc` method using ``memfd_create`` when available, POSIX
    ``shm_open`` otherwise. Platforms not supporting any of those (Windows) will
    always return None.

    Note that allocating new shared memories has a significant performance cost,
    it is thus recommended to keep a pool of pre-allocated GstMemory, using
    GstBufferPool. For that reason, this allocator has the
    GST_ALLOCATOR_FLAG_NO_COPY flag set.
    """

    # gi Fields
    @builtins.property
    def parent_instance(self) -> FdAllocator | None:
        """
        Parent instance.
        """

    # gi Methods
    def __init__(self, name: str | None = None, parent: Gst.Object | None = None) -> None:
        """
        Initialize ShmAllocator object with properties.
        """
    @staticmethod
    def get() -> Gst.Allocator | None:
        """
            Get the GstShmAllocator singleton previously registered with
        `gst_shm_allocator_init_once`.
        """
    @staticmethod
    def init_once() -> None:
        """
            Register a GstShmAllocator using `gst_allocator_register` with the name
        GST_ALLOCATOR_SHM. This is no-op after the first call.
        """

    # Signals
    @typing.overload
    def connect(
        self,
        detailed_signal: typing.Literal["deep-notify"],
        handler: typing.Callable[[typing_extensions.Self, Gst.Object, GObject.ParamSpec], None],
        *args: typing.Any,
    ) -> int: ...
    @typing.overload
    def connect(
        self,
        detailed_signal: typing.Literal["notify"],
        handler: typing.Callable[[typing_extensions.Self, GObject.ParamSpec], None],
        *args: typing.Any,
    ) -> int: ...
    @typing.overload
    def connect(
        self,
        detailed_signal: typing.Literal["notify::name"],
        handler: typing.Callable[[typing_extensions.Self, GObject.ParamSpec, typing.Any], None],
        *args: typing.Any,
    ) -> int: ...
    @typing.overload
    def connect(
        self,
        detailed_signal: typing.Literal["notify::parent"],
        handler: typing.Callable[[typing_extensions.Self, GObject.ParamSpec, typing.Any], None],
        *args: typing.Any,
    ) -> int: ...
    @typing.overload
    def connect(  # type: ignore otherwise pylance will complain and we should repeat all parent overloads here..
        self, detailed_signal: str, handler: typing.Callable[..., typing.Any], *args: typing.Any
    ) -> int: ...

class ShmAllocatorClass(GObject.GPointer, metaclass=GObject.GType):
    # gi Fields
    @builtins.property
    def parent_class(self) -> FdAllocatorClass | None:
        """
        Parent Class.
        """

class UdmabufAllocator(DmaBufAllocator):
    """
    This is a subclass of GstDmaBufAllocator that implements the
    `gst_allocator_alloc` method using ``memfd_create`` and `UDMABUF_CREATE`.
    Platforms not supporting that (most non-Linux) will always return None.
    """

    # gi Methods
    def __init__(self, name: str | None = None, parent: Gst.Object | None = None) -> None:
        """
        Initialize UdmabufAllocator object with properties.
        """
    @staticmethod
    def get() -> Gst.Allocator | None:
        """
        Get the GstUdmabufAllocator singleton if available.
        """
    @staticmethod
    def init_once() -> None:
        """
            Register a GstUdmabufAllocator using `gst_allocator_register` with the name
        GST_ALLOCATOR_UDMABUF. This is no-op after the first call.
        """

    # Signals
    @typing.overload
    def connect(
        self,
        detailed_signal: typing.Literal["deep-notify"],
        handler: typing.Callable[[typing_extensions.Self, Gst.Object, GObject.ParamSpec], None],
        *args: typing.Any,
    ) -> int: ...
    @typing.overload
    def connect(
        self,
        detailed_signal: typing.Literal["notify"],
        handler: typing.Callable[[typing_extensions.Self, GObject.ParamSpec], None],
        *args: typing.Any,
    ) -> int: ...
    @typing.overload
    def connect(
        self,
        detailed_signal: typing.Literal["notify::name"],
        handler: typing.Callable[[typing_extensions.Self, GObject.ParamSpec, typing.Any], None],
        *args: typing.Any,
    ) -> int: ...
    @typing.overload
    def connect(
        self,
        detailed_signal: typing.Literal["notify::parent"],
        handler: typing.Callable[[typing_extensions.Self, GObject.ParamSpec, typing.Any], None],
        *args: typing.Any,
    ) -> int: ...
    @typing.overload
    def connect(  # type: ignore otherwise pylance will complain and we should repeat all parent overloads here..
        self, detailed_signal: str, handler: typing.Callable[..., typing.Any], *args: typing.Any
    ) -> int: ...

class UdmabufAllocatorClass(GObject.GPointer, metaclass=GObject.GType):
    # gi Fields
    @builtins.property
    def parent_class(self) -> DmaBufAllocatorClass | None:
        """
        Parent Class.
        """

###############################################################
# Callbacks
###############################################################

class get_phys_addrPhysMemoryAllocatorInterfaceCB(typing.Protocol):
    """
    This callback was used in:
        PhysMemoryAllocatorInterface.get_phys_addr
    """
    #  allocator
    def __call__(
        self,
        allocator: PhysMemoryAllocator,
        mem: Gst.Memory,
    ) -> int: ...

###############################################################
# Aliases
###############################################################

_lock = _thread._lock  # type: ignore
###############################################################
# Constants
###############################################################

ALLOCATOR_DMABUF: str = ...
ALLOCATOR_FD: str = ...
ALLOCATOR_SHM: str = ...
ALLOCATOR_UDMABUF: str = ...
CAPS_FEATURE_MEMORY_DMABUF: str = ...
_namespace: str = ...
_version: str = ...
