# pyright: reportIncompatibleMethodOverride=false
"""
Stub template for a GI Repository Module.

Generated by gi-stub-gen, version 0.0.1.
Module: GstHip
Date: 2026-07-14
"""
# we disable method override report for pyright in generated stubs,
# causes too many false positives

from __future__ import annotations
from typing_extensions import deprecated  # noqa: F401
import typing_extensions  # noqa: F401

import builtins
import enum
import typing

# gi.repository imports needed by this Stub
from gi.repository import GObject
from gi.repository import Gst
from gi.repository import GstVideo
###############################################################
# Functions
###############################################################

def context_new_hip_device(
    device: HipDevice,
) -> Gst.Context: ...
def hip_ensure_element_data(
    element: Gst.Element,
    vendor: HipVendor,
    device_id: int,
    device: HipDevice,
) -> tuple[bool, HipDevice]:
    """
    Perform the steps necessary for retrieving a GstHip.Device from the
    surrounding elements or from the application using the GstContext mechanism.

    If the content of `device` is not None, then no GstContext query is
    necessary for GstHip.Device.
    """
    ...

def hip_handle_context_query(
    element: Gst.Element,
    query: Gst.Query,
    device: HipDevice | None = None,
) -> bool: ...
def hip_handle_set_context(
    element: Gst.Element,
    context: Gst.Context,
    vendor: HipVendor,
    device_id: int,
    device: HipDevice,
) -> tuple[bool, HipDevice]:
    """
    Helper function for implementing GstElementClass.`set_context` in
    HIP capable elements.

    Retrieves the GstHip.Device in `context` and places the result in `device`.
    """
    ...

def hip_load_library(
    vendor: HipVendor,
) -> bool:
    """
    Opens `vendor` specific runtime libraries
    """
    ...

def hip_rtc_compile(
    device: HipDevice,
    source: str,
    options: str,
    num_options: int,
) -> str | None:
    """
    Compiles `source` with given compile options
    """
    ...

def hip_rtc_load_library(
    vendor: HipVendor,
) -> bool:
    """
    Opens `vendor` specific runtime compiler libraries
    """
    ...

def is_hip_memory(
    mem: Gst.Memory,
) -> bool: ...

###############################################################
# Enums/Flags
###############################################################

class HipMemoryTransfer(enum.IntFlag):
    DOWNLOAD = 1048576
    UPLOAD = 2097152

class HipVendor(GObject.GEnum):
    UNKNOWN = 0
    AMD = 1
    NVIDIA = 2

###############################################################
# classes
###############################################################

class HipAllocator(Gst.Allocator):
    """
    Opaque GstHipAllocator struct
    """

    # gi Fields
    @builtins.property
    def _gst_reserved(self) -> list[object] | None: ...
    @builtins.property
    def allocator(self) -> Gst.Allocator | None: ...
    @builtins.property
    def priv(self) -> HipAllocatorPrivate | None: ...

    # gi Methods
    def __init__(self, name: str | None = None, parent: Gst.Object | None = None) -> None:
        """
        Initialize HipAllocator object with properties.
        """
    def alloc(self, device: HipDevice, info: GstVideo.VideoInfo) -> Gst.Memory | None:
        """
        Allocates a new GstHipMemory
        """
    def set_active(self, active: bool) -> bool:
        """
        Controls the active state of `allocator`.
        """

    # python methods (overrides?)
    def do_set_active(
        self,
        active: bool,
    ) -> bool:
        """
        set_active(self, active:bool) -> bool
        """

    # Signals
    @typing.overload
    def connect(
        self,
        detailed_signal: typing.Literal["deep-notify"],
        handler: typing.Callable[[typing_extensions.Self, Gst.Object, GObject.ParamSpec], None],
        *args: typing.Any,
    ) -> int: ...
    @typing.overload
    def connect(
        self,
        detailed_signal: typing.Literal["notify"],
        handler: typing.Callable[[typing_extensions.Self, GObject.ParamSpec], None],
        *args: typing.Any,
    ) -> int: ...
    @typing.overload
    def connect(
        self,
        detailed_signal: typing.Literal["notify::name"],
        handler: typing.Callable[[typing_extensions.Self, GObject.ParamSpec, typing.Any], None],
        *args: typing.Any,
    ) -> int: ...
    @typing.overload
    def connect(
        self,
        detailed_signal: typing.Literal["notify::parent"],
        handler: typing.Callable[[typing_extensions.Self, GObject.ParamSpec, typing.Any], None],
        *args: typing.Any,
    ) -> int: ...
    @typing.overload
    def connect(  # type: ignore otherwise pylance will complain and we should repeat all parent overloads here..
        self, detailed_signal: str, handler: typing.Callable[..., typing.Any], *args: typing.Any
    ) -> int: ...

class HipAllocatorClass(GObject.GPointer, metaclass=GObject.GType):
    """
    Opaque GstHipAllocatorClass struct
    """

    # gi Fields
    @builtins.property
    def _gst_reserved(self) -> list[object] | None: ...
    @builtins.property
    def allocator_class(self) -> Gst.AllocatorClass | None: ...
    @builtins.property
    def set_active(self) -> set_activeHipAllocatorClassCB: ...

class HipAllocatorPrivate(GObject.GPointer, metaclass=GObject.GType): ...

class HipBufferPool(Gst.BufferPool):
    """
    Opaque GstHipBufferPool struct
    """

    # gi Fields
    @builtins.property
    def _gst_reserved(self) -> list[object] | None: ...
    @builtins.property
    def device(self) -> HipDevice | None: ...
    @builtins.property
    def parent(self) -> Gst.BufferPool | None: ...
    @builtins.property
    def priv(self) -> HipBufferPoolPrivate | None: ...

    # gi Methods
    def __init__(self, name: str | None = None, parent: Gst.Object | None = None) -> None:
        """
        Initialize HipBufferPool object with properties.
        """

    # python methods (overrides?)
    @classmethod
    def new(
        cls,
        device: HipDevice,
    ) -> HipBufferPool:
        """
        [is-override: Note this method is an override in Python of the original gi implementation.]

        new(device:GstHip.HipDevice) -> Gst.BufferPool

        Creates new GstHip.BufferPool instance
        """

    # Signals
    @typing.overload
    def connect(
        self,
        detailed_signal: typing.Literal["deep-notify"],
        handler: typing.Callable[[typing_extensions.Self, Gst.Object, GObject.ParamSpec], None],
        *args: typing.Any,
    ) -> int: ...
    @typing.overload
    def connect(
        self,
        detailed_signal: typing.Literal["notify"],
        handler: typing.Callable[[typing_extensions.Self, GObject.ParamSpec], None],
        *args: typing.Any,
    ) -> int: ...
    @typing.overload
    def connect(
        self,
        detailed_signal: typing.Literal["notify::name"],
        handler: typing.Callable[[typing_extensions.Self, GObject.ParamSpec, typing.Any], None],
        *args: typing.Any,
    ) -> int: ...
    @typing.overload
    def connect(
        self,
        detailed_signal: typing.Literal["notify::parent"],
        handler: typing.Callable[[typing_extensions.Self, GObject.ParamSpec, typing.Any], None],
        *args: typing.Any,
    ) -> int: ...
    @typing.overload
    def connect(  # type: ignore otherwise pylance will complain and we should repeat all parent overloads here..
        self, detailed_signal: str, handler: typing.Callable[..., typing.Any], *args: typing.Any
    ) -> int: ...

class HipBufferPoolClass(GObject.GPointer, metaclass=GObject.GType):
    """
    Opaque GstHipBufferPoolClass struct
    """

    # gi Fields
    @builtins.property
    def _gst_reserved(self) -> list[object] | None: ...
    @builtins.property
    def parent_class(self) -> Gst.BufferPoolClass | None: ...

class HipBufferPoolPrivate(GObject.GPointer, metaclass=GObject.GType): ...

class HipDevice(Gst.Object):
    """
    Opaque GstHipDevice struct
    """

    class Props(Gst.Object.Props):
        device_id: int  # [device-id]: changed because contained invalid characters
        texture2d_support: bool  # [texture2d-support]: changed because contained invalid characters
        vendor: HipVendor

    @builtins.property
    def props(self) -> Props: ...

    # gi Fields
    @builtins.property
    def _gst_reserved(self) -> list[object] | None: ...
    @builtins.property
    def object(self) -> Gst.Object | None: ...
    @builtins.property
    def priv(self) -> HipDevicePrivate | None: ...

    # gi Methods
    def __init__(self, name: str | None = None, parent: Gst.Object | None = None) -> None:
        """
        Initialize HipDevice object with properties.
        """
    def get_device_id(self) -> int:
        """
        Gets numeric device identifier of `device`
        """
    def get_stream(self) -> HipStream:
        """
        Gets per GstHip.Device default GstHip.Stream owned by `device`
        """
    def get_vendor(self) -> HipVendor:
        """
        Gets vendor of `device`
        """
    def is_equal(self, device2: HipDevice) -> bool:
        """
        Checks equality of `device1` and `device2`
        """
    def set_current(self) -> bool:
        """
        Sets `device` to current stack via hipSetDevice
        """

    # python methods (overrides?)
    @classmethod
    def new(
        cls,
        vendor: HipVendor,
        device_id: int,
    ) -> HipDevice | None:
        """
        [is-override: Note this method is an override in Python of the original gi implementation.]

        new(vendor:GstHip.HipVendor, device_id:int) -> GstHip.HipDevice or None

        Creates a new device instance with `vendor` and `device_id`.
        """

    # Signals
    @typing.overload
    def connect(
        self,
        detailed_signal: typing.Literal["deep-notify"],
        handler: typing.Callable[[typing_extensions.Self, Gst.Object, GObject.ParamSpec], None],
        *args: typing.Any,
    ) -> int: ...
    @typing.overload
    def connect(
        self,
        detailed_signal: typing.Literal["notify"],
        handler: typing.Callable[[typing_extensions.Self, GObject.ParamSpec], None],
        *args: typing.Any,
    ) -> int: ...
    @typing.overload
    def connect(
        self,
        detailed_signal: typing.Literal["notify::device_id"],
        handler: typing.Callable[[typing_extensions.Self, GObject.ParamSpec, typing.Any], None],
        *args: typing.Any,
    ) -> int: ...
    @typing.overload
    def connect(
        self,
        detailed_signal: typing.Literal["notify::texture2d_support"],
        handler: typing.Callable[[typing_extensions.Self, GObject.ParamSpec, typing.Any], None],
        *args: typing.Any,
    ) -> int: ...
    @typing.overload
    def connect(
        self,
        detailed_signal: typing.Literal["notify::vendor"],
        handler: typing.Callable[[typing_extensions.Self, GObject.ParamSpec, typing.Any], None],
        *args: typing.Any,
    ) -> int: ...
    @typing.overload
    def connect(
        self,
        detailed_signal: typing.Literal["notify::name"],
        handler: typing.Callable[[typing_extensions.Self, GObject.ParamSpec, typing.Any], None],
        *args: typing.Any,
    ) -> int: ...
    @typing.overload
    def connect(
        self,
        detailed_signal: typing.Literal["notify::parent"],
        handler: typing.Callable[[typing_extensions.Self, GObject.ParamSpec, typing.Any], None],
        *args: typing.Any,
    ) -> int: ...
    @typing.overload
    def connect(  # type: ignore otherwise pylance will complain and we should repeat all parent overloads here..
        self, detailed_signal: str, handler: typing.Callable[..., typing.Any], *args: typing.Any
    ) -> int: ...

class HipDeviceClass(GObject.GPointer, metaclass=GObject.GType):
    """
    Opaque GstHipDeviceClass struct
    """

    # gi Fields
    @builtins.property
    def _gst_reserved(self) -> list[object] | None: ...
    @builtins.property
    def parent_class(self) -> Gst.ObjectClass | None: ...

class HipDevicePrivate(GObject.GPointer, metaclass=GObject.GType): ...

class HipEvent(GObject.GBoxed, metaclass=GObject.GType):
    # gi Methods
    def get_device_id(self) -> int:
        """
        Gets numeric device identifier of `event` object
        """
    def get_vendor(self) -> HipVendor:
        """
        Gets device vendor of `event` object
        """
    def ref(self) -> HipEvent:
        """
        Increments the reference count on `event`
        """
    def unref(self) -> None:
        """
        Decrements the reference count on `event`
        """

class HipEventPool(Gst.Object):
    """
    Opaque GstHipEventPool struct
    """

    # gi Fields
    @builtins.property
    def _gst_reserved(self) -> list[object] | None: ...
    @builtins.property
    def parent(self) -> Gst.Object | None: ...
    @builtins.property
    def priv(self) -> HipEventPoolPrivate | None: ...

    # gi Methods
    def __init__(self, name: str | None = None, parent: Gst.Object | None = None) -> None:
        """
        Initialize HipEventPool object with properties.
        """
    def acquire(self) -> tuple[bool, HipEvent | None]:
        """
        Acquires GstHip.Event from `pool`
        """

    # python methods (overrides?)
    @classmethod
    def new(
        cls,
        vendor: HipVendor,
        device_id: int,
    ) -> HipEventPool | None:
        """
        [is-override: Note this method is an override in Python of the original gi implementation.]

        new(vendor:GstHip.HipVendor, device_id:int) -> GstHip.HipEventPool or None

        Creates a new event pool instance with `vendor` and `device_id`.
        """

    # Signals
    @typing.overload
    def connect(
        self,
        detailed_signal: typing.Literal["deep-notify"],
        handler: typing.Callable[[typing_extensions.Self, Gst.Object, GObject.ParamSpec], None],
        *args: typing.Any,
    ) -> int: ...
    @typing.overload
    def connect(
        self,
        detailed_signal: typing.Literal["notify"],
        handler: typing.Callable[[typing_extensions.Self, GObject.ParamSpec], None],
        *args: typing.Any,
    ) -> int: ...
    @typing.overload
    def connect(
        self,
        detailed_signal: typing.Literal["notify::name"],
        handler: typing.Callable[[typing_extensions.Self, GObject.ParamSpec, typing.Any], None],
        *args: typing.Any,
    ) -> int: ...
    @typing.overload
    def connect(
        self,
        detailed_signal: typing.Literal["notify::parent"],
        handler: typing.Callable[[typing_extensions.Self, GObject.ParamSpec, typing.Any], None],
        *args: typing.Any,
    ) -> int: ...
    @typing.overload
    def connect(  # type: ignore otherwise pylance will complain and we should repeat all parent overloads here..
        self, detailed_signal: str, handler: typing.Callable[..., typing.Any], *args: typing.Any
    ) -> int: ...

class HipEventPoolClass(GObject.GPointer, metaclass=GObject.GType):
    """
    Opaque GstHipEventPoolClass struct
    """

    # gi Fields
    @builtins.property
    def _gst_reserved(self) -> list[object] | None: ...
    @builtins.property
    def parent_class(self) -> Gst.ObjectClass | None: ...

class HipEventPoolPrivate(GObject.GPointer, metaclass=GObject.GType): ...

class HipGraphicsResource(GObject.GBoxed, metaclass=GObject.GType):
    # gi Methods
    def ref(self) -> HipGraphicsResource:
        """
        Increments the reference count on `resource`
        """
    def unref(self) -> None:
        """
        Decrements the reference count on `resource`
        """

class HipMemory(GObject.GPointer, metaclass=GObject.GType):
    """
    Opaque GstHipMemory struct
    """

    # gi Fields
    @builtins.property
    def _gst_reserved(self) -> list[object] | None: ...
    device: HipDevice | None = ...
    info: GstVideo.VideoInfo | None = ...  # type: ignore
    mem: Gst.Memory | None = ...  # type: ignore
    @builtins.property
    def priv(self) -> HipMemoryPrivate | None: ...

    # gi Methods
    def get_stream(self) -> HipStream | None:
        """
        Gets HIP stream object associated with `mem`
        """
    def get_texture(self, plane: int, filter_mode: int, address_mode: int) -> tuple[bool, object | None]:
        """
        Creates hipTextureObject_t with given parameters
        """
    def set_event(self, event: HipEvent | None = None) -> None:
        """
        Sets `event` to `mem` for later synchronization operation
        """
    def sync(self) -> None:
        """
            Waits for device synchronization by using previously configured GstHip.Event
        via `gst_hip_memory_set_event`
        """

class HipMemoryPrivate(GObject.GPointer, metaclass=GObject.GType): ...

class HipPoolAllocator(HipAllocator):
    """
    Opaque GstHipPoolAllocator struct
    """

    # gi Fields
    @builtins.property
    def _gst_reserved(self) -> list[object] | None: ...
    @builtins.property
    def device(self) -> HipDevice | None: ...
    @builtins.property
    def info(self) -> GstVideo.VideoInfo | None: ...
    @builtins.property
    def parent(self) -> HipAllocator | None: ...
    @builtins.property
    def priv(self) -> HipPoolAllocatorPrivate | None: ...

    # gi Methods
    def __init__(self, name: str | None = None, parent: Gst.Object | None = None) -> None:
        """
        Initialize HipPoolAllocator object with properties.
        """
    def acquire_memory(self) -> tuple[Gst.FlowReturn, Gst.Memory | None]:
        """
            Acquires a GstMemory from `allocator`. `memory` should point to a memory
        location that can hold a pointer to the new GstMemory.
        """

    # python methods (overrides?)
    @classmethod
    def new(
        cls,
        device: HipDevice,
        info: GstVideo.VideoInfo,
    ) -> HipPoolAllocator:
        """
        [is-override: Note this method is an override in Python of the original gi implementation.]

        new(device:GstHip.HipDevice, info:GstVideo.VideoInfo) -> GstHip.HipPoolAllocator

        Creates a new GstHip.PoolAllocator instance
        """

    # Signals
    @typing.overload
    def connect(
        self,
        detailed_signal: typing.Literal["deep-notify"],
        handler: typing.Callable[[typing_extensions.Self, Gst.Object, GObject.ParamSpec], None],
        *args: typing.Any,
    ) -> int: ...
    @typing.overload
    def connect(
        self,
        detailed_signal: typing.Literal["notify"],
        handler: typing.Callable[[typing_extensions.Self, GObject.ParamSpec], None],
        *args: typing.Any,
    ) -> int: ...
    @typing.overload
    def connect(
        self,
        detailed_signal: typing.Literal["notify::name"],
        handler: typing.Callable[[typing_extensions.Self, GObject.ParamSpec, typing.Any], None],
        *args: typing.Any,
    ) -> int: ...
    @typing.overload
    def connect(
        self,
        detailed_signal: typing.Literal["notify::parent"],
        handler: typing.Callable[[typing_extensions.Self, GObject.ParamSpec, typing.Any], None],
        *args: typing.Any,
    ) -> int: ...
    @typing.overload
    def connect(  # type: ignore otherwise pylance will complain and we should repeat all parent overloads here..
        self, detailed_signal: str, handler: typing.Callable[..., typing.Any], *args: typing.Any
    ) -> int: ...

class HipPoolAllocatorClass(GObject.GPointer, metaclass=GObject.GType):
    """
    Opaque GstHipPoolAllocatorClass struct
    """

    # gi Fields
    @builtins.property
    def _gst_reserved(self) -> list[object] | None: ...
    @builtins.property
    def parent_class(self) -> HipAllocatorClass | None: ...

class HipPoolAllocatorPrivate(GObject.GPointer, metaclass=GObject.GType): ...

class HipStream(GObject.GBoxed, metaclass=GObject.GType):
    # gi Methods
    def get_device_id(self) -> int:
        """
        Gets numeric device identifier of `stream` object
        """
    def get_handle(self) -> object | None:
        """
        Gets hipStream_t handle owned by `stream`
        """
    def get_vendor(self) -> HipVendor:
        """
        Gets device vendor of `stream` object
        """
    def record_event(self) -> tuple[bool, HipEvent | None]:
        """
        Records currently scheduled operations in `stream` to GstHip.Event
        """
    def ref(self) -> HipStream:
        """
        Increments the reference count on `stream`
        """
    def unref(self) -> None:
        """
        Decrements the reference count on `stream`
        """

    # python methods (overrides?)
    def __init__(
        self,
        *args: typing.Any,
        **kwargs: typing.Any,
    ) -> None: ...
    @classmethod
    def new(
        cls,
        vendor: HipVendor,
        device_id: int,
    ) -> HipStream | None:
        """
        [is-override: Note this method is an override in Python of the original gi implementation.]

        new(vendor:GstHip.HipVendor, device_id:int) -> GstHip.HipStream or None

        Creates a new GstHip.Stream object
        """

###############################################################
# Callbacks
###############################################################

class set_activeHipAllocatorClassCB(typing.Protocol):
    """
    This callback was used in:
        HipAllocatorClass.set_active
    """
    #  allocator
    def __call__(
        self,
        allocator: HipAllocator,
        active: bool,
    ) -> bool: ...

###############################################################
# Constants
###############################################################

CAPS_FEATURE_MEMORY_HIP_MEMORY: str = ...
HIP_DEVICE_CONTEXT_TYPE: str = ...
HIP_MEMORY_NAME: str = ...
MAP_HIP = Gst.MapFlags(0)
MAP_READ_HIP = Gst.MapFlags(0)
MAP_WRITE_HIP = Gst.MapFlags(0)
_namespace: str = ...
_version: str = ...
###############################################################
# Unknowns/Not Parsed
###############################################################

# type: lock, element not parsed are:
#     - _lock
