# pyright: reportIncompatibleMethodOverride=false
"""
Stub template for a GI Repository Module.

Generated by gi-stub-gen, version 0.0.1.
Module: GstInsertBin
Date: 2026-07-02
"""
# we disable method override report for pyright in generated stubs,
# causes too many false positives

from __future__ import annotations
from typing_extensions import deprecated  # noqa: F401
import typing_extensions  # noqa: F401

import builtins
import typing

# gi.repository imports needed by this Stub
from gi.repository import GObject
from gi.repository import Gst
###############################################################
# classes
###############################################################

class InsertBin(Gst.Bin):
    """
    This element is a GstBin that has a single source and sink pad. It allows
    the user (the application) to easily add and remove filter-like element
    (that has a single source and sink pad), to the pipeline while it is running.
    It features a fully asynchronous API inspired by GLib's GAsyncResult based
    APIs.

    Each operation (addition or removal) can take a callback, this callback
    is guaranteed to be called. Unlike GIO, there is no guarantee about where
    this callback will be called from, it could be called before the action
    returns or it could be called later from another thread. The signature of
    this callback `GstInsertBinCallback`.

    Apart from the library API, since 1.24 insertbin can also be found in the
    registry:

    ``` C
      GstElement *pipeline, *insertbin, *videoflip;

      gst_init (None, None);
      pipeline =
          gst_parse_launch ("videotestsrc ! insertbin name=i ! autovideosink",
          None);

      ...

      insertbin = gst_bin_get_by_name (GST_BIN (pipeline), "i");
      videoflip = gst_element_factory_make ("videoflip", None);

      ...

      g_object_set (videoflip, "method", 1, None);
      g_signal_emit_by_name (insertbin, "append", videoflip, None, None);

      ...
    ```
    """

    # gi Fields
    @builtins.property
    def parent(self) -> Gst.Bin | None: ...
    @builtins.property
    def priv(self) -> InsertBinPrivate | None: ...

    # gi Methods
    def __init__(
        self,
        async_handling: bool | None = None,
        message_forward: bool | None = None,
        name: str | None = None,
        parent: Gst.Object | None = None,
    ) -> None:
        """
        Initialize InsertBin object with properties.
        """
    def append(self, element: Gst.Element, callback: InsertBinCallback, *user_data: object | None) -> None:
        """
            This action signal adds the filter like element after any other element
        in the bin.

        Same as the GstInsertBin.::append signal.
        """
    def insert_after(
        self, element: Gst.Element, sibling: Gst.Element, callback: InsertBinCallback, *user_data: object | None
    ) -> None:
        """
            This action signal adds the filter like element after the `sibling`
        element in the bin.

        Same as the GstInsertBin.::insert-after signal.
        """
    def insert_before(
        self, element: Gst.Element, sibling: Gst.Element, callback: InsertBinCallback, *user_data: object | None
    ) -> None:
        """
            This action signal adds the filter like element before the `sibling`
        element in the bin.

        Same as the GstInsertBin.::insert-before signal.
        """
    def prepend(self, element: Gst.Element, callback: InsertBinCallback, *user_data: object | None) -> None:
        """
            This action signal adds the filter like element before any other element
        in the bin.

        Same as the GstInsertBin.::prepend signal.
        """
    def remove(self, element: Gst.Element, callback: InsertBinCallback, *user_data: object | None) -> None:
        """
            This action signal removed the filter like element from the bin.

        Same as the GstInsertBin.::remove signal.
        """

    # python methods (overrides?)
    @classmethod
    def new(
        cls,
        name: str | None = None,
    ) -> InsertBin:
        """
        [is-override: Note this method is an override in Python of the original gi implementation.]

        new(name:str=None) -> Gst.Element

        Creates a new GstInsertBin.
        """

    # Signals
    @typing.overload
    def connect(
        self,
        detailed_signal: typing.Literal["append"],
        handler: typing.Callable[[typing_extensions.Self, Gst.Element, object | None, object | None], None],
        *args: typing.Any,
    ) -> int:
        """
            This action signal adds the filter like element after any other element
        in the bin.

        Same as `gst_insert_bin_append`
        """
    @typing.overload
    def connect(
        self,
        detailed_signal: typing.Literal["insert-after"],
        handler: typing.Callable[
            [typing_extensions.Self, Gst.Element, Gst.Element, object | None, object | None], None
        ],
        *args: typing.Any,
    ) -> int:
        """
            This action signal adds the filter like element after the `sibling`
        element in the bin.
        element in the bin.

        Same as `gst_insert_bin_insert_after`
        """
    @typing.overload
    def connect(
        self,
        detailed_signal: typing.Literal["insert-before"],
        handler: typing.Callable[
            [typing_extensions.Self, Gst.Element, Gst.Element, object | None, object | None], None
        ],
        *args: typing.Any,
    ) -> int:
        """
            This action signal adds the filter like element before the `sibling`
        element in the bin.

        Same as `gst_insert_bin_insert_before`
        """
    @typing.overload
    def connect(
        self,
        detailed_signal: typing.Literal["prepend"],
        handler: typing.Callable[[typing_extensions.Self, Gst.Element, object | None, object | None], None],
        *args: typing.Any,
    ) -> int:
        """
            This action signal adds the filter like element before any other element
        in the bin.

        Same as `gst_insert_bin_prepend`
        """
    @typing.overload
    def connect(
        self,
        detailed_signal: typing.Literal["remove"],
        handler: typing.Callable[[typing_extensions.Self, Gst.Element, object | None, object | None], None],
        *args: typing.Any,
    ) -> int:
        """
            This action signal removed the filter like element from the bin.

        Same as `gst_insert_bin_remove`
        """
    @typing.overload
    def connect(
        self,
        detailed_signal: typing.Literal["child-added"],
        handler: typing.Callable[[typing_extensions.Self, GObject.Object, str], None],
        *args: typing.Any,
    ) -> int: ...
    @typing.overload
    def connect(
        self,
        detailed_signal: typing.Literal["child-removed"],
        handler: typing.Callable[[typing_extensions.Self, GObject.Object, str], None],
        *args: typing.Any,
    ) -> int: ...
    @typing.overload
    def connect(
        self,
        detailed_signal: typing.Literal["deep-element-added"],
        handler: typing.Callable[[typing_extensions.Self, Gst.Bin, Gst.Element], None],
        *args: typing.Any,
    ) -> int: ...
    @typing.overload
    def connect(
        self,
        detailed_signal: typing.Literal["deep-element-removed"],
        handler: typing.Callable[[typing_extensions.Self, Gst.Bin, Gst.Element], None],
        *args: typing.Any,
    ) -> int: ...
    @typing.overload
    def connect(
        self, detailed_signal: typing.Literal["do-latency"], handler: typing.Callable[..., bool], *args: typing.Any
    ) -> int: ...
    @typing.overload
    def connect(
        self,
        detailed_signal: typing.Literal["element-added"],
        handler: typing.Callable[[typing_extensions.Self, Gst.Element], None],
        *args: typing.Any,
    ) -> int: ...
    @typing.overload
    def connect(
        self,
        detailed_signal: typing.Literal["element-removed"],
        handler: typing.Callable[[typing_extensions.Self, Gst.Element], None],
        *args: typing.Any,
    ) -> int: ...
    @typing.overload
    def connect(
        self, detailed_signal: typing.Literal["no-more-pads"], handler: typing.Callable[..., None], *args: typing.Any
    ) -> int: ...
    @typing.overload
    def connect(
        self,
        detailed_signal: typing.Literal["pad-added"],
        handler: typing.Callable[[typing_extensions.Self, Gst.Pad], None],
        *args: typing.Any,
    ) -> int: ...
    @typing.overload
    def connect(
        self,
        detailed_signal: typing.Literal["pad-removed"],
        handler: typing.Callable[[typing_extensions.Self, Gst.Pad], None],
        *args: typing.Any,
    ) -> int: ...
    @typing.overload
    def connect(
        self,
        detailed_signal: typing.Literal["deep-notify"],
        handler: typing.Callable[[typing_extensions.Self, Gst.Object, GObject.ParamSpec], None],
        *args: typing.Any,
    ) -> int: ...
    @typing.overload
    def connect(
        self,
        detailed_signal: typing.Literal["notify"],
        handler: typing.Callable[[typing_extensions.Self, GObject.ParamSpec], None],
        *args: typing.Any,
    ) -> int: ...
    @typing.overload
    def connect(
        self,
        detailed_signal: typing.Literal["notify::async_handling"],
        handler: typing.Callable[[typing_extensions.Self, GObject.ParamSpec, typing.Any], None],
        *args: typing.Any,
    ) -> int: ...
    @typing.overload
    def connect(
        self,
        detailed_signal: typing.Literal["notify::message_forward"],
        handler: typing.Callable[[typing_extensions.Self, GObject.ParamSpec, typing.Any], None],
        *args: typing.Any,
    ) -> int: ...
    @typing.overload
    def connect(
        self,
        detailed_signal: typing.Literal["notify::name"],
        handler: typing.Callable[[typing_extensions.Self, GObject.ParamSpec, typing.Any], None],
        *args: typing.Any,
    ) -> int: ...
    @typing.overload
    def connect(
        self,
        detailed_signal: typing.Literal["notify::parent"],
        handler: typing.Callable[[typing_extensions.Self, GObject.ParamSpec, typing.Any], None],
        *args: typing.Any,
    ) -> int: ...
    @typing.overload
    def connect(  # type: ignore otherwise pylance will complain and we should repeat all parent overloads here..
        self, detailed_signal: str, handler: typing.Callable[..., typing.Any], *args: typing.Any
    ) -> int: ...

class InsertBinClass(GObject.GPointer, metaclass=GObject.GType):
    """
    The object class structure.
    """

    # gi Fields
    @builtins.property
    def parent_class(self) -> Gst.BinClass | None: ...

class InsertBinPrivate(GObject.GPointer, metaclass=GObject.GType): ...

###############################################################
# Callbacks
###############################################################

class InsertBinCallback(typing.Protocol):
    """
    This callback was used in:
        GstInsertBin.append, GstInsertBin.insert_after, GstInsertBin.insert_before, GstInsertBin.prepend, GstInsertBin.remove
    """
    #  insertbin
    def __call__(
        self,
        insertbin: InsertBin,
        element: Gst.Element,
        success: bool,
        *user_data: object | None,
    ) -> None: ...

###############################################################
# Constants
###############################################################

_namespace: str = ...
_version: str = ...
###############################################################
# Unknowns/Not Parsed
###############################################################

# type: lock, element not parsed are:
#     - _lock
