# pyright: reportIncompatibleMethodOverride=false
"""
Stub template for a GI Repository Module.

Generated by gi-stub-gen, version 0.0.1.
Module: GstPbutils
Date: 2026-07-14
"""
# we disable method override report for pyright in generated stubs,
# causes too many false positives

from __future__ import annotations
from typing_extensions import deprecated  # noqa: F401
import typing_extensions  # noqa: F401

import builtins
import typing

# gi.repository imports needed by this Stub
from gi.repository import GLib
from gi.repository import GObject
from gi.repository import Gst
from gi.repository import GstAudio
from gi.repository import GstVideo
###############################################################
# Functions
###############################################################

def codec_utils_aac_caps_set_level_and_profile(
    caps: Gst.Caps,
    audio_config: bytes,
) -> bool:
    """
    Sets the level and profile on `caps` if it can be determined from
    `audio_config`. See `gst_codec_utils_aac_get_level` and
    `gst_codec_utils_aac_get_profile` for more details on the parameters.
    `caps` must be audio/mpeg caps with an "mpegversion" field of either 2 or 4.
    If mpegversion is 4, the "base-profile" field is also set in `caps`.
    """
    ...

def codec_utils_aac_get_channels(
    audio_config: bytes,
) -> int:
    """
    Returns the channels of the given AAC stream.
    """
    ...

def codec_utils_aac_get_index_from_sample_rate(
    rate: int,
) -> int:
    """
    Translates the sample rate to the index corresponding to it in AAC spec.
    """
    ...

def codec_utils_aac_get_level(
    audio_config: bytes,
) -> str | None:
    """
    Determines the level of a stream as defined in ISO/IEC 14496-3. For AAC LC
    streams, the constraints from the AAC audio profile are applied. For AAC
    Main, LTP, SSR and others, the Main profile is used.

    The `audio_config` parameter follows the following format, starting from the
    most significant bit of the first byte:

      * Bit 0:4 contains the AudioObjectType (if this is 0x5, then the
        real AudioObjectType is carried after the rate and channel data)
      * Bit 5:8 contains the sample frequency index (if this is 0xf, then the
        next 24 bits define the actual sample frequency, and subsequent
        fields are appropriately shifted).
      * Bit 9:12 contains the channel configuration
    """
    ...

def codec_utils_aac_get_profile(
    audio_config: bytes,
) -> str | None:
    """
    Returns the profile of the given AAC stream as a string. The profile is
    normally determined using the AudioObjectType field which is in the first
    5 bits of `audio_config`
    """
    ...

def codec_utils_aac_get_sample_rate(
    audio_config: bytes,
) -> int:
    """
    Translates the sample rate index found in AAC headers to the actual sample
    rate.
    """
    ...

def codec_utils_aac_get_sample_rate_from_index(
    sr_idx: int,
) -> int:
    """
    Translates the sample rate index found in AAC headers to the actual sample
    rate.
    """
    ...

def codec_utils_av1_create_av1c_from_caps(
    caps: Gst.Caps,
) -> Gst.Buffer | None:
    """
    Creates the corresponding AV1 Codec Configuration Record
    """
    ...

def codec_utils_av1_create_caps_from_av1c(
    av1c: Gst.Buffer,
) -> Gst.Caps | None:
    """
    Parses the provided `av1c` and returns the corresponding caps
    """
    ...

def codec_utils_av1_get_level(
    seq_level_idx: int,
) -> str | None:
    """
    Transform a seq_level_idx into the level string
    """
    ...

def codec_utils_av1_get_seq_level_idx(
    level: str,
) -> int:
    """
    Transform a level string from the caps into the seq_level_idx
    """
    ...

def codec_utils_caps_from_mime_codec(
    codecs_field: str,
) -> Gst.Caps | None:
    """
    Converts a RFC 6381 compatible codec string to GstCaps. More than one codec
    string can be present (separated by `,`).

    Registered codecs can be found at http://mp4ra.org/#/codecs
    """
    ...

def codec_utils_caps_get_mime_codec(
    caps: Gst.Caps,
) -> str | None:
    """
    Converts `caps` to a RFC 6381 compatible codec string if possible.

    Useful for providing the 'codecs' field inside the 'Content-Type' HTTP
    header for containerized formats, such as mp4 or matroska.

    Registered codecs can be found at http://mp4ra.org/#/codecs
    """
    ...

def codec_utils_h264_caps_set_level_and_profile(
    caps: Gst.Caps,
    sps: bytes,
) -> bool:
    """
    Sets the level and profile in `caps` if it can be determined from `sps`. See
    `gst_codec_utils_h264_get_level` and `gst_codec_utils_h264_get_profile`
    for more details on the parameters.
    """
    ...

def codec_utils_h264_get_level(
    sps: bytes,
) -> str | None:
    """
    Converts the level indication (level_idc) in the stream's
    sequence parameter set into a string. The SPS is expected to have the
    same format as for `gst_codec_utils_h264_get_profile`.
    """
    ...

def codec_utils_h264_get_level_idc(
    level: str,
) -> int:
    """
    Transform a level string from the caps into the level_idc
    """
    ...

def codec_utils_h264_get_profile(
    sps: bytes,
) -> str | None:
    """
    Converts the profile indication (profile_idc) in the stream's
    sequence parameter set into a string. The SPS is expected to have the
    following format, as defined in the H.264 specification. The SPS is viewed
    as a bitstream here, with bit 0 being the most significant bit of the first
    byte.

    * Bit 0:7   - Profile indication
    * Bit 8     - constraint_set0_flag
    * Bit 9     - constraint_set1_flag
    * Bit 10    - constraint_set2_flag
    * Bit 11    - constraint_set3_flag
    * Bit 12    - constraint_set3_flag
    * Bit 13:15 - Reserved
    * Bit 16:24 - Level indication
    """
    ...

def codec_utils_h264_get_profile_flags_level(
    codec_data: bytes,
) -> tuple[bool, int, int, int]:
    """
    Parses profile, flags, and level from a H264 AVCC extradata/sequence_header.
    These are most commonly retrieved from a video/x-h264 caps with a codec_data
    buffer.

    The format of H264 AVCC extradata/sequence_header is documented in the
    ITU-T H.264 specification section 7.3.2.1.1 as well as in ISO/IEC 14496-15
    section 5.3.3.1.2.
    """
    ...

def codec_utils_h265_caps_set_level_tier_and_profile(
    caps: Gst.Caps,
    profile_tier_level: bytes,
) -> bool:
    """
    Sets the level, tier and profile in `caps` if it can be determined from
    `profile_tier_level`. See `gst_codec_utils_h265_get_level`,
    `gst_codec_utils_h265_get_tier` and `gst_codec_utils_h265_get_profile`
    for more details on the parameters.
    """
    ...

def codec_utils_h265_get_level(
    profile_tier_level: bytes,
) -> str | None:
    """
    Converts the level indication (general_level_idc) in the stream's
    profile_tier_level structure into a string. The profiel_tier_level is
    expected to have the same format as for `gst_codec_utils_h264_get_profile`.
    """
    ...

def codec_utils_h265_get_level_idc(
    level: str,
) -> int:
    """
    Transform a level string from the caps into the level_idc
    """
    ...

def codec_utils_h265_get_profile(
    profile_tier_level: bytes,
) -> str | None:
    """
    Converts the profile indication (general_profile_idc) in the stream's
    profile_level_tier structure into a string. The profile_tier_level is
    expected to have the following format, as defined in the H.265
    specification. The profile_tier_level is viewed as a bitstream here,
    with bit 0 being the most significant bit of the first byte.

    * Bit 0:1   - general_profile_space
    * Bit 2     - general_tier_flag
    * Bit 3:7   - general_profile_idc
    * Bit 8:39  - gernal_profile_compatibility_flags
    * Bit 40    - general_progressive_source_flag
    * Bit 41    - general_interlaced_source_flag
    * Bit 42    - general_non_packed_constraint_flag
    * Bit 43    - general_frame_only_constraint_flag
    * Bit 44:87 - See below
    * Bit 88:95 - general_level_idc
    """
    ...

def codec_utils_h265_get_tier(
    profile_tier_level: bytes,
) -> str | None:
    """
    Converts the tier indication (general_tier_flag) in the stream's
    profile_tier_level structure into a string. The profile_tier_level
    is expected to have the same format as for `gst_codec_utils_h264_get_profile`.
    """
    ...

def codec_utils_h266_caps_set_level_tier_and_profile(
    caps: Gst.Caps,
    decoder_configuration: bytes,
) -> bool:
    """
    Sets the level, tier and profile in `caps` if it can be determined from
    `decoder_configuration`. See `gst_codec_utils_h266_get_level`,
    `gst_codec_utils_h266_get_tier` and `gst_codec_utils_h266_get_profile`
    for more details on the parameters.
    """
    ...

def codec_utils_h266_get_level(
    ptl_record: bytes,
) -> str | None:
    """
    Converts the level indication (general_level_idc) in the stream's
    ptl_record structure into a string.
    """
    ...

def codec_utils_h266_get_level_idc(
    level: str,
) -> int:
    """
    Transform a level string from the caps into the level_idc
    """
    ...

def codec_utils_h266_get_profile(
    ptl_record: bytes,
) -> str | None:
    """
    Converts the profile indication (general_profile_idc) in the stream's
    ptl_record structure into a string.
    """
    ...

def codec_utils_h266_get_tier(
    ptl_record: bytes,
) -> str | None:
    """
    Converts the tier indication (general_tier_flag) in the stream's
    ptl_record structure into a string.
    """
    ...

def codec_utils_mpeg4video_caps_set_level_and_profile(
    caps: Gst.Caps,
    vis_obj_seq: bytes,
) -> bool:
    """
    Sets the level and profile in `caps` if it can be determined from
    `vis_obj_seq`. See `gst_codec_utils_mpeg4video_get_level` and
    `gst_codec_utils_mpeg4video_get_profile` for more details on the
    parameters.
    """
    ...

def codec_utils_mpeg4video_get_level(
    vis_obj_seq: bytes,
) -> str | None:
    """
    Converts the level indication in the stream's visual object sequence into
    a string. `vis_obj_seq` is expected to be the data following the visual
    object sequence start code. Only the first byte
    (profile_and_level_indication) is used.
    """
    ...

def codec_utils_mpeg4video_get_profile(
    vis_obj_seq: bytes,
) -> str | None:
    """
    Converts the profile indication in the stream's visual object sequence into
    a string. `vis_obj_seq` is expected to be the data following the visual
    object sequence start code. Only the first byte
    (profile_and_level_indication) is used.
    """
    ...

def codec_utils_opus_create_caps(
    rate: int,
    channels: int,
    channel_mapping_family: int,
    stream_count: int,
    coupled_count: int,
    channel_mapping: bytes | None = None,
) -> Gst.Caps | None:
    """
    Creates Opus caps from the given parameters.
    """
    ...

def codec_utils_opus_create_caps_from_header(
    header: Gst.Buffer,
    comments: Gst.Buffer | None = None,
) -> Gst.Caps | None:
    """
    Creates Opus caps from the given OpusHead `header` and comment header
    `comments`.
    """
    ...

def codec_utils_opus_create_header(
    rate: int,
    channels: int,
    channel_mapping_family: int,
    stream_count: int,
    coupled_count: int,
    channel_mapping: bytes | None,
    pre_skip: int,
    output_gain: int,
) -> Gst.Buffer | None:
    """
    Creates OpusHead header from the given parameters.
    """
    ...

def codec_utils_opus_parse_caps(
    caps: Gst.Caps,
) -> tuple[bool, int, int, int, int, int, bytes]:
    """
    Parses Opus caps and fills the different fields with defaults if possible.
    """
    ...

def codec_utils_opus_parse_header(
    header: Gst.Buffer,
) -> tuple[bool, int, int, int, int, int, bytes, int, int]:
    """
    Parses the OpusHead header.
    """
    ...

def encoding_list_all_targets(
    categoryname: str | None = None,
) -> list[EncodingTarget]:
    """
    List all available GstEncodingTarget for the specified category, or all categories
    if `categoryname` is None.
    """
    ...

def encoding_list_available_categories() -> list[str]:
    """
    Lists all GstEncodingTarget categories present on disk.
    """
    ...

def install_plugins_async(
    details: list[str],
    ctx: InstallPluginsContext | None,
    func: InstallPluginsResultFunc,
    *user_data: object | None,
) -> InstallPluginsReturn:
    """
    Requests plugin installation without blocking. Once the plugins have been
    installed or installation has failed, `func` will be called with the result
    of the installation and your provided `user_data` pointer.

    This function requires a running GLib/Gtk main loop. If you are not
    running a GLib/Gtk main loop, make sure to regularly call
    g_main_context_iteration(None,False).

    The installer strings that make up `detail` are typically obtained by
    calling `gst_missing_plugin_message_get_installer_detail` on missing-plugin
    messages that have been caught on a pipeline's bus or created by the
    application via the provided API, such as `gst_missing_element_message_new`.

    It is possible to request the installation of multiple missing plugins in
    one go (as might be required if there is a demuxer for a certain format
    installed but no suitable video decoder and no suitable audio decoder).
    """
    ...

def install_plugins_installation_in_progress() -> bool:
    """
    Checks whether plugin installation (initiated by this application only)
    is currently in progress.
    """
    ...

def install_plugins_return_get_name(
    ret: InstallPluginsReturn,
) -> str:
    """
    Convenience function to return the descriptive string associated
    with a status code.  This function returns English strings and
    should not be used for user messages. It is here only to assist
    in debugging.
    """
    ...

def install_plugins_supported() -> bool:
    """
    Checks whether plugin installation is likely to be supported by the
    current environment. This currently only checks whether the helper script
    that is to be provided by the distribution or operating system vendor
    exists.
    """
    ...

def install_plugins_sync(
    details: list[str],
    ctx: InstallPluginsContext | None = None,
) -> InstallPluginsReturn:
    """
    Requests plugin installation and block until the plugins have been
    installed or installation has failed.

    This function should almost never be used, it only exists for cases where
    a non-GLib main loop is running and the user wants to run it in a separate
    thread and marshal the result back asynchronously into the main thread
    using the other non-GLib main loop. You should almost always use
    `gst_install_plugins_async` instead of this function.
    """
    ...

def is_missing_plugin_message(
    msg: Gst.Message,
) -> bool:
    """
    Checks whether `msg` is a missing plugins message.
    """
    ...

def missing_decoder_installer_detail_new(
    decode_caps: Gst.Caps,
) -> str:
    """
    Returns an opaque string containing all the details about the missing
    element to be passed to an external installer called via
    `gst_install_plugins_async` or `gst_install_plugins_sync`.

    This function is mainly for applications that call external plugin
    installation mechanisms using one of the two above-mentioned functions in
    the case where the application knows exactly what kind of plugin it is
    missing.
    """
    ...

def missing_decoder_message_new(
    element: Gst.Element,
    decode_caps: Gst.Caps,
) -> Gst.Message:
    """
    Creates a missing-plugin message for `element` to notify the application
    that a decoder element for a particular set of (fixed) caps is missing.
    This function is mainly for use in plugins.
    """
    ...

def missing_element_installer_detail_new(
    factory_name: str,
) -> str:
    """
    Returns an opaque string containing all the details about the missing
    element to be passed to an external installer called via
    `gst_install_plugins_async` or `gst_install_plugins_sync`.

    This function is mainly for applications that call external plugin
    installation mechanisms using one of the two above-mentioned functions in
    the case where the application knows exactly what kind of plugin it is
    missing.
    """
    ...

def missing_element_message_new(
    element: Gst.Element,
    factory_name: str,
) -> Gst.Message:
    """
    Creates a missing-plugin message for `element` to notify the application
    that a certain required element is missing. This function is mainly for
    use in plugins.
    """
    ...

def missing_encoder_installer_detail_new(
    encode_caps: Gst.Caps,
) -> str:
    """
    Returns an opaque string containing all the details about the missing
    element to be passed to an external installer called via
    `gst_install_plugins_async` or `gst_install_plugins_sync`.

    This function is mainly for applications that call external plugin
    installation mechanisms using one of the two above-mentioned functions in
    the case where the application knows exactly what kind of plugin it is
    missing.
    """
    ...

def missing_encoder_message_new(
    element: Gst.Element,
    encode_caps: Gst.Caps,
) -> Gst.Message:
    """
    Creates a missing-plugin message for `element` to notify the application
    that an encoder element for a particular set of (fixed) caps is missing.
    This function is mainly for use in plugins.
    """
    ...

def missing_plugin_message_get_description(
    msg: Gst.Message,
) -> str:
    """
    Returns a localised string describing the missing feature, for use in
    error dialogs and the like. Should never return None unless `msg` is not
    a valid missing-plugin message.

    This function is mainly for applications that need a human-readable string
    describing a missing plugin, given a previously collected missing-plugin
    message
    """
    ...

def missing_plugin_message_get_installer_detail(
    msg: Gst.Message,
) -> str | None:
    """
    Returns an opaque string containing all the details about the missing
    element to be passed to an external installer called via
    `gst_install_plugins_async` or `gst_install_plugins_sync`.

    This function is mainly for applications that call external plugin
    installation mechanisms using one of the two above-mentioned functions.
    """
    ...

def missing_plugin_message_get_stream_id(
    msg: Gst.Message,
) -> str | None:
    """
    Get the stream-id of the stream for which an element is missing.
    """
    ...

def missing_plugin_message_set_stream_id(
    msg: Gst.Message,
    stream_id: str,
) -> None:
    """
    Set the stream-id of the stream for which an element is missing.
    """
    ...

def missing_uri_sink_installer_detail_new(
    protocol: str,
) -> str:
    """
    Returns an opaque string containing all the details about the missing
    element to be passed to an external installer called via
    `gst_install_plugins_async` or `gst_install_plugins_sync`.

    This function is mainly for applications that call external plugin
    installation mechanisms using one of the two above-mentioned functions in
    the case where the application knows exactly what kind of plugin it is
    missing.
    """
    ...

def missing_uri_sink_message_new(
    element: Gst.Element,
    protocol: str,
) -> Gst.Message:
    """
    Creates a missing-plugin message for `element` to notify the application
    that a sink element for a particular URI protocol is missing. This
    function is mainly for use in plugins.
    """
    ...

def missing_uri_source_installer_detail_new(
    protocol: str,
) -> str:
    """
    Returns an opaque string containing all the details about the missing
    element to be passed to an external installer called via
    `gst_install_plugins_async` or `gst_install_plugins_sync`.

    This function is mainly for applications that call external plugin
    installation mechanisms using one of the two above-mentioned functions in
    the case where the application knows exactly what kind of plugin it is
    missing.
    """
    ...

def missing_uri_source_message_new(
    element: Gst.Element,
    protocol: str,
) -> Gst.Message:
    """
    Creates a missing-plugin message for `element` to notify the application
    that a source element for a particular URI protocol is missing. This
    function is mainly for use in plugins.
    """
    ...

def pb_utils_add_codec_description_to_tag_list(
    taglist: Gst.TagList,
    codec_tag: str | None,
    caps: Gst.Caps,
) -> bool:
    """
    Adds a codec tag describing the format specified by `caps` to `taglist`.
    """
    ...

def pb_utils_get_caps_description_flags(
    caps: Gst.Caps,
) -> PbUtilsCapsDescriptionFlags:
    """
    Returns flags that describe the format of the caps if known. No flags are
    set for unknown caps.
    """
    ...

def pb_utils_get_codec_description(
    caps: Gst.Caps,
) -> str | None:
    """
    Returns a localised (as far as this is possible) string describing the
    media format specified in `caps`, for use in error dialogs or other messages
    to be seen by the user. Should never return None unless `caps` is invalid.

    Also see the convenience function
    `gst_pb_utils_add_codec_description_to_tag_list`.
    """
    ...

def pb_utils_get_decoder_description(
    caps: Gst.Caps,
) -> str:
    """
    Returns a localised string describing an decoder for the format specified
    in `caps`, for use in error dialogs or other messages to be seen by the user.

    This function is mainly for internal use, applications would typically
    use `gst_missing_plugin_message_get_description` to get a description of
    a missing feature from a missing-plugin message.
    """
    ...

def pb_utils_get_element_description(
    factory_name: str,
) -> str:
    """
    Returns a localised string describing the given element, for use in
    error dialogs or other messages to be seen by the user.

    This function is mainly for internal use, applications would typically
    use `gst_missing_plugin_message_get_description` to get a description of
    a missing feature from a missing-plugin message.
    """
    ...

def pb_utils_get_encoder_description(
    caps: Gst.Caps,
) -> str:
    """
    Returns a localised string describing an encoder for the format specified
    in `caps`, for use in error dialogs or other messages to be seen by the user.

    This function is mainly for internal use, applications would typically
    use `gst_missing_plugin_message_get_description` to get a description of
    a missing feature from a missing-plugin message.
    """
    ...

def pb_utils_get_file_extension_from_caps(
    caps: Gst.Caps,
) -> str | None:
    """
    Returns a possible file extension for the given caps, if known.
    """
    ...

def pb_utils_get_sink_description(
    protocol: str,
) -> str:
    """
    Returns a localised string describing a sink element handling the protocol
    specified in `protocol`, for use in error dialogs or other messages to be
    seen by the user.

    This function is mainly for internal use, applications would typically
    use `gst_missing_plugin_message_get_description` to get a description of
    a missing feature from a missing-plugin message.
    """
    ...

def pb_utils_get_source_description(
    protocol: str,
) -> str:
    """
    Returns a localised string describing a source element handling the protocol
    specified in `protocol`, for use in error dialogs or other messages to be
    seen by the user.

    This function is mainly for internal use, applications would typically
    use `gst_missing_plugin_message_get_description` to get a description of
    a missing feature from a missing-plugin message.
    """
    ...

def plugins_base_version() -> tuple[int, int, int, int]:
    """
    Gets the version number of the GStreamer Plugins Base libraries.
    """
    ...

def plugins_base_version_string() -> str:
    """
    This function returns a string that is useful for describing this version
    of GStreamer's gst-plugins-base libraries to the outside world: user agent
    strings, logging, about dialogs ...
    """
    ...

###############################################################
# builtin_functions
###############################################################

def init() -> typing.Any: ...

###############################################################
# Enums/Flags
###############################################################

class AudioVisualizerShader(GObject.GEnum):
    """
    Different types of supported background shading functions."""

    NONE = 0
    """
    no shading
    """
    FADE = 1
    """
    plain fading
    """
    FADE_AND_MOVE_UP = 2
    """
    fade and move up
    """
    FADE_AND_MOVE_DOWN = 3
    """
    fade and move down
    """
    FADE_AND_MOVE_LEFT = 4
    """
    fade and move left
    """
    FADE_AND_MOVE_RIGHT = 5
    """
    fade and move right
    """
    FADE_AND_MOVE_HORIZ_OUT = 6
    """
    fade and move horizontally out
    """
    FADE_AND_MOVE_HORIZ_IN = 7
    """
    fade and move horizontally in
    """
    FADE_AND_MOVE_VERT_OUT = 8
    """
    fade and move vertically out
    """
    FADE_AND_MOVE_VERT_IN = 9
    """
    fade and move vertically in
    """

class DiscovererResult(GObject.GEnum):
    """
    Result values for the discovery process."""

    OK = 0
    """
    The discovery was successful
    """
    URI_INVALID = 1
    """
    the URI is invalid
    """
    ERROR = 2
    """
    an error happened and the GError is set
    """
    TIMEOUT = 3
    """
    the discovery timed-out
    """
    BUSY = 4
    """
    the discoverer was already discovering a file
    """
    MISSING_PLUGINS = 5
    """
    Some plugins are missing for full discovery
    """

class DiscovererSerializeFlags(GObject.GFlags):
    """
    You can use these flags to control what is serialized by
    `gst_discoverer_info_to_variant`"""

    BASIC = 0
    """
    Serialize only basic information, excluding
    caps, tags and miscellaneous information
    """
    CAPS = 1
    """
    Serialize the caps for each stream
    """
    TAGS = 2
    """
    Serialize the tags for each stream
    """
    MISC = 4
    """
    Serialize miscellaneous information for each stream
    """
    ALL = 7
    """
    Serialize all the available info, including
    caps, tags and miscellaneous information
    """

class InstallPluginsReturn(GObject.GEnum):
    """
    Result codes returned by `gst_install_plugins_async` and
    `gst_install_plugins_sync`, and also the result code passed to the
    GstInstallPluginsResultFunc specified with `gst_install_plugins_async`.

    These codes indicate success or failure of starting an external installer
    program and to what extent the requested plugins could be installed."""

    SUCCESS = 0
    """
    all of the requested plugins could be
        installed
    """
    NOT_FOUND = 1
    """
    no appropriate installation candidate for
        any of the requested plugins could be found. Only return this if nothing
        has been installed. Return GST_INSTALL_PLUGINS_PARTIAL_SUCCESS if
        some (but not all) of the requested plugins could be installed.
    """
    ERROR = 2
    """
    an error occurred during the installation. If
        this happens, the  user has already seen an error message and another
        one should not be displayed
    """
    PARTIAL_SUCCESS = 3
    """
    some of the requested plugins could
        be installed, but not all
    """
    USER_ABORT = 4
    """
    the user has aborted the installation
    """
    CRASHED = 100
    """
    the installer had an unclean exit code
        (ie. death by signal)
    """
    INVALID = 101
    """
    the helper returned an invalid status code
    """
    STARTED_OK = 200
    """
    returned by `gst_install_plugins_async` to
        indicate that everything went fine so far and the provided callback
        will be called with the result of the installation later
    """
    INTERNAL_FAILURE = 201
    """
    some internal failure has
        occurred when trying to start the installer
    """
    HELPER_MISSING = 202
    """
    the helper script to call the
        actual installer is not installed
    """
    INSTALL_IN_PROGRESS = 203
    """
    a previously-started plugin
        installation is still in progress, try again later
    """
    # gi Methods
    @staticmethod
    def get_name(ret: InstallPluginsReturn) -> str: ...

class PbUtilsCapsDescriptionFlags(GObject.GFlags):
    """
    Flags that are returned by `gst_pb_utils_get_caps_description_flags` and
    describe the format of the caps."""

    CONTAINER = 1
    """
    Caps describe a container format.
    """
    AUDIO = 2
    """
    Caps describe an audio format, or a
        container format that can store audio.
    """
    VIDEO = 4
    """
    Caps describe an video format, or a
        container format that can store video.
    """
    IMAGE = 8
    """
    Caps describe an image format, or a
        container format that can store image.
    """
    SUBTITLE = 16
    """
    Caps describe an subtitle format, or a
        container format that can store subtitles.
    """
    TAG = 32
    """
    Container format is a tags container.
    """
    GENERIC = 64
    """
    Container format can store any kind of
        stream type.
    """
    METADATA = 128
    """
    Caps describe a metadata format, or a container format that can store
    metadata.
    """

###############################################################
# classes
###############################################################

class AudioVisualizer(Gst.Element):
    """
    A baseclass for scopes (visualizers). It takes care of re-fitting the
    audio-rate to video-rate and handles renegotiation (downstream video size
    changes).

    It also provides several background shading effects. These effects are
    applied to a previous picture before the ``render`` implementation can draw a
    new frame.
    """

    class Props(Gst.Element.Props):
        shade_amount: int  # [shade-amount]: changed because contained invalid characters
        shader: AudioVisualizerShader

    @builtins.property
    def props(self) -> Props: ...

    # gi Fields
    @builtins.property
    def ainfo(self) -> GstAudio.AudioInfo | None: ...
    @builtins.property
    def parent(self) -> Gst.Element | None: ...
    @builtins.property
    def priv(self) -> AudioVisualizerPrivate | None: ...
    @builtins.property
    def req_spf(self) -> int: ...
    @builtins.property
    def vinfo(self) -> GstVideo.VideoInfo | None: ...

    # gi Methods
    def __init__(
        self,
        name: str | None = None,
        parent: Gst.Object | None = None,
        shade_amount: int | None = None,
        shader: AudioVisualizerShader | None = AudioVisualizerShader.FADE,
    ) -> None:
        """
        Initialize AudioVisualizer object with properties.
        """

    # python methods (overrides?)
    def do_decide_allocation(
        self,
        query: Gst.Query,
    ) -> bool:
        """
        decide_allocation(self, query:Gst.Query) -> bool
        """
    def do_render(
        self,
        audio: Gst.Buffer,
        video: GstVideo.VideoFrame,
    ) -> bool:
        """
        render(self, audio:Gst.Buffer, video:GstVideo.VideoFrame) -> bool
        """
    def do_setup(
        self,
    ) -> bool:
        """
        setup(self) -> bool
        """

    # Signals
    @typing.overload
    def connect(
        self, detailed_signal: typing.Literal["no-more-pads"], handler: typing.Callable[..., None], *args: typing.Any
    ) -> int: ...
    @typing.overload
    def connect(
        self,
        detailed_signal: typing.Literal["pad-added"],
        handler: typing.Callable[[typing_extensions.Self, Gst.Pad], None],
        *args: typing.Any,
    ) -> int: ...
    @typing.overload
    def connect(
        self,
        detailed_signal: typing.Literal["pad-removed"],
        handler: typing.Callable[[typing_extensions.Self, Gst.Pad], None],
        *args: typing.Any,
    ) -> int: ...
    @typing.overload
    def connect(
        self,
        detailed_signal: typing.Literal["deep-notify"],
        handler: typing.Callable[[typing_extensions.Self, Gst.Object, GObject.ParamSpec], None],
        *args: typing.Any,
    ) -> int: ...
    @typing.overload
    def connect(
        self,
        detailed_signal: typing.Literal["notify"],
        handler: typing.Callable[[typing_extensions.Self, GObject.ParamSpec], None],
        *args: typing.Any,
    ) -> int: ...
    @typing.overload
    def connect(
        self,
        detailed_signal: typing.Literal["notify::shade_amount"],
        handler: typing.Callable[[typing_extensions.Self, GObject.ParamSpec, typing.Any], None],
        *args: typing.Any,
    ) -> int: ...
    @typing.overload
    def connect(
        self,
        detailed_signal: typing.Literal["notify::shader"],
        handler: typing.Callable[[typing_extensions.Self, GObject.ParamSpec, typing.Any], None],
        *args: typing.Any,
    ) -> int: ...
    @typing.overload
    def connect(
        self,
        detailed_signal: typing.Literal["notify::name"],
        handler: typing.Callable[[typing_extensions.Self, GObject.ParamSpec, typing.Any], None],
        *args: typing.Any,
    ) -> int: ...
    @typing.overload
    def connect(
        self,
        detailed_signal: typing.Literal["notify::parent"],
        handler: typing.Callable[[typing_extensions.Self, GObject.ParamSpec, typing.Any], None],
        *args: typing.Any,
    ) -> int: ...
    @typing.overload
    def connect(  # type: ignore otherwise pylance will complain and we should repeat all parent overloads here..
        self, detailed_signal: str, handler: typing.Callable[..., typing.Any], *args: typing.Any
    ) -> int: ...

class AudioVisualizerClass(GObject.GPointer, metaclass=GObject.GType):
    # gi Fields
    @builtins.property
    def decide_allocation(self) -> decide_allocationAudioVisualizerClassCB: ...
    @builtins.property
    def parent_class(self) -> Gst.ElementClass | None: ...
    @builtins.property
    def render(self) -> renderAudioVisualizerClassCB: ...
    @builtins.property
    def setup(self) -> setupAudioVisualizerClassCB: ...

class AudioVisualizerPrivate(GObject.GPointer, metaclass=GObject.GType): ...

class Discoverer(GObject.Object):
    """
    The GstDiscoverer is a utility object which allows to get as much
    information as possible from one or many URIs.

    It provides two APIs, allowing usage in blocking or non-blocking mode.

    The blocking mode just requires calling `gst_discoverer_discover_uri`
    with the URI one wishes to discover.

    The non-blocking mode requires a running GMainLoop iterating a
    GMainContext, where one connects to the various signals, appends the
    URIs to be processed (through `gst_discoverer_discover_uri_async`) and then
    asks for the discovery to begin (through `gst_discoverer_start`).
    By default this will use the GLib default main context unless you have
    set a custom context using `g_main_context_push_thread_default`.

    All the information is returned in a GstDiscovererInfo structure.
    """

    class Props(GObject.Object.Props):
        timeout: int
        """
        The duration (in nanoseconds) after which the discovery of an individual
        URI will timeout.

        If the discovery of a URI times out, the GST_DISCOVERER_TIMEOUT will be
        set on the result flags.
        """
        use_cache: bool  # [use-cache]: changed because contained invalid characters

    @builtins.property
    def props(self) -> Props: ...

    # gi Fields
    @builtins.property
    def _reserved(self) -> list[object] | None: ...
    @builtins.property
    def parent(self) -> GObject.Object | None: ...
    @builtins.property
    def priv(self) -> DiscovererPrivate | None: ...

    # gi Methods
    def __init__(self, timeout: int | None = None, use_cache: bool | None = None) -> None:
        """
        Initialize Discoverer object with properties.
        """
    def discover_uri(self, uri: str) -> DiscovererInfo:
        """
            Synchronously discovers the given `uri`.

        A copy of `uri` will be made internally, so the caller can safely `g_free`
        afterwards.
        """
    def discover_uri_async(self, uri: str) -> bool:
        """
            Appends the given `uri` to the list of URIs to discoverer. The actual
        discovery of the `uri` will only take place if `gst_discoverer_start` has
        been called.

        A copy of `uri` will be made internally, so the caller can safely `g_free`
        afterwards.
        """
    def start(self) -> None:
        """
            Allow asynchronous discovering of URIs to take place.
        A GMainLoop must be available for GstDiscoverer to properly work in
        asynchronous mode.
        """
    def stop(self) -> None:
        """
            Stop the discovery of any pending URIs and clears the list of
        pending URIS (if any).
        """

    # python methods (overrides?)
    def do_discovered(
        self,
        info: DiscovererInfo,
        err: GLib.Error,
    ) -> None:
        """
        discovered(self, info:GstPbutils.DiscovererInfo, err:error)
        """
    def do_finished(
        self,
    ) -> None:
        """
        finished(self)
        """
    def do_load_serialize_info(
        self,
        uri: str,
    ) -> DiscovererInfo:
        """
        load_serialize_info(self, uri:str) -> GstPbutils.DiscovererInfo
        """
    def do_source_setup(
        self,
        source: Gst.Element,
    ) -> None:
        """
        source_setup(self, source:Gst.Element)
        """
    def do_starting(
        self,
    ) -> None:
        """
        starting(self)
        """
    @classmethod
    def new(
        cls,
        timeout: int,
    ) -> Discoverer:
        """
        [is-override: Note this method is an override in Python of the original gi implementation.]

        new(timeout:int) -> GstPbutils.Discoverer

        Creates a new GstDiscoverer with the provided timeout.
        """

    # Signals
    @typing.overload
    def connect(
        self,
        detailed_signal: typing.Literal["discovered"],
        handler: typing.Callable[[typing_extensions.Self, DiscovererInfo, GLib.Error | None], None],
        *args: typing.Any,
    ) -> int:
        """
            Will be emitted in async mode when all information on a URI could be
        discovered, or an error occurred.

        When an error occurs, `info` might still contain some partial information,
        depending on the circumstances of the error.
        """
    @typing.overload
    def connect(
        self, detailed_signal: typing.Literal["finished"], handler: typing.Callable[..., None], *args: typing.Any
    ) -> int:
        """
        Will be emitted in async mode when all pending URIs have been processed.
        """
    @typing.overload
    def connect(
        self,
        detailed_signal: typing.Literal["load-serialized-info"],
        handler: typing.Callable[[typing_extensions.Self, str], DiscovererInfo | None],
        *args: typing.Any,
    ) -> int:
        """
            Retrieves information about a URI from and external source of information,
        like a cache file. This is used by the discoverer to speed up the
        discovery.
        """
    @typing.overload
    def connect(
        self,
        detailed_signal: typing.Literal["source-setup"],
        handler: typing.Callable[[typing_extensions.Self, Gst.Element], None],
        *args: typing.Any,
    ) -> int:
        """
            This signal is emitted after the source element has been created for, so
        the URI being discovered, so it can be configured by setting additional
        properties (e.g. set a proxy server for an http source, or set the device
        and read speed for an audio cd source).

        This signal is usually emitted from the context of a GStreamer streaming
        thread.
        """
    @typing.overload
    def connect(
        self, detailed_signal: typing.Literal["starting"], handler: typing.Callable[..., None], *args: typing.Any
    ) -> int:
        """
        Will be emitted when the discover starts analyzing the pending URIs
        """
    @typing.overload
    def connect(
        self,
        detailed_signal: typing.Literal["notify"],
        handler: typing.Callable[[typing_extensions.Self, GObject.ParamSpec], None],
        *args: typing.Any,
    ) -> int: ...
    @typing.overload
    def connect(
        self,
        detailed_signal: typing.Literal["notify::timeout"],
        handler: typing.Callable[[typing_extensions.Self, GObject.ParamSpec, typing.Any], None],
        *args: typing.Any,
    ) -> int: ...
    @typing.overload
    def connect(
        self,
        detailed_signal: typing.Literal["notify::use_cache"],
        handler: typing.Callable[[typing_extensions.Self, GObject.ParamSpec, typing.Any], None],
        *args: typing.Any,
    ) -> int: ...
    @typing.overload
    def connect(  # type: ignore otherwise pylance will complain and we should repeat all parent overloads here..
        self, detailed_signal: str, handler: typing.Callable[..., typing.Any], *args: typing.Any
    ) -> int: ...

class DiscovererAudioInfo(DiscovererStreamInfo):
    """
    GstDiscovererStreamInfo specific to audio streams.
    """

    # gi Methods
    def __init__(self) -> None:
        """
        Initialize DiscovererAudioInfo object with properties.
        """
    def get_bitrate(self) -> int: ...
    def get_channel_mask(self) -> int: ...
    def get_channels(self) -> int: ...
    def get_depth(self) -> int: ...
    def get_language(self) -> str | None: ...
    def get_max_bitrate(self) -> int: ...
    def get_sample_rate(self) -> int: ...

    # Signals
    @typing.overload
    def connect(
        self,
        detailed_signal: typing.Literal["notify"],
        handler: typing.Callable[[typing_extensions.Self, GObject.ParamSpec], None],
        *args: typing.Any,
    ) -> int: ...
    @typing.overload
    def connect(  # type: ignore otherwise pylance will complain and we should repeat all parent overloads here..
        self, detailed_signal: str, handler: typing.Callable[..., typing.Any], *args: typing.Any
    ) -> int: ...

class DiscovererClass(GObject.GPointer, metaclass=GObject.GType):
    # gi Fields
    @builtins.property
    def _reserved(self) -> list[object] | None: ...
    @builtins.property
    def discovered(self) -> discoveredDiscovererClassCB: ...
    @builtins.property
    def finished(self) -> finishedDiscovererClassCB: ...
    @builtins.property
    def load_serialize_info(self) -> load_serialize_infoDiscovererClassCB: ...
    @builtins.property
    def parentclass(self) -> GObject.ObjectClass | None: ...
    @builtins.property
    def source_setup(self) -> source_setupDiscovererClassCB: ...
    @builtins.property
    def starting(self) -> startingDiscovererClassCB: ...

class DiscovererContainerInfo(DiscovererStreamInfo):
    """
    GstDiscovererStreamInfo specific to container streams.
    """

    # gi Methods
    def __init__(self) -> None:
        """
        Initialize DiscovererContainerInfo object with properties.
        """
    def get_streams(self) -> list[DiscovererStreamInfo]: ...
    def get_tags(self) -> Gst.TagList | None: ...

    # Signals
    @typing.overload
    def connect(
        self,
        detailed_signal: typing.Literal["notify"],
        handler: typing.Callable[[typing_extensions.Self, GObject.ParamSpec], None],
        *args: typing.Any,
    ) -> int: ...
    @typing.overload
    def connect(  # type: ignore otherwise pylance will complain and we should repeat all parent overloads here..
        self, detailed_signal: str, handler: typing.Callable[..., typing.Any], *args: typing.Any
    ) -> int: ...

class DiscovererInfo(GObject.Object):
    """
    Structure containing the information of a URI analyzed by GstDiscoverer.
    """

    # gi Methods
    def __init__(self) -> None:
        """
        Initialize DiscovererInfo object with properties.
        """
    def copy(self) -> DiscovererInfo: ...
    @staticmethod
    def from_variant(variant: GLib.Variant) -> DiscovererInfo | None:
        """
            Parses a GVariant as produced by `gst_discoverer_info_to_variant`
        back to a GstDiscovererInfo.
        """
    def get_audio_streams(self) -> list[DiscovererAudioInfo]:
        """
        Finds all the GstDiscovererAudioInfo contained in `info`
        """
    def get_container_streams(self) -> list[DiscovererContainerInfo]:
        """
        Finds all the GstDiscovererContainerInfo contained in `info`
        """
    def get_duration(self) -> int: ...
    def get_live(self) -> bool: ...
    @deprecated("deprecated")
    def get_misc(self) -> Gst.Structure | None: ...
    def get_missing_elements_installer_details(self) -> list[str]:
        """
        Get the installer details for missing elements
        """
    def get_result(self) -> DiscovererResult: ...
    def get_seekable(self) -> bool: ...
    def get_stream_info(self) -> DiscovererStreamInfo | None: ...
    def get_stream_list(self) -> list[DiscovererStreamInfo]: ...
    def get_streams(self, streamtype: GObject.GType) -> list[DiscovererStreamInfo]:
        """
            Finds the GstDiscovererStreamInfo contained in `info` that match the
        given `streamtype`.
        """
    def get_subtitle_streams(self) -> list[DiscovererSubtitleInfo]:
        """
        Finds all the GstDiscovererSubtitleInfo contained in `info`
        """
    @deprecated("deprecated")
    def get_tags(self) -> Gst.TagList | None: ...
    def get_toc(self) -> Gst.Toc | None: ...
    def get_uri(self) -> str: ...
    def get_video_streams(self) -> list[DiscovererVideoInfo]:
        """
        Finds all the GstDiscovererVideoInfo contained in `info`
        """
    def to_variant(self, flags: DiscovererSerializeFlags) -> GLib.Variant:
        """
            Serializes `info` to a GVariant that can be parsed again
        through `gst_discoverer_info_from_variant`.

        Note that any GstToc (s) that might have been discovered will not be serialized
        for now.
        """

    # Signals
    @typing.overload
    def connect(
        self,
        detailed_signal: typing.Literal["notify"],
        handler: typing.Callable[[typing_extensions.Self, GObject.ParamSpec], None],
        *args: typing.Any,
    ) -> int: ...
    @typing.overload
    def connect(  # type: ignore otherwise pylance will complain and we should repeat all parent overloads here..
        self, detailed_signal: str, handler: typing.Callable[..., typing.Any], *args: typing.Any
    ) -> int: ...

class DiscovererPrivate(GObject.GPointer, metaclass=GObject.GType): ...

class DiscovererStreamInfo(GObject.Object):
    """
    Base structure for information concerning a media stream. Depending on the
    stream type, one can find more media-specific information in
    GstDiscovererAudioInfo, GstDiscovererVideoInfo, and
    GstDiscovererContainerInfo.

    The GstDiscovererStreamInfo represents the topology of the stream. Siblings
    can be iterated over with `gst_discoverer_stream_info_get_next` and
    `gst_discoverer_stream_info_get_previous`. Children (sub-streams) of a
    stream can be accessed using the GstDiscovererContainerInfo API.

    As a simple example, if you run GstDiscoverer on an AVI file with one audio
    and one video stream, you will get a GstDiscovererContainerInfo
    corresponding to the AVI container, which in turn will have a
    GstDiscovererAudioInfo sub-stream and a GstDiscovererVideoInfo sub-stream
    for the audio and video streams respectively.
    """

    # gi Methods
    def __init__(self) -> None:
        """
        Initialize DiscovererStreamInfo object with properties.
        """
    def get_caps(self) -> Gst.Caps | None: ...
    @deprecated("deprecated")
    def get_misc(self) -> Gst.Structure | None: ...
    def get_next(self) -> DiscovererStreamInfo | None: ...
    def get_previous(self) -> DiscovererStreamInfo | None: ...
    def get_stream_id(self) -> str | None: ...
    def get_stream_number(self) -> int: ...
    def get_stream_type_nick(self) -> str: ...
    def get_tags(self) -> Gst.TagList | None: ...
    def get_toc(self) -> Gst.Toc | None: ...
    @staticmethod
    def list_free(infos: list[DiscovererStreamInfo]) -> None:
        """
            Decrements the reference count of all contained GstDiscovererStreamInfo
        and fress the GList.
        """

    # Signals
    @typing.overload
    def connect(
        self,
        detailed_signal: typing.Literal["notify"],
        handler: typing.Callable[[typing_extensions.Self, GObject.ParamSpec], None],
        *args: typing.Any,
    ) -> int: ...
    @typing.overload
    def connect(  # type: ignore otherwise pylance will complain and we should repeat all parent overloads here..
        self, detailed_signal: str, handler: typing.Callable[..., typing.Any], *args: typing.Any
    ) -> int: ...

class DiscovererSubtitleInfo(DiscovererStreamInfo):
    """
    GstDiscovererStreamInfo specific to subtitle streams (this includes text and
    image based ones).
    """

    # gi Methods
    def __init__(self) -> None:
        """
        Initialize DiscovererSubtitleInfo object with properties.
        """
    def get_language(self) -> str | None: ...

    # Signals
    @typing.overload
    def connect(
        self,
        detailed_signal: typing.Literal["notify"],
        handler: typing.Callable[[typing_extensions.Self, GObject.ParamSpec], None],
        *args: typing.Any,
    ) -> int: ...
    @typing.overload
    def connect(  # type: ignore otherwise pylance will complain and we should repeat all parent overloads here..
        self, detailed_signal: str, handler: typing.Callable[..., typing.Any], *args: typing.Any
    ) -> int: ...

class DiscovererVideoInfo(DiscovererStreamInfo):
    """
    GstDiscovererStreamInfo specific to video streams (this includes images).
    """

    # gi Methods
    def __init__(self) -> None:
        """
        Initialize DiscovererVideoInfo object with properties.
        """
    def get_bitrate(self) -> int: ...
    def get_depth(self) -> int: ...
    def get_framerate_denom(self) -> int: ...
    def get_framerate_num(self) -> int: ...
    def get_height(self) -> int: ...
    def get_max_bitrate(self) -> int: ...
    def get_par_denom(self) -> int: ...
    def get_par_num(self) -> int: ...
    def get_width(self) -> int: ...
    def is_image(self) -> bool: ...
    def is_interlaced(self) -> bool: ...

    # Signals
    @typing.overload
    def connect(
        self,
        detailed_signal: typing.Literal["notify"],
        handler: typing.Callable[[typing_extensions.Self, GObject.ParamSpec], None],
        *args: typing.Any,
    ) -> int: ...
    @typing.overload
    def connect(  # type: ignore otherwise pylance will complain and we should repeat all parent overloads here..
        self, detailed_signal: str, handler: typing.Callable[..., typing.Any], *args: typing.Any
    ) -> int: ...

class EncodingAudioProfile(EncodingProfile):
    """
    Variant of GstEncodingProfile for audio streams.
    """

    # gi Methods

    # python methods (overrides?)
    def __init__(
        self,
        format: typing.Any,
        preset: typing.Any = None,
        restriction: typing.Any = None,
        presence: typing.Any = 0,
    ) -> None: ...
    @classmethod
    def new(
        cls,
        format: Gst.Caps,
        preset: str | None,
        restriction: Gst.Caps | None,
        presence: int,
    ) -> EncodingAudioProfile:
        """
        [is-override: Note this method is an override in Python of the original gi implementation.]

        new(format:Gst.Caps, preset:str=None, restriction:Gst.Caps=None, presence:int) -> GstPbutils.EncodingAudioProfile

        Creates a new GstEncodingAudioProfile

        All provided allocatable arguments will be internally copied, so can be
        safely freed/unreferenced after calling this method.
        """

    # Signals
    @typing.overload
    def connect(
        self,
        detailed_signal: typing.Literal["notify"],
        handler: typing.Callable[[typing_extensions.Self, GObject.ParamSpec], None],
        *args: typing.Any,
    ) -> int: ...
    @typing.overload
    def connect(
        self,
        detailed_signal: typing.Literal["notify::element_properties"],
        handler: typing.Callable[[typing_extensions.Self, GObject.ParamSpec, typing.Any], None],
        *args: typing.Any,
    ) -> int: ...
    @typing.overload
    def connect(
        self,
        detailed_signal: typing.Literal["notify::restriction_caps"],
        handler: typing.Callable[[typing_extensions.Self, GObject.ParamSpec, typing.Any], None],
        *args: typing.Any,
    ) -> int: ...
    @typing.overload
    def connect(  # type: ignore otherwise pylance will complain and we should repeat all parent overloads here..
        self, detailed_signal: str, handler: typing.Callable[..., typing.Any], *args: typing.Any
    ) -> int: ...

class EncodingAudioProfileClass(GObject.GPointer, metaclass=GObject.GType): ...

class EncodingContainerProfile(EncodingProfile):
    """
    Encoding profiles for containers. Keeps track of a list of GstEncodingProfile
    """

    # gi Methods
    def add_profile(self, profile: EncodingProfile) -> bool:
        """
            Add a GstEncodingProfile to the list of profiles handled by `container`.

        No copy of `profile` will be made, if you wish to use it elsewhere after this
        method you should increment its reference count.
        """
    def contains_profile(self, profile: EncodingProfile) -> bool:
        """
            Checks if `container` contains a GstEncodingProfile identical to
        `profile`.
        """
    def get_profiles(self) -> list[EncodingProfile]: ...

    # python methods (overrides?)
    def __init__(
        self,
        name: typing.Any,
        description: typing.Any,
        format: typing.Any,
        preset: typing.Any = None,
    ) -> None: ...
    @classmethod
    def new(
        cls,
        name: str | None,
        description: str | None,
        format: Gst.Caps,
        preset: str | None = None,
    ) -> EncodingContainerProfile:
        """
        [is-override: Note this method is an override in Python of the original gi implementation.]

        new(name:str=None, description:str=None, format:Gst.Caps, preset:str=None) -> GstPbutils.EncodingContainerProfile

        Creates a new GstEncodingContainerProfile.
        """

    # Signals
    @typing.overload
    def connect(
        self,
        detailed_signal: typing.Literal["notify"],
        handler: typing.Callable[[typing_extensions.Self, GObject.ParamSpec], None],
        *args: typing.Any,
    ) -> int: ...
    @typing.overload
    def connect(
        self,
        detailed_signal: typing.Literal["notify::element_properties"],
        handler: typing.Callable[[typing_extensions.Self, GObject.ParamSpec, typing.Any], None],
        *args: typing.Any,
    ) -> int: ...
    @typing.overload
    def connect(
        self,
        detailed_signal: typing.Literal["notify::restriction_caps"],
        handler: typing.Callable[[typing_extensions.Self, GObject.ParamSpec, typing.Any], None],
        *args: typing.Any,
    ) -> int: ...
    @typing.overload
    def connect(  # type: ignore otherwise pylance will complain and we should repeat all parent overloads here..
        self, detailed_signal: str, handler: typing.Callable[..., typing.Any], *args: typing.Any
    ) -> int: ...

class EncodingContainerProfileClass(GObject.GPointer, metaclass=GObject.GType): ...

class EncodingProfile(GObject.Object):
    """
    The opaque base class object for all encoding profiles. This contains generic
    information like name, description, format and preset.
    """

    class Props(GObject.Object.Props):
        element_properties: Gst.Structure | None  # [element-properties]: changed because contained invalid characters
        """
        A GstStructure defining the properties to be set to the element
        the profile represents.

        For example for `av1enc`:

        ```
        element-properties,row-mt=true, end-usage=vbr
        ```
        """
        restriction_caps: Gst.Caps | None  # [restriction-caps]: changed because contained invalid characters

    @builtins.property
    def props(self) -> Props: ...

    # gi Methods
    def __init__(
        self, element_properties: Gst.Structure | None = None, restriction_caps: Gst.Caps | None = None
    ) -> None:
        """
        Initialize EncodingProfile object with properties.
        """
    def copy(self) -> EncodingProfile:
        """
        Makes a deep copy of `self`
        """
    @staticmethod
    def find(targetname: str, profilename: str | None = None, category: str | None = None) -> EncodingProfile | None:
        """
        Find the GstEncodingProfile with the specified name and category.
        """
    @staticmethod
    def from_discoverer(info: DiscovererInfo) -> EncodingProfile | None:
        """
            Creates a GstEncodingProfile matching the formats from the given
        GstDiscovererInfo. Streams other than audio or video (eg,
        subtitles), are currently ignored.
        """
    @staticmethod
    def from_string(string: str) -> EncodingProfile | None:
        """
            Converts a string in the "encoding profile serialization format" into a
        GstEncodingProfile. Refer to the encoding-profile documentation for details
        on the format.
        """
    def get_allow_dynamic_output(self) -> bool:
        """
            Get whether the format that has been negotiated in at some point can be renegotiated
        later during the encoding.
        """
    def get_description(self) -> str | None: ...
    def get_element_properties(self) -> Gst.Structure | None: ...
    def get_file_extension(self) -> str | None: ...
    def get_format(self) -> Gst.Caps: ...
    def get_input_caps(self) -> Gst.Caps:
        """
        Computes the full output caps that this `profile` will be able to consume.
        """
    def get_name(self) -> str | None: ...
    def get_presence(self) -> int: ...
    def get_preset(self) -> str | None: ...
    def get_preset_name(self) -> str | None: ...
    def get_restriction(self) -> Gst.Caps | None: ...
    def get_single_segment(self) -> bool: ...
    def get_type_nick(self) -> str: ...
    def is_enabled(self) -> bool: ...
    def is_equal(self, b: EncodingProfile) -> bool:
        """
        Checks whether the two GstEncodingProfile are equal
        """
    def set_allow_dynamic_output(self, allow_dynamic_output: bool) -> None:
        """
            Sets whether the format that has been negotiated in at some point can be renegotiated
        later during the encoding.
        """
    def set_description(self, description: str | None = None) -> None:
        """
            Set `description` as the given description for the `profile`. A copy of
        `description` will be made internally.
        """
    def set_element_properties(self, element_properties: Gst.Structure) -> None:
        """
            This allows setting the muxing/encoding element properties.

        **Set properties generically**

        ``` properties
         [element-properties, boolean-prop=true, string-prop="hi"]
        ```

        **Mapping properties with well known element factories**

        ``` properties
        element-properties-map, map = {
             [openh264enc, gop-size=32, ],
             [x264enc, key-int-max=32, tune=zerolatency],
         }
        ```
        """
    def set_enabled(self, enabled: bool) -> None:
        """
        Set whether the profile should be used or not.
        """
    def set_format(self, format: Gst.Caps) -> None:
        """
        Sets the media format used in the profile.
        """
    def set_name(self, name: str | None = None) -> None:
        """
            Set `name` as the given name for the `profile`. A copy of `name` will be made
        internally.
        """
    def set_presence(self, presence: int) -> None:
        """
            Set the number of time the profile is used in its parent
        container profile. If 0, it is not a mandatory stream
        """
    def set_preset(self, preset: str | None = None) -> None:
        """
            Sets the name of the preset to be used in the profile.
        This is the name that has been set when saving the preset.
        You can list the available presets for a specific element factory
        using  `$ gst-inspect-1.0 element-factory-name`, for example for
        `x264enc`:

        ``` bash
        $ gst-inspect-1.0 x264enc
        ...
        Presets:
         "Profile Baseline": Baseline Profile
         "Profile High": High Profile
         "Profile Main": Main Profile
         "Profile YouTube": YouTube recommended settings (https://support.google.com/youtube/answer/1722171)
         "Quality High": High quality
         "Quality Low": Low quality
         "Quality Normal": Normal quality
         "Zero Latency"
        ```
         }
        """
    def set_preset_name(self, preset_name: str | None = None) -> None:
        """
            Sets the name of the GstPreset's factory to be used in the profile. This
        is the name of the **element factory** that implements the GstPreset interface not
        the name of the preset itself (see #gst_encoding_profile_set_preset).
        """
    def set_restriction(self, restriction: Gst.Caps | None = None) -> None:
        """
            Set the restriction GstCaps to apply before the encoder
        that will be used in the profile. See `gst_encoding_profile_get_restriction`
        for more about restrictions. Does not apply to GstEncodingContainerProfile.
        """
    def set_single_segment(self, single_segment: bool) -> None:
        """
            If using a single segment, buffers will be retimestamped and segments will be
        eat so as to appear as one segment.

        > *NOTE*: Single segment is not property supported when using
        > #encodebin:avoid-reencoding
        """
    def to_string(self) -> str:
        """
            Converts a GstEncodingProfile to a string in the "Encoding Profile
        serialization format".
        """

    # Signals
    @typing.overload
    def connect(
        self,
        detailed_signal: typing.Literal["notify"],
        handler: typing.Callable[[typing_extensions.Self, GObject.ParamSpec], None],
        *args: typing.Any,
    ) -> int: ...
    @typing.overload
    def connect(
        self,
        detailed_signal: typing.Literal["notify::element_properties"],
        handler: typing.Callable[[typing_extensions.Self, GObject.ParamSpec, typing.Any], None],
        *args: typing.Any,
    ) -> int: ...
    @typing.overload
    def connect(
        self,
        detailed_signal: typing.Literal["notify::restriction_caps"],
        handler: typing.Callable[[typing_extensions.Self, GObject.ParamSpec, typing.Any], None],
        *args: typing.Any,
    ) -> int: ...
    @typing.overload
    def connect(  # type: ignore otherwise pylance will complain and we should repeat all parent overloads here..
        self, detailed_signal: str, handler: typing.Callable[..., typing.Any], *args: typing.Any
    ) -> int: ...

class EncodingProfileClass(GObject.GPointer, metaclass=GObject.GType): ...

class EncodingTarget(GObject.Object):
    """
    Collection of GstEncodingProfile for a specific target or use-case.

    When being stored/loaded, targets come from a specific category, like
    GST_ENCODING_CATEGORY_DEVICE.
    """

    # gi Methods
    def __init__(self) -> None:
        """
        Initialize EncodingTarget object with properties.
        """
    def add_profile(self, profile: EncodingProfile) -> bool:
        """
            Adds the given `profile` to the `target`. Each added profile must have
        a unique name within the profile.

        The `target` will steal a reference to the `profile`. If you wish to use
        the profile after calling this method, you should increase its reference
        count.
        """
    def get_category(self) -> str: ...
    def get_description(self) -> str: ...
    def get_name(self) -> str: ...
    def get_path(self) -> str | None: ...
    def get_profile(self, name: str) -> EncodingProfile | None: ...
    def get_profiles(self) -> list[EncodingProfile]: ...
    @staticmethod
    def load(name: str, category: str | None = None) -> EncodingTarget:
        """
            Searches for the GstEncodingTarget with the given name, loads it
        and returns it.

        If the category name is specified only targets from that category will be
        searched for.
        """
    @staticmethod
    def load_from_file(filepath: str) -> EncodingTarget:
        """
        Opens the provided file and returns the contained GstEncodingTarget.
        """
    def save(self) -> bool:
        """
        Saves the `target` to a default user-local directory.
        """
    def save_to_file(self, filepath: str) -> bool:
        """
        Saves the `target` to the provided file location.
        """

    # python methods (overrides?)
    @classmethod
    def new(
        cls,
        name: str,
        category: str,
        description: str,
        profiles: list[EncodingProfile],
    ) -> EncodingTarget | None:
        """
        [is-override: Note this method is an override in Python of the original gi implementation.]

        new(name:str, category:str, description:str, profiles:list) -> GstPbutils.EncodingTarget or None

        Creates a new GstEncodingTarget.

        The name and category can only consist of lowercase ASCII letters for the
        first character, followed by either lowercase ASCII letters, digits or
        hyphens ('-').

        The `category` *should* be one of the existing
        well-defined categories, like GST_ENCODING_CATEGORY_DEVICE, but it
        *can* be a application or user specific category if
        needed.
        """

    # Signals
    @typing.overload
    def connect(
        self,
        detailed_signal: typing.Literal["notify"],
        handler: typing.Callable[[typing_extensions.Self, GObject.ParamSpec], None],
        *args: typing.Any,
    ) -> int: ...
    @typing.overload
    def connect(  # type: ignore otherwise pylance will complain and we should repeat all parent overloads here..
        self, detailed_signal: str, handler: typing.Callable[..., typing.Any], *args: typing.Any
    ) -> int: ...

class EncodingVideoProfile(EncodingProfile):
    """
    Variant of GstEncodingProfile for video streams, allows specifying the `pass`.
    """

    # gi Methods
    def get_pass(self) -> int:
        """
        Get the pass number if this is part of a multi-pass profile.
        """
    def get_variableframerate(self) -> bool:
        """
            > *NOTE*: Fixed framerate won't be enforced when #encodebin:avoid-reencoding
        > is set.
        """
    def set_pass(self, pass_: int) -> None:
        """
            Sets the pass number of this video profile. The first pass profile should have
        this value set to 1. If this video profile isn't part of a multi-pass profile,
        you may set it to 0 (the default value).
        """
    def set_variableframerate(self, variableframerate: bool) -> None:
        """
            If set to True, then the incoming stream will be allowed to have non-constant
        framerate. If set to False (default value), then the incoming stream will
        be normalized by dropping/duplicating frames in order to produce a
        constance framerate.
        """

    # python methods (overrides?)
    def __init__(
        self,
        format: typing.Any,
        preset: typing.Any = None,
        restriction: typing.Any = None,
        presence: typing.Any = 0,
    ) -> None: ...
    @classmethod
    def new(
        cls,
        format: Gst.Caps,
        preset: str | None,
        restriction: Gst.Caps | None,
        presence: int,
    ) -> EncodingVideoProfile:
        """
        [is-override: Note this method is an override in Python of the original gi implementation.]

        new(format:Gst.Caps, preset:str=None, restriction:Gst.Caps=None, presence:int) -> GstPbutils.EncodingVideoProfile

        Creates a new GstEncodingVideoProfile

        All provided allocatable arguments will be internally copied, so can be
        safely freed/unreferenced after calling this method.

        If you wish to control the pass number (in case of multi-pass scenarios),
        please refer to the `gst_encoding_video_profile_set_pass` documentation.

        If you wish to use/force a constant framerate please refer to the
        `gst_encoding_video_profile_set_variableframerate` documentation.
        """

    # Signals
    @typing.overload
    def connect(
        self,
        detailed_signal: typing.Literal["notify"],
        handler: typing.Callable[[typing_extensions.Self, GObject.ParamSpec], None],
        *args: typing.Any,
    ) -> int: ...
    @typing.overload
    def connect(
        self,
        detailed_signal: typing.Literal["notify::element_properties"],
        handler: typing.Callable[[typing_extensions.Self, GObject.ParamSpec, typing.Any], None],
        *args: typing.Any,
    ) -> int: ...
    @typing.overload
    def connect(
        self,
        detailed_signal: typing.Literal["notify::restriction_caps"],
        handler: typing.Callable[[typing_extensions.Self, GObject.ParamSpec, typing.Any], None],
        *args: typing.Any,
    ) -> int: ...
    @typing.overload
    def connect(  # type: ignore otherwise pylance will complain and we should repeat all parent overloads here..
        self, detailed_signal: str, handler: typing.Callable[..., typing.Any], *args: typing.Any
    ) -> int: ...

class EncodingVideoProfileClass(GObject.GPointer, metaclass=GObject.GType): ...

class InstallPluginsContext(GObject.GBoxed, metaclass=GObject.GType):
    """
    Opaque context structure for the plugin installation. Use the provided
    API to set details on it.
    """

    # gi Methods
    def copy(self) -> InstallPluginsContext:
        """
        Copies a GstInstallPluginsContext.
        """
    def free(self) -> None:
        """
        Frees a GstInstallPluginsContext.
        """
    def set_confirm_search(self, confirm_search: bool) -> None:
        """
            This function is used to tell the external installer process whether it
        should ask for confirmation or not before searching for missing plugins.

        If set, this option will be passed to the installer via a
        --interaction=[show-confirm-search|hide-confirm-search] command line option.
        """
    def set_desktop_id(self, desktop_id: str) -> None:
        """
            This function is used to pass the calling application's desktop file ID to
        the external installer process.

        A desktop file ID is the basename of the desktop file, including the
        .desktop extension.

        If set, the desktop file ID will be passed to the installer via a
        --desktop-id= command line option.
        """
    def set_startup_notification_id(self, startup_id: str) -> None:
        """
            Sets the startup notification ID for the launched process.

        This is typically used to to pass the current X11 event timestamp to the
        external installer process.

        Startup notification IDs are defined in the
        [FreeDesktop.Org Startup Notifications standard](http://standards.freedesktop.org/startup-notification-spec/startup-notification-latest.txt).

        If set, the ID will be passed to the installer via a
        --startup-notification-id= command line option.

        GTK+/GNOME applications should be able to create a startup notification ID
        like this:
        |[
          timestamp = gtk_get_current_event_time ();
          startup_id = g_strdup_printf ("_TIME%u", timestamp);
        ...
        ]|
        """
    def set_xid(self, xid: int) -> None:
        """
            This function is for X11-based applications (such as most Gtk/Qt
        applications on linux/unix) only. You can use it to tell the external
        installer the XID of your main application window. That way the installer
        can make its own window transient to your application window during the
        installation.

        If set, the XID will be passed to the installer via a --transient-for=XID
        command line option.

        Gtk+/Gnome application should be able to obtain the XID of the top-level
        window like this:
        |[
        ##include <gtk/gtk.h>
        ##ifdef GDK_WINDOWING_X11
        ##include <gdk/gdkx.h>
        ##endif
        ...
        ##ifdef GDK_WINDOWING_X11
          xid = GDK_WINDOW_XWINDOW (GTK_WIDGET (application_window)->window);
        ##endif
        ...
        ]|
        """

    # python methods (overrides?)
    def __init__(
        self,
        *args: typing.Any,
        **kwargs: typing.Any,
    ) -> None: ...
    @classmethod
    def new(
        cls,
    ) -> InstallPluginsContext:
        """
        [is-override: Note this method is an override in Python of the original gi implementation.]

        new() -> GstPbutils.InstallPluginsContext

        Creates a new GstInstallPluginsContext.
        """

###############################################################
# Callbacks
###############################################################

class setupAudioVisualizerClassCB(typing.Protocol):
    """
    This callback was used in:
        AudioVisualizerClass.setup
    """
    #  scope
    def __call__(
        self,
        scope: AudioVisualizer,
    ) -> bool: ...

class renderAudioVisualizerClassCB(typing.Protocol):
    """
    This callback was used in:
        AudioVisualizerClass.render
    """
    #  scope
    def __call__(
        self,
        scope: AudioVisualizer,
        audio: Gst.Buffer,
        video: GstVideo.VideoFrame,
    ) -> bool: ...

class decide_allocationAudioVisualizerClassCB(typing.Protocol):
    """
    This callback was used in:
        AudioVisualizerClass.decide_allocation
    """
    #  scope
    def __call__(
        self,
        scope: AudioVisualizer,
        query: Gst.Query,
    ) -> bool: ...

class finishedDiscovererClassCB(typing.Protocol):
    """
    This callback was used in:
        DiscovererClass.finished
    """
    #  discoverer
    def __call__(
        self,
        discoverer: Discoverer,
    ) -> None: ...

class startingDiscovererClassCB(typing.Protocol):
    """
    This callback was used in:
        DiscovererClass.starting
    """
    #  discoverer
    def __call__(
        self,
        discoverer: Discoverer,
    ) -> None: ...

class discoveredDiscovererClassCB(typing.Protocol):
    """
    This callback was used in:
        DiscovererClass.discovered
    """
    #  discoverer
    def __call__(
        self,
        discoverer: Discoverer,
        info: DiscovererInfo,
        err: GLib.Error,
    ) -> None: ...

class source_setupDiscovererClassCB(typing.Protocol):
    """
    This callback was used in:
        DiscovererClass.source_setup
    """
    #  discoverer
    def __call__(
        self,
        discoverer: Discoverer,
        source: Gst.Element,
    ) -> None: ...

class load_serialize_infoDiscovererClassCB(typing.Protocol):
    """
    This callback was used in:
        DiscovererClass.load_serialize_info
    """
    #  dc
    def __call__(
        self,
        dc: Discoverer,
        uri: str,
    ) -> DiscovererInfo: ...

class InstallPluginsResultFunc(typing.Protocol):
    """
    This callback was used in:
        GstPbutils.install_plugins_async
    """
    #  result
    def __call__(
        self,
        result: InstallPluginsReturn,
        *user_data: object | None,
    ) -> None: ...

###############################################################
# Aliases
###############################################################

pb_utils_init = init
###############################################################
# Constants
###############################################################

ENCODING_CATEGORY_CAPTURE: str = ...
ENCODING_CATEGORY_DEVICE: str = ...
ENCODING_CATEGORY_FILE_EXTENSION: str = ...
ENCODING_CATEGORY_ONLINE_SERVICE: str = ...
ENCODING_CATEGORY_STORAGE_EDITING: str = ...
PLUGINS_BASE_VERSION_MAJOR: int = ...
PLUGINS_BASE_VERSION_MICRO: int = ...
PLUGINS_BASE_VERSION_MINOR: int = ...
PLUGINS_BASE_VERSION_NANO: int = ...
_namespace: str = ...
_version: str = ...
###############################################################
# Unknowns/Not Parsed
###############################################################

# type: lock, element not parsed are:
#     - _lock
# type: OverridesProxyModule, element not parsed are:
#     - _overrides_module
