# pyright: reportIncompatibleMethodOverride=false
"""
Stub template for a GI Repository Module.

Generated by gi-stub-gen, version 0.0.1.
Module: GstPlay
Date: 2026-07-02
"""
# we disable method override report for pyright in generated stubs,
# causes too many false positives

from __future__ import annotations
from typing_extensions import deprecated  # noqa: F401
import typing_extensions  # noqa: F401

import builtins
import enum
import typing

# gi.repository imports needed by this Stub
from gi.repository import GLib
from gi.repository import GObject
from gi.repository import Gst
from gi.repository import GstVideo
###############################################################
# Functions
###############################################################

def play_color_balance_type_get_name(
    type: PlayColorBalanceType,
) -> str:
    """
    Gets a string representing the given color balance type.
    """
    ...

def play_error_get_name(
    error: PlayError,
) -> str:
    """
    Gets a string representing the given error.
    """
    ...

def play_error_quark() -> int: ...
def play_loop_get_name(
    loop: PlayLoop,
) -> str: ...
def play_message_get_name(
    message_type: PlayMessage,
) -> str: ...
def play_message_get_stream_id(
    msg: Gst.Message,
) -> str | None:
    """
    Reads the stream ID the play message `msg` applies to, if any.
    """
    ...

def play_message_get_uri(
    msg: Gst.Message,
) -> str:
    """
    Reads the URI the play message `msg` applies to.
    """
    ...

def play_message_parse_buffering(
    msg: Gst.Message,
) -> int:
    """
    Parse the given buffering `msg` and extract the corresponding value
    """
    ...

@deprecated("deprecated")
def play_message_parse_buffering_percent(
    msg: Gst.Message,
) -> int:
    """
    Parse the given buffering `msg` and extract the corresponding value
    """
    ...

def play_message_parse_duration_changed(
    msg: Gst.Message,
) -> int:
    """
    Parse the given duration-changed `msg` and extract the corresponding GstClockTime
    """
    ...

@deprecated("deprecated")
def play_message_parse_duration_updated(
    msg: Gst.Message,
) -> int:
    """
    Parse the given duration-changed `msg` and extract the corresponding GstClockTime
    """
    ...

def play_message_parse_error(
    msg: Gst.Message,
) -> tuple[GLib.Error, Gst.Structure | None]:
    """
    Parse the given error `msg` and extract the corresponding GError.

    Since 1.26 the details will always contain the URI this refers to in an
    "uri" field of type string, and (if known) the string "stream-id" it is
    referring to.
    """
    ...

def play_message_parse_error_missing_plugin(
    msg: Gst.Message,
) -> tuple[bool, list[str], list[str]]:
    """
    Parses missing plugin descriptions and installer details from a
    GST_PLAY_ERROR_MISSING_PLUGIN error message.

    Both arrays will have the same length, and strings at the same index
    correspond to each other.

    The installer details can be passed to `gst_install_plugins_sync` or
    `gst_install_plugins_async`.
    """
    ...

def play_message_parse_media_info_updated(
    msg: Gst.Message,
) -> PlayMediaInfo:
    """
    Parse the given media-info-updated `msg` and extract the corresponding media information
    """
    ...

def play_message_parse_muted_changed(
    msg: Gst.Message,
) -> bool:
    """
    Parse the given mute-changed `msg` and extract the corresponding audio muted state
    """
    ...

def play_message_parse_position_updated(
    msg: Gst.Message,
) -> int:
    """
    Parse the given position-updated `msg` and extract the corresponding GstClockTime
    """
    ...

def play_message_parse_seek_done(
    msg: Gst.Message,
) -> int:
    """
    Parse the given seek-done `msg` and extract the corresponding GstClockTime
    """
    ...

def play_message_parse_state_changed(
    msg: Gst.Message,
) -> PlayState:
    """
    Parse the given state-changed `msg` and extract the corresponding GstPlay.State
    """
    ...

def play_message_parse_type(
    msg: Gst.Message,
) -> PlayMessage:
    """
    Parse the given `msg` and extract its GstPlay.Message type.
    """
    ...

def play_message_parse_uri_loaded(
    msg: Gst.Message,
) -> str:
    """
    Parse the given uri-loaded `msg` and extract the corresponding value
    """
    ...

def play_message_parse_video_dimensions_changed(
    msg: Gst.Message,
) -> tuple[int, int]:
    """
    Parse the given video-dimensions-changed `msg` and extract the corresponding video dimensions
    """
    ...

def play_message_parse_volume_changed(
    msg: Gst.Message,
) -> float:
    """
    Parse the given volume-changed `msg` and extract the corresponding audio volume
    """
    ...

def play_message_parse_warning(
    msg: Gst.Message,
) -> tuple[GLib.Error, Gst.Structure | None]:
    """
    Parse the given warning `msg` and extract the corresponding GError.

    Since 1.26 the details will always contain the URI this refers to in an
    "uri" field of type string, and (if known) the string "stream-id" it is
    referring to.
    """
    ...

def play_message_parse_warning_missing_plugin(
    msg: Gst.Message,
) -> tuple[bool, list[str], list[str]]:
    """
    Parses missing plugin descriptions and installer details from a
    GST_PLAY_ERROR_MISSING_PLUGIN warning message.

    Both arrays will have the same length, and strings at the same index
    correspond to each other.

    The installer details can be passed to `gst_install_plugins_sync` or
    `gst_install_plugins_async`.
    """
    ...

def play_state_get_name(
    state: PlayState,
) -> str:
    """
    Gets a string representing the given state.
    """
    ...

###############################################################
# Enums/Flags
###############################################################

class PlayColorBalanceType(GObject.GEnum, enum.IntEnum):
    HUE = 3
    """
    hue or color balance.
    """
    BRIGHTNESS = 0
    """
    brightness or black level.
    """
    SATURATION = 2
    """
    color saturation or chroma
    gain.
    """
    CONTRAST = 1
    """
    contrast or luma gain.
    """
    # gi Methods
    @staticmethod
    def get_name(type: PlayColorBalanceType) -> str: ...

class PlayError(GObject.GEnum, enum.IntEnum):
    FAILED = 0
    """
    generic error.
    """
    # gi Methods
    @staticmethod
    def get_name(error: PlayError) -> str: ...
    @staticmethod
    def quark() -> int: ...

class PlayLoop(GObject.GEnum, enum.IntEnum):
    NONE = 0
    """
    Don't loop.
    """
    TRACK = 1
    """
    Loop over the current track.
    """
    # gi Methods
    @staticmethod
    def get_name(loop: PlayLoop) -> str: ...

class PlayMessage(GObject.GEnum, enum.IntEnum):
    URI_LOADED = 0
    """
    Source element was initalized for set URI
    """
    POSITION_UPDATED = 1
    """
    Sink position changed
    """
    DURATION_CHANGED = 2
    """
    Duration of stream changed
    """
    STATE_CHANGED = 3
    """
    State changed, see GstPlay.State
    """
    BUFFERING = 4
    """
    Pipeline is in buffering state, message contains the percentage value of the decoding buffer
    """
    END_OF_STREAM = 5
    """
    Sink has received EOS
    """
    ERROR = 6
    """
    Message contains an error
    """
    WARNING = 7
    """
    Message contains an error
    """
    VIDEO_DIMENSIONS_CHANGED = 8
    """
    Video sink received format in different dimensions than before
    """
    MEDIA_INFO_UPDATED = 9
    """
    A media-info property has changed, message contains current GstPlay.MediaInfo
    """
    VOLUME_CHANGED = 10
    """
    The volume of the audio ouput has changed
    """
    MUTE_CHANGED = 11
    """
    Audio muting flag has been toggled
    """
    SEEK_DONE = 12
    """
    Any pending seeking operation has been completed
    """
    # gi Methods
    @staticmethod
    def get_name(message_type: PlayMessage) -> str: ...
    @staticmethod
    def get_stream_id(msg: Gst.Message) -> str | None: ...
    @staticmethod
    def get_uri(msg: Gst.Message) -> str: ...
    @staticmethod
    def parse_buffering(msg: Gst.Message) -> int: ...
    @deprecated("deprecated")
    @staticmethod
    def parse_buffering_percent(msg: Gst.Message) -> int: ...
    @staticmethod
    def parse_duration_changed(msg: Gst.Message) -> int: ...
    @deprecated("deprecated")
    @staticmethod
    def parse_duration_updated(msg: Gst.Message) -> int: ...
    @staticmethod
    def parse_error(msg: Gst.Message) -> tuple[GLib.Error, Gst.Structure | None]: ...
    @staticmethod
    def parse_error_missing_plugin(msg: Gst.Message) -> tuple[bool, list[str], list[str]]: ...
    @staticmethod
    def parse_media_info_updated(msg: Gst.Message) -> PlayMediaInfo: ...
    @staticmethod
    def parse_muted_changed(msg: Gst.Message) -> bool: ...
    @staticmethod
    def parse_position_updated(msg: Gst.Message) -> int: ...
    @staticmethod
    def parse_seek_done(msg: Gst.Message) -> int: ...
    @staticmethod
    def parse_state_changed(msg: Gst.Message) -> PlayState: ...
    @staticmethod
    def parse_type(msg: Gst.Message) -> PlayMessage: ...
    @staticmethod
    def parse_uri_loaded(msg: Gst.Message) -> str: ...
    @staticmethod
    def parse_video_dimensions_changed(msg: Gst.Message) -> tuple[int, int]: ...
    @staticmethod
    def parse_volume_changed(msg: Gst.Message) -> float: ...
    @staticmethod
    def parse_warning(msg: Gst.Message) -> tuple[GLib.Error, Gst.Structure | None]: ...
    @staticmethod
    def parse_warning_missing_plugin(msg: Gst.Message) -> tuple[bool, list[str], list[str]]: ...

class PlaySnapshotFormat(enum.IntEnum):
    RAW_NATIVE = 0
    """
    raw native format.
    """
    RAW_XRGB = 1
    """
    raw xRGB format.
    """
    RAW_BGRX = 2
    """
    raw BGRx format.
    """
    JPG = 3
    """
    jpeg format.
    """
    PNG = 4
    """
    png format.
    """

class PlayState(GObject.GEnum, enum.IntEnum):
    STOPPED = 0
    """
    the play is stopped.
    """
    BUFFERING = 1
    """
    the play is buffering.
    """
    PAUSED = 2
    """
    the play is paused.
    """
    PLAYING = 3
    """
    the play is currently playing a
    stream.
    """
    # gi Methods
    @staticmethod
    def get_name(state: PlayState) -> str: ...

###############################################################
# classes
###############################################################

class Play(Gst.Object):
    """
    The goal of the GstPlay library is to ease the integration of multimedia
    playback features in applications. Thus, if you need to build a media player
    from the ground-up, GstPlay provides the features you will most likely need.

    An example player is available in gst-examples/playback/player/gst-play/.

    Internally the GstPlay makes use of the `playbin3` element. The legacy
    `playbin2` can be selected if the `GST_PLAY_USE_PLAYBIN3=0` environment
    variable has been set.

    **Important note**: If your application relies on the GstBus to get
    notifications from GstPlay, you need to add some explicit clean-up code in
    order to prevent the GstPlay object from leaking. See below for the details.
    If you use the GstPlaySignalAdapter, no special clean-up is required.

    When the GstPlaySignalAdapter is not used, the GstBus owned by GstPlay should
    be set to flushing state before any attempt to drop the last reference of the
    GstPlay object. An example in C:

    ```c
    ...
    GstBus *bus = gst_play_get_message_bus (player);
    gst_bus_set_flushing (bus, True);
    gst_object_unref (bus);
    gst_object_unref (player);
    ```

    The messages managed by the player contain a reference to itself, and if the
    bus watch is just removed together with dropping the player then the bus will
    simply keep them around forever (and the bus never goes away because the
    player has a strong reference to it, so there's a reference cycle as long as
    there are messages). Setting the bus to flushing state forces it to get rid
    of its queued messages, thus breaking any possible reference cycle.
    """

    class Props(Gst.Object.Props):
        audio_video_offset: int  # [audio-video-offset]: changed because contained invalid characters
        current_audio_track: PlayAudioInfo | None  # [current-audio-track]: changed because contained invalid characters
        current_subtitle_track: (
            PlaySubtitleInfo | None
        )  # [current-subtitle-track]: changed because contained invalid characters
        current_video_track: PlayVideoInfo | None  # [current-video-track]: changed because contained invalid characters
        duration: int
        media_info: PlayMediaInfo | None  # [media-info]: changed because contained invalid characters
        mute: bool
        pipeline: Gst.Element | None
        position: int
        rate: float
        subtitle_video_offset: int  # [subtitle-video-offset]: changed because contained invalid characters
        suburi: str
        uri: str
        video_multiview_flags: (
            GstVideo.VideoMultiviewFlags
        )  # [video-multiview-flags]: changed because contained invalid characters
        video_multiview_mode: (
            GstVideo.VideoMultiviewFramePacking
        )  # [video-multiview-mode]: changed because contained invalid characters
        video_renderer: PlayVideoRenderer | None  # [video-renderer]: changed because contained invalid characters
        volume: float

    @builtins.property
    def props(self) -> Props: ...

    # gi Methods
    def __init__(
        self,
        audio_video_offset: int | None = None,
        mute: bool | None = None,
        name: str | None = None,
        parent: Gst.Object | None = None,
        rate: float | None = None,
        subtitle_video_offset: int | None = None,
        suburi: str | None = None,
        uri: str | None = None,
        video_multiview_flags: GstVideo.VideoMultiviewFlags | None = GstVideo.VideoMultiviewFlags.NONE,
        video_multiview_mode: GstVideo.VideoMultiviewFramePacking | None = GstVideo.VideoMultiviewFramePacking.NONE,
        video_renderer: PlayVideoRenderer | None = None,
        volume: float | None = None,
    ) -> None:
        """
        Initialize Play object with properties.
        """
    @staticmethod
    def config_get_loop(config: Gst.Structure) -> PlayLoop: ...
    @staticmethod
    def config_get_pipeline_dump_in_error_details(config: Gst.Structure) -> bool: ...
    @staticmethod
    def config_get_position_update_interval(config: Gst.Structure) -> int: ...
    @staticmethod
    def config_get_seek_accurate(config: Gst.Structure) -> bool: ...
    @staticmethod
    def config_get_user_agent(config: Gst.Structure) -> str | None:
        """
            Return the user agent which has been configured using
        `gst_play_config_set_user_agent` if any.
        """
    @staticmethod
    def config_set_loop(config: Gst.Structure, loop: PlayLoop) -> None:
        """
            Sets the looping mode.

        Looping is disabled by default.
        """
    @staticmethod
    def config_set_pipeline_dump_in_error_details(config: Gst.Structure, value: bool) -> None:
        """
            When enabled, the error message emitted by GstPlay. will include a pipeline
        dump (in Graphviz DOT format) in the error details GstStructure. The field
        name is `pipeline-dump`.

        This option is disabled by default.
        """
    @staticmethod
    def config_set_position_update_interval(config: Gst.Structure, interval: int) -> None:
        """
            Set desired interval in milliseconds between two position-updated messages.
        Pass 0 to stop updating the position.
        """
    @staticmethod
    def config_set_seek_accurate(config: Gst.Structure, accurate: bool) -> None:
        """
            Enable or disable accurate seeking. When enabled, elements will try harder
        to seek as accurately as possible to the requested seek position. Generally
        it will be slower especially for formats that don't have any indexes or
        timestamp markers in the stream.

        If accurate seeking is disabled, elements will seek as close as the request
        position without slowing down seeking too much.

        Accurate seeking is disabled by default.
        """
    @staticmethod
    def config_set_user_agent(config: Gst.Structure, agent: str | None = None) -> None:
        """
            Set the user agent to pass to the server if `play` needs to connect
        to a server during playback. This is typically used when playing HTTP
        or RTSP streams.
        """
    @staticmethod
    def get_audio_streams(info: PlayMediaInfo) -> list[PlayAudioInfo]: ...
    def get_audio_video_offset(self) -> int:
        """
        Retrieve the current value of audio-video-offset property
        """
    def get_color_balance(self, type: PlayColorBalanceType) -> float:
        """
        Retrieve the current value of the indicated `type`.
        """
    def get_config(self) -> Gst.Structure:
        """
            Get a copy of the current configuration of the play. This configuration
        can either be modified and used for the `gst_play_set_config` call
        or it must be freed after usage.
        """
    def get_current_audio_track(self) -> PlayAudioInfo | None:
        """
        A Function to get current audio GstPlay.AudioInfo instance.
        """
    def get_current_subtitle_track(self) -> PlaySubtitleInfo | None:
        """
        A Function to get current subtitle GstPlay.SubtitleInfo instance.
        """
    def get_current_video_track(self) -> PlayVideoInfo | None:
        """
        A Function to get current video GstPlay.VideoInfo instance.
        """
    def get_current_visualization(self) -> str | None: ...
    def get_duration(self) -> int:
        """
        Retrieves the duration of the media stream that self represents.
        """
    def get_media_info(self) -> PlayMediaInfo | None:
        """
        A Function to get the current media info GstPlay.MediaInfo instance.
        """
    def get_message_bus(self) -> Gst.Bus:
        """
            GstPlay API exposes a GstBus instance which purpose is to provide data
        structures representing play-internal events in form of GstMessage<!-- -->s of
        type GST_MESSAGE_APPLICATION.

        Each message carries a "play-message" field of type GstPlay.Message.
        Further fields of the message data are specific to each possible value of
        that enumeration.

        Applications can consume the messages asynchronously within their own
        event-loop / UI-thread etc. Note that in case the application does not
        consume the messages, the bus will accumulate these internally and eventually
        fill memory. To avoid that, the bus has to be set "flushing".
        """
    def get_multiview_flags(self) -> GstVideo.VideoMultiviewFlags:
        """
        Retrieve the current value of the indicated `type`.
        """
    def get_multiview_mode(self) -> GstVideo.VideoMultiviewFramePacking:
        """
        Retrieve the current value of the indicated `type`.
        """
    def get_mute(self) -> bool: ...
    def get_pipeline(self) -> Gst.Element: ...
    def get_position(self) -> int: ...
    def get_rate(self) -> float: ...
    @staticmethod
    def get_subtitle_streams(info: PlayMediaInfo) -> list[PlaySubtitleInfo]: ...
    def get_subtitle_uri(self) -> str | None:
        """
        Current subtitle URI
        """
    def get_subtitle_video_offset(self) -> int:
        """
        Retrieve the current value of subtitle-video-offset property
        """
    def get_uri(self) -> str | None:
        """
        Gets the URI of the currently-playing stream.
        """
    def get_video_snapshot(self, format: PlaySnapshotFormat, config: Gst.Structure | None = None) -> Gst.Sample | None:
        """
            Get a snapshot of the currently selected video stream, if any. The format can be
        selected with `format` and optional configuration is possible with `config`.
        Currently supported settings are:
        - width, height of type G_TYPE_INT
        - pixel-aspect-ratio of type GST_TYPE_FRACTION
         Except for GST_PLAY_THUMBNAIL_RAW_NATIVE format, if no config is set, pixel-aspect-ratio would be 1/1
        """
    @staticmethod
    def get_video_streams(info: PlayMediaInfo) -> list[PlayVideoInfo]: ...
    def get_volume(self) -> float:
        """
        Returns the current volume level, as a percentage between 0 and 1.
        """
    def has_color_balance(self) -> bool:
        """
        Checks whether the `play` has color balance support available.
        """
    @staticmethod
    def is_play_message(msg: Gst.Message) -> bool: ...
    def pause(self) -> None:
        """
        Pauses the current stream.
        """
    def play(self) -> None:
        """
        Request to play the loaded stream.
        """
    def seek(self, position: int) -> None:
        """
            Seeks the currently-playing stream to the absolute `position` time
        in nanoseconds.
        """
    @deprecated("deprecated")
    def set_audio_track(self, stream_index: int) -> bool: ...
    def set_audio_track_enabled(self, enabled: bool) -> None:
        """
        Enable or disable the current audio track.
        """
    def set_audio_track_id(self, stream_id: str | None = None) -> bool: ...
    def set_audio_video_offset(self, offset: int) -> None:
        """
        Sets audio-video-offset property by value of `offset`
        """
    def set_color_balance(self, type: PlayColorBalanceType, value: float) -> None:
        """
            Sets the current value of the indicated channel `type` to the passed
        value.
        """
    def set_config(self, config: Gst.Structure) -> bool:
        """
            Set the configuration of the play. If the play is already configured, and
        the configuration hasn't changed, this function will return True. If the
        play is not in the GST_PLAY_STATE_STOPPED, this method will return False
        and active configuration will remain.

        `config` is a GstStructure that contains the configuration parameters for
        the play.

        This function takes ownership of `config`.
        """
    def set_multiview_flags(self, flags: GstVideo.VideoMultiviewFlags) -> None:
        """
            Sets the current value of the indicated mode `type` to the passed
        value.
        """
    def set_multiview_mode(self, mode: GstVideo.VideoMultiviewFramePacking) -> None:
        """
            Sets the current value of the indicated mode `type` to the passed
        value.
        """
    def set_mute(self, val: bool) -> None:
        """
        True if the currently-playing stream should be muted.
        """
    def set_rate(self, rate: float) -> None:
        """
        Playback at specified rate
        """
    @deprecated("deprecated")
    def set_subtitle_track(self, stream_index: int) -> bool: ...
    def set_subtitle_track_enabled(self, enabled: bool) -> None:
        """
        Enable or disable the current subtitle track.
        """
    def set_subtitle_track_id(self, stream_id: str | None = None) -> bool: ...
    def set_subtitle_uri(self, uri: str | None = None) -> None:
        """
            Sets the external subtitle URI. This should be combined with a call to
        gst_play_set_subtitle_track_enabled(`play`, True) so the subtitles are actually
        rendered.
        """
    def set_subtitle_video_offset(self, offset: int) -> None:
        """
        Sets subtitle-video-offset property by value of `offset`
        """
    def set_track_ids(
        self,
        audio_stream_id: str | None = None,
        video_stream_id: str | None = None,
        subtitle_stream_id: str | None = None,
    ) -> bool: ...
    def set_uri(self, uri: str | None = None) -> None:
        """
        Sets the next URI to play.
        """
    @deprecated("deprecated")
    def set_video_track(self, stream_index: int) -> bool: ...
    def set_video_track_enabled(self, enabled: bool) -> None:
        """
        Enable or disable the current video track.
        """
    def set_video_track_id(self, stream_id: str | None = None) -> bool: ...
    def set_visualization(self, name: str | None = None) -> bool: ...
    def set_visualization_enabled(self, enabled: bool) -> None:
        """
        Enable or disable the visualization.
        """
    def set_volume(self, val: float) -> None:
        """
        Sets the volume level of the stream as a percentage between 0 and 1.
        """
    def stop(self) -> None:
        """
            Stops playing the current stream and resets to the first position
        in the stream.
        """
    @staticmethod
    def visualizations_free(viss: PlayVisualization) -> None:
        """
        Frees a None terminated array of GstPlay.Visualization.
        """
    @staticmethod
    def visualizations_get() -> list[PlayVisualization]: ...

    # python methods (overrides?)
    @classmethod
    def new(
        cls,
        video_renderer: PlayVideoRenderer | None = None,
    ) -> Play:
        """
        [is-override: Note this method is an override in Python of the original gi implementation.]

        new(video_renderer:GstPlay.PlayVideoRenderer=None) -> GstPlay.Play

        Creates a new GstPlay. instance.

        Video is going to be rendered by `video_renderer`, or if None is provided
        no special video set up will be done and some default handling will be
        performed.

        This also initializes GStreamer via ``gst_init`` on the first call if this
        didn't happen before.
        """

    # Signals
    @typing.overload
    def connect(
        self,
        detailed_signal: typing.Literal["deep-notify"],
        handler: typing.Callable[[typing_extensions.Self, Gst.Object, GObject.ParamSpec], None],
        *args: typing.Any,
    ) -> int: ...
    @typing.overload
    def connect(
        self,
        detailed_signal: typing.Literal["notify"],
        handler: typing.Callable[[typing_extensions.Self, GObject.ParamSpec], None],
        *args: typing.Any,
    ) -> int: ...
    @typing.overload
    def connect(
        self,
        detailed_signal: typing.Literal["notify::audio_video_offset"],
        handler: typing.Callable[[typing_extensions.Self, GObject.ParamSpec, typing.Any], None],
        *args: typing.Any,
    ) -> int: ...
    @typing.overload
    def connect(
        self,
        detailed_signal: typing.Literal["notify::current_audio_track"],
        handler: typing.Callable[[typing_extensions.Self, GObject.ParamSpec, typing.Any], None],
        *args: typing.Any,
    ) -> int: ...
    @typing.overload
    def connect(
        self,
        detailed_signal: typing.Literal["notify::current_subtitle_track"],
        handler: typing.Callable[[typing_extensions.Self, GObject.ParamSpec, typing.Any], None],
        *args: typing.Any,
    ) -> int: ...
    @typing.overload
    def connect(
        self,
        detailed_signal: typing.Literal["notify::current_video_track"],
        handler: typing.Callable[[typing_extensions.Self, GObject.ParamSpec, typing.Any], None],
        *args: typing.Any,
    ) -> int: ...
    @typing.overload
    def connect(
        self,
        detailed_signal: typing.Literal["notify::duration"],
        handler: typing.Callable[[typing_extensions.Self, GObject.ParamSpec, typing.Any], None],
        *args: typing.Any,
    ) -> int: ...
    @typing.overload
    def connect(
        self,
        detailed_signal: typing.Literal["notify::media_info"],
        handler: typing.Callable[[typing_extensions.Self, GObject.ParamSpec, typing.Any], None],
        *args: typing.Any,
    ) -> int: ...
    @typing.overload
    def connect(
        self,
        detailed_signal: typing.Literal["notify::mute"],
        handler: typing.Callable[[typing_extensions.Self, GObject.ParamSpec, typing.Any], None],
        *args: typing.Any,
    ) -> int: ...
    @typing.overload
    def connect(
        self,
        detailed_signal: typing.Literal["notify::pipeline"],
        handler: typing.Callable[[typing_extensions.Self, GObject.ParamSpec, typing.Any], None],
        *args: typing.Any,
    ) -> int: ...
    @typing.overload
    def connect(
        self,
        detailed_signal: typing.Literal["notify::position"],
        handler: typing.Callable[[typing_extensions.Self, GObject.ParamSpec, typing.Any], None],
        *args: typing.Any,
    ) -> int: ...
    @typing.overload
    def connect(
        self,
        detailed_signal: typing.Literal["notify::rate"],
        handler: typing.Callable[[typing_extensions.Self, GObject.ParamSpec, typing.Any], None],
        *args: typing.Any,
    ) -> int: ...
    @typing.overload
    def connect(
        self,
        detailed_signal: typing.Literal["notify::subtitle_video_offset"],
        handler: typing.Callable[[typing_extensions.Self, GObject.ParamSpec, typing.Any], None],
        *args: typing.Any,
    ) -> int: ...
    @typing.overload
    def connect(
        self,
        detailed_signal: typing.Literal["notify::suburi"],
        handler: typing.Callable[[typing_extensions.Self, GObject.ParamSpec, typing.Any], None],
        *args: typing.Any,
    ) -> int: ...
    @typing.overload
    def connect(
        self,
        detailed_signal: typing.Literal["notify::uri"],
        handler: typing.Callable[[typing_extensions.Self, GObject.ParamSpec, typing.Any], None],
        *args: typing.Any,
    ) -> int: ...
    @typing.overload
    def connect(
        self,
        detailed_signal: typing.Literal["notify::video_multiview_flags"],
        handler: typing.Callable[[typing_extensions.Self, GObject.ParamSpec, typing.Any], None],
        *args: typing.Any,
    ) -> int: ...
    @typing.overload
    def connect(
        self,
        detailed_signal: typing.Literal["notify::video_multiview_mode"],
        handler: typing.Callable[[typing_extensions.Self, GObject.ParamSpec, typing.Any], None],
        *args: typing.Any,
    ) -> int: ...
    @typing.overload
    def connect(
        self,
        detailed_signal: typing.Literal["notify::video_renderer"],
        handler: typing.Callable[[typing_extensions.Self, GObject.ParamSpec, typing.Any], None],
        *args: typing.Any,
    ) -> int: ...
    @typing.overload
    def connect(
        self,
        detailed_signal: typing.Literal["notify::volume"],
        handler: typing.Callable[[typing_extensions.Self, GObject.ParamSpec, typing.Any], None],
        *args: typing.Any,
    ) -> int: ...
    @typing.overload
    def connect(
        self,
        detailed_signal: typing.Literal["notify::name"],
        handler: typing.Callable[[typing_extensions.Self, GObject.ParamSpec, typing.Any], None],
        *args: typing.Any,
    ) -> int: ...
    @typing.overload
    def connect(
        self,
        detailed_signal: typing.Literal["notify::parent"],
        handler: typing.Callable[[typing_extensions.Self, GObject.ParamSpec, typing.Any], None],
        *args: typing.Any,
    ) -> int: ...
    @typing.overload
    def connect(  # type: ignore otherwise pylance will complain and we should repeat all parent overloads here..
        self, detailed_signal: str, handler: typing.Callable[..., typing.Any], *args: typing.Any
    ) -> int: ...

class PlayAudioInfo(PlayStreamInfo):
    """
    GstPlay.StreamInfo specific to audio streams.
    """

    # gi Methods
    def __init__(self) -> None:
        """
        Initialize PlayAudioInfo object with properties.
        """
    def get_bitrate(self) -> int: ...
    def get_channels(self) -> int: ...
    def get_language(self) -> str | None: ...
    def get_max_bitrate(self) -> int: ...
    def get_sample_rate(self) -> int: ...

    # Signals
    @typing.overload
    def connect(
        self,
        detailed_signal: typing.Literal["notify"],
        handler: typing.Callable[[typing_extensions.Self, GObject.ParamSpec], None],
        *args: typing.Any,
    ) -> int: ...
    @typing.overload
    def connect(  # type: ignore otherwise pylance will complain and we should repeat all parent overloads here..
        self, detailed_signal: str, handler: typing.Callable[..., typing.Any], *args: typing.Any
    ) -> int: ...

class PlayAudioInfoClass(GObject.GPointer, metaclass=GObject.GType): ...
class PlayClass(GObject.GPointer, metaclass=GObject.GType): ...

class PlayMediaInfo(GObject.Object):
    """
    Structure containing the media information of a URI.
    """

    # gi Methods
    def __init__(self) -> None:
        """
        Initialize PlayMediaInfo object with properties.
        """
    def get_audio_streams(self) -> list[PlayAudioInfo]: ...
    def get_container_format(self) -> str | None: ...
    def get_duration(self) -> int: ...
    def get_image_sample(self) -> Gst.Sample | None:
        """
            Function to get the image (or preview-image) stored in taglist.
        Application can use `gst_sample_*`_`` API's to get caps, buffer etc.
        """
    def get_number_of_audio_streams(self) -> int: ...
    def get_number_of_streams(self) -> int: ...
    def get_number_of_subtitle_streams(self) -> int: ...
    def get_number_of_video_streams(self) -> int: ...
    def get_stream_list(self) -> list[PlayStreamInfo]: ...
    def get_subtitle_streams(self) -> list[PlaySubtitleInfo]: ...
    def get_tags(self) -> Gst.TagList | None: ...
    def get_title(self) -> str | None: ...
    def get_uri(self) -> str: ...
    def get_video_streams(self) -> list[PlayVideoInfo]: ...
    def is_live(self) -> bool: ...
    def is_seekable(self) -> bool: ...

    # Signals
    @typing.overload
    def connect(
        self,
        detailed_signal: typing.Literal["notify"],
        handler: typing.Callable[[typing_extensions.Self, GObject.ParamSpec], None],
        *args: typing.Any,
    ) -> int: ...
    @typing.overload
    def connect(  # type: ignore otherwise pylance will complain and we should repeat all parent overloads here..
        self, detailed_signal: str, handler: typing.Callable[..., typing.Any], *args: typing.Any
    ) -> int: ...

class PlayMediaInfoClass(GObject.GPointer, metaclass=GObject.GType): ...

class PlaySignalAdapter(GObject.Object):
    class Props(GObject.Object.Props):
        play: Play | None

    @builtins.property
    def props(self) -> Props: ...

    # gi Methods
    def __init__(self) -> None:
        """
        Initialize PlaySignalAdapter object with properties.
        """
    def get_play(self) -> Play: ...

    # python methods (overrides?)
    @classmethod
    def new(
        cls,
        play: Play,
    ) -> PlaySignalAdapter:
        """
        [is-override: Note this method is an override in Python of the original gi implementation.]

        new(play:GstPlay.Play) -> GstPlay.PlaySignalAdapter

        A bus-watching GSource will be created and attached to the the
        thread-default GMainContext. The attached callback will emit the
        corresponding signal for the message received. Matching signals for play
        messages from the bus will be emitted by it on the created adapter object.
        """
    @classmethod
    def new_sync_emit(
        cls,
        play: Play,
    ) -> PlaySignalAdapter:
        """
        [is-override: Note this method is an override in Python of the original gi implementation.]

        new_sync_emit(play:GstPlay.Play) -> GstPlay.PlaySignalAdapter

        Create an adapter that synchronously emits its signals, from the thread in
        which the messages have been posted.
        """
    @classmethod
    def new_with_main_context(
        cls,
        play: Play,
        context: GLib.MainContext,
    ) -> PlaySignalAdapter:
        """
        [is-override: Note this method is an override in Python of the original gi implementation.]

        new_with_main_context(play:GstPlay.Play, context:GLib.MainContext) -> GstPlay.PlaySignalAdapter

        A bus-watching GSource will be created and attached to the `context`. The
        attached callback will emit the corresponding signal for the message
        received. Matching signals for play messages from the bus will be emitted by
        it on the created adapter object.
        """

    # Signals
    @typing.overload
    def connect(
        self,
        detailed_signal: typing.Literal["buffering"],
        handler: typing.Callable[[typing_extensions.Self, int], None],
        *args: typing.Any,
    ) -> int: ...
    @typing.overload
    def connect(
        self,
        detailed_signal: typing.Literal["duration-changed"],
        handler: typing.Callable[[typing_extensions.Self, int], None],
        *args: typing.Any,
    ) -> int: ...
    @typing.overload
    def connect(
        self, detailed_signal: typing.Literal["end-of-stream"], handler: typing.Callable[..., None], *args: typing.Any
    ) -> int: ...
    @typing.overload
    def connect(
        self,
        detailed_signal: typing.Literal["error"],
        handler: typing.Callable[[typing_extensions.Self, GLib.Error, Gst.Structure | None], None],
        *args: typing.Any,
    ) -> int:
        """
        Emitted on errors.
        """
    @typing.overload
    def connect(
        self,
        detailed_signal: typing.Literal["media-info-updated"],
        handler: typing.Callable[[typing_extensions.Self, PlayMediaInfo], None],
        *args: typing.Any,
    ) -> int: ...
    @typing.overload
    def connect(
        self,
        detailed_signal: typing.Literal["mute-changed"],
        handler: typing.Callable[[typing_extensions.Self, bool], None],
        *args: typing.Any,
    ) -> int: ...
    @typing.overload
    def connect(
        self,
        detailed_signal: typing.Literal["position-updated"],
        handler: typing.Callable[[typing_extensions.Self, int], None],
        *args: typing.Any,
    ) -> int: ...
    @typing.overload
    def connect(
        self,
        detailed_signal: typing.Literal["seek-done"],
        handler: typing.Callable[[typing_extensions.Self, int], None],
        *args: typing.Any,
    ) -> int: ...
    @typing.overload
    def connect(
        self,
        detailed_signal: typing.Literal["state-changed"],
        handler: typing.Callable[[typing_extensions.Self, PlayState], None],
        *args: typing.Any,
    ) -> int: ...
    @typing.overload
    def connect(
        self,
        detailed_signal: typing.Literal["uri-loaded"],
        handler: typing.Callable[[typing_extensions.Self, str], None],
        *args: typing.Any,
    ) -> int: ...
    @typing.overload
    def connect(
        self,
        detailed_signal: typing.Literal["video-dimensions-changed"],
        handler: typing.Callable[[typing_extensions.Self, int, int], None],
        *args: typing.Any,
    ) -> int: ...
    @typing.overload
    def connect(
        self,
        detailed_signal: typing.Literal["volume-changed"],
        handler: typing.Callable[[typing_extensions.Self, float], None],
        *args: typing.Any,
    ) -> int: ...
    @typing.overload
    def connect(
        self,
        detailed_signal: typing.Literal["warning"],
        handler: typing.Callable[[typing_extensions.Self, GLib.Error, Gst.Structure | None], None],
        *args: typing.Any,
    ) -> int:
        """
        Emitted on warnings.
        """
    @typing.overload
    def connect(
        self,
        detailed_signal: typing.Literal["notify"],
        handler: typing.Callable[[typing_extensions.Self, GObject.ParamSpec], None],
        *args: typing.Any,
    ) -> int: ...
    @typing.overload
    def connect(
        self,
        detailed_signal: typing.Literal["notify::play"],
        handler: typing.Callable[[typing_extensions.Self, GObject.ParamSpec, typing.Any], None],
        *args: typing.Any,
    ) -> int: ...
    @typing.overload
    def connect(  # type: ignore otherwise pylance will complain and we should repeat all parent overloads here..
        self, detailed_signal: str, handler: typing.Callable[..., typing.Any], *args: typing.Any
    ) -> int: ...

class PlaySignalAdapterClass(GObject.GPointer, metaclass=GObject.GType): ...

class PlayStreamInfo(GObject.Object):
    """
    Base structure for information concerning a media stream. Depending on
    the stream type, one can find more media-specific information in
    GstPlay.VideoInfo, GstPlay.AudioInfo, GstPlay.SubtitleInfo.
    """

    # gi Methods
    def __init__(self) -> None:
        """
        Initialize PlayStreamInfo object with properties.
        """
    def get_caps(self) -> Gst.Caps | None: ...
    def get_codec(self) -> str | None:
        """
        A string describing codec used in GstPlay.StreamInfo.
        """
    @deprecated("deprecated")
    def get_index(self) -> int:
        """
            Function to get stream index from GstPlay.StreamInfo instance or -1 if
        unknown.
        """
    def get_stream_id(self) -> str:
        """
        A string stream id identifying this GstPlay.StreamInfo.
        """
    def get_stream_type(self) -> str:
        """
            Function to return human readable name for the stream type
        of the given `info` (ex: "audio", "video", "subtitle")
        """
    def get_tags(self) -> Gst.TagList | None: ...

    # Signals
    @typing.overload
    def connect(
        self,
        detailed_signal: typing.Literal["notify"],
        handler: typing.Callable[[typing_extensions.Self, GObject.ParamSpec], None],
        *args: typing.Any,
    ) -> int: ...
    @typing.overload
    def connect(  # type: ignore otherwise pylance will complain and we should repeat all parent overloads here..
        self, detailed_signal: str, handler: typing.Callable[..., typing.Any], *args: typing.Any
    ) -> int: ...

class PlayStreamInfoClass(GObject.GPointer, metaclass=GObject.GType): ...

class PlaySubtitleInfo(PlayStreamInfo):
    """
    GstPlay.StreamInfo specific to subtitle streams.
    """

    # gi Methods
    def __init__(self) -> None:
        """
        Initialize PlaySubtitleInfo object with properties.
        """
    def get_language(self) -> str | None: ...

    # Signals
    @typing.overload
    def connect(
        self,
        detailed_signal: typing.Literal["notify"],
        handler: typing.Callable[[typing_extensions.Self, GObject.ParamSpec], None],
        *args: typing.Any,
    ) -> int: ...
    @typing.overload
    def connect(  # type: ignore otherwise pylance will complain and we should repeat all parent overloads here..
        self, detailed_signal: str, handler: typing.Callable[..., typing.Any], *args: typing.Any
    ) -> int: ...

class PlaySubtitleInfoClass(GObject.GPointer, metaclass=GObject.GType): ...

class PlayVideoInfo(PlayStreamInfo):
    """
    GstPlay.StreamInfo specific to video streams.
    """

    # gi Methods
    def __init__(self) -> None:
        """
        Initialize PlayVideoInfo object with properties.
        """
    def get_bitrate(self) -> int: ...
    def get_framerate(self) -> tuple[int, int]: ...
    def get_height(self) -> int: ...
    def get_max_bitrate(self) -> int: ...
    def get_pixel_aspect_ratio(self) -> tuple[int, int]:
        """
        Returns the pixel aspect ratio in `par_n` and `par_d`
        """
    def get_width(self) -> int: ...

    # Signals
    @typing.overload
    def connect(
        self,
        detailed_signal: typing.Literal["notify"],
        handler: typing.Callable[[typing_extensions.Self, GObject.ParamSpec], None],
        *args: typing.Any,
    ) -> int: ...
    @typing.overload
    def connect(  # type: ignore otherwise pylance will complain and we should repeat all parent overloads here..
        self, detailed_signal: str, handler: typing.Callable[..., typing.Any], *args: typing.Any
    ) -> int: ...

class PlayVideoInfoClass(GObject.GPointer, metaclass=GObject.GType): ...

class PlayVideoOverlayVideoRenderer(GObject.Object):
    class Props(GObject.Object.Props):
        video_sink: Gst.Element | None  # [video-sink]: changed because contained invalid characters
        window_handle: object | None  # [window-handle]: changed because contained invalid characters

    @builtins.property
    def props(self) -> Props: ...

    # gi Methods
    def __init__(self, video_sink: Gst.Element | None = None, window_handle: object | None = None) -> None:
        """
        Initialize PlayVideoOverlayVideoRenderer object with properties.
        """
    def expose(self) -> None:
        """
            Tell an overlay that it has been exposed. This will redraw the current frame
        in the drawable even if the pipeline is PAUSED.
        """
    def get_render_rectangle(self) -> tuple[int, int, int, int]:
        """
            Return the currently configured render rectangle. See `gst_play_video_overlay_video_renderer_set_render_rectangle`
        for details.
        """
    def get_window_handle(self) -> object | None: ...
    @staticmethod
    def new(window_handle: object | None = None) -> PlayVideoRenderer: ...
    @staticmethod
    def new_with_sink(window_handle: object | None, video_sink: Gst.Element) -> PlayVideoRenderer: ...
    def set_render_rectangle(self, x: int, y: int, width: int, height: int) -> None:
        """
            Configure a subregion as a video target within the window set by
        `gst_play_video_overlay_video_renderer_set_window_handle`. If this is not
        used or not supported the video will fill the area of the window set as the
        overlay to 100%. By specifying the rectangle, the video can be overlaid to
        a specific region of that window only. After setting the new rectangle one
        should call `gst_play_video_overlay_video_renderer_expose` to force a
        redraw. To unset the region pass -1 for the `width` and `height` parameters.

        This method is needed for non fullscreen video overlay in UI toolkits that
        do not support subwindows.
        """
    def set_window_handle(self, window_handle: object | None = None) -> None:
        """
            Sets the platform specific window handle into which the video
        should be rendered
        """

    # Signals
    @typing.overload
    def connect(
        self,
        detailed_signal: typing.Literal["notify"],
        handler: typing.Callable[[typing_extensions.Self, GObject.ParamSpec], None],
        *args: typing.Any,
    ) -> int: ...
    @typing.overload
    def connect(
        self,
        detailed_signal: typing.Literal["notify::video_sink"],
        handler: typing.Callable[[typing_extensions.Self, GObject.ParamSpec, typing.Any], None],
        *args: typing.Any,
    ) -> int: ...
    @typing.overload
    def connect(
        self,
        detailed_signal: typing.Literal["notify::window_handle"],
        handler: typing.Callable[[typing_extensions.Self, GObject.ParamSpec, typing.Any], None],
        *args: typing.Any,
    ) -> int: ...
    @typing.overload
    def connect(  # type: ignore otherwise pylance will complain and we should repeat all parent overloads here..
        self, detailed_signal: str, handler: typing.Callable[..., typing.Any], *args: typing.Any
    ) -> int: ...

class PlayVideoOverlayVideoRendererClass(GObject.GPointer, metaclass=GObject.GType): ...

class PlayVideoRenderer(builtins.object):
    class Props: ...

    @builtins.property
    def props(self) -> Props: ...

    # gi Methods
    def __init__(self) -> None:
        """
        Initialize PlayVideoRenderer object with properties.
        """

class PlayVideoRendererInterface(GObject.GPointer, metaclass=GObject.GType):
    # gi Fields
    @builtins.property
    def create_video_sink(self) -> object | None: ...
    @builtins.property
    def parent_iface(self) -> GObject.TypeInterface | None: ...

class PlayVisualization(GObject.GBoxed, metaclass=GObject.GType):
    """
    A GstPlay.Visualization descriptor.
    """

    # gi Fields
    description: str = ...
    """
    description of the visualization.
    """
    name: str = ...
    """
    name of the visualization.
    """

    # gi Methods
    def copy(self) -> PlayVisualization:
        """
            Makes a copy of the GstPlay.Visualization. The result must be
        freed using `gst_play_visualization_free`.
        """
    def free(self) -> None:
        """
        Frees a GstPlay.Visualization.
        """

###############################################################
# Constants
###############################################################

_namespace: str = ...
_version: str = ...
###############################################################
# Unknowns/Not Parsed
###############################################################

# type: lock, element not parsed are:
#     - _lock
