# pyright: reportIncompatibleMethodOverride=false
# pyright: reportIncompatibleVariableOverride=false
"""
Stub template for a GI Repository Module.

Generated by gi-stub-gen, version 0.0.1.
Module: GstRtsp
Date: 2025-12-24
"""
# we disable override report for pyright in generated stubs,
# causes too many false positives

from __future__ import annotations
from typing_extensions import deprecated  # noqa: F401
import typing_extensions  # noqa: F401
import typing  # noqa: F401
import gi  # noqa: F401

import _thread

# gi.repository imports needed by this Stub
from gi.repository import GObject
from gi.repository import Gio
from gi.repository import GLib
from gi.repository import GstSdp
from gi.repository import Gst
###############################################################
# Functions
###############################################################

def rtsp_auth_credentials_free(
    credentials: RTSPAuthCredential,
) -> None: ...
def rtsp_connection_accept(
    socket: Gio.Socket,
    cancellable: Gio.Cancellable | None = None,
) -> tuple[RTSPResult, RTSPConnection | None]: ...
def rtsp_connection_create(
    url: RTSPUrl,
) -> tuple[RTSPResult, RTSPConnection]: ...
def rtsp_connection_create_from_socket(
    socket: Gio.Socket,
    ip: str,
    port: int,
    initial_buffer: str,
) -> tuple[RTSPResult, RTSPConnection | None]: ...
def rtsp_find_header_field(
    header: str,
) -> RTSPHeaderField: ...
def rtsp_find_method(
    method: str,
) -> RTSPMethod: ...
def rtsp_generate_digest_auth_response(
    algorithm: str | None,
    method: str,
    realm: str,
    username: str,
    password: str,
    uri: str,
    nonce: str,
) -> str | None: ...
def rtsp_generate_digest_auth_response_from_md5(
    algorithm: str | None,
    method: str,
    md5: str,
    uri: str,
    nonce: str,
) -> str | None: ...
def rtsp_header_allow_multiple(
    field: RTSPHeaderField,
) -> bool: ...
def rtsp_header_as_text(
    field: RTSPHeaderField,
) -> str | None: ...
def rtsp_message_new() -> tuple[RTSPResult, RTSPMessage]: ...
def rtsp_message_new_data(
    channel: int,
) -> tuple[RTSPResult, RTSPMessage]: ...
def rtsp_message_new_request(
    method: RTSPMethod,
    uri: str,
) -> tuple[RTSPResult, RTSPMessage]: ...
def rtsp_message_new_response(
    code: RTSPStatusCode,
    reason: str | None = None,
    request: RTSPMessage | None = None,
) -> tuple[RTSPResult, RTSPMessage]: ...
def rtsp_method_as_text(
    method: RTSPMethod,
) -> str | None: ...
def rtsp_options_as_text(
    options: RTSPMethod,
) -> str: ...
def rtsp_options_from_text(
    options: str,
) -> RTSPMethod: ...
def rtsp_range_convert_units(
    range: RTSPTimeRange,
    unit: RTSPRangeUnit,
) -> bool: ...
def rtsp_range_free(
    range: RTSPTimeRange,
) -> None: ...
def rtsp_range_get_times(
    range: RTSPTimeRange,
) -> tuple[bool, int, int]: ...
def rtsp_range_parse(
    rangestr: str,
) -> tuple[RTSPResult, RTSPTimeRange]: ...
def rtsp_range_to_string(
    range: RTSPTimeRange,
) -> str: ...
def rtsp_status_as_text(
    code: RTSPStatusCode,
) -> str: ...
def rtsp_strresult(
    result: RTSPResult,
) -> str: ...
def rtsp_transport_get_manager(
    trans: RTSPTransMode,
    option: int,
) -> tuple[RTSPResult, str | None]: ...
def rtsp_transport_get_mime(
    trans: RTSPTransMode,
) -> tuple[RTSPResult, str]: ...
def rtsp_transport_init() -> tuple[RTSPResult, RTSPTransport]: ...
def rtsp_transport_new() -> tuple[RTSPResult, RTSPTransport]: ...
def rtsp_transport_parse(
    str: str,
) -> tuple[RTSPResult, RTSPTransport]: ...
def rtsp_url_parse(
    urlstr: str,
) -> tuple[RTSPResult, RTSPUrl | None]: ...
def rtsp_version_as_text(
    version: RTSPVersion,
) -> str: ...

###############################################################
# Enums/Flags
###############################################################

class RTSPAuthMethod(GObject.GEnum):
    NONE = 0
    BASIC = 1
    DIGEST = 2

class RTSPEvent(GObject.GFlags):
    READ = 1
    WRITE = 2

class RTSPFamily(GObject.GEnum):
    NONE = 0
    INET = 1
    INET6 = 2

class RTSPHeaderField(GObject.GEnum):
    INVALID = 0
    ACCEPT = 1
    ACCEPT_ENCODING = 2
    ACCEPT_LANGUAGE = 3
    ALLOW = 4
    AUTHORIZATION = 5
    BANDWIDTH = 6
    BLOCKSIZE = 7
    CACHE_CONTROL = 8
    CONFERENCE = 9
    CONNECTION = 10
    CONTENT_BASE = 11
    CONTENT_ENCODING = 12
    CONTENT_LANGUAGE = 13
    CONTENT_LENGTH = 14
    CONTENT_LOCATION = 15
    CONTENT_TYPE = 16
    CSEQ = 17
    DATE = 18
    EXPIRES = 19
    FROM = 20
    IF_MODIFIED_SINCE = 21
    LAST_MODIFIED = 22
    PROXY_AUTHENTICATE = 23
    PROXY_REQUIRE = 24
    PUBLIC = 25
    RANGE = 26
    REFERER = 27
    REQUIRE = 28
    RETRY_AFTER = 29
    RTP_INFO = 30
    SCALE = 31
    SESSION = 32
    SERVER = 33
    SPEED = 34
    TRANSPORT = 35
    UNSUPPORTED = 36
    USER_AGENT = 37
    VIA = 38
    WWW_AUTHENTICATE = 39
    CLIENT_CHALLENGE = 40
    REAL_CHALLENGE1 = 41
    REAL_CHALLENGE2 = 42
    REAL_CHALLENGE3 = 43
    SUBSCRIBE = 44
    ALERT = 45
    CLIENT_ID = 46
    COMPANY_ID = 47
    GUID = 48
    REGION_DATA = 49
    MAX_ASM_WIDTH = 50
    LANGUAGE = 51
    PLAYER_START_TIME = 52
    LOCATION = 53
    ETAG = 54
    IF_MATCH = 55
    ACCEPT_CHARSET = 56
    SUPPORTED = 57
    VARY = 58
    X_ACCELERATE_STREAMING = 59
    X_ACCEPT_AUTHENT = 60
    X_ACCEPT_PROXY_AUTHENT = 61
    X_BROADCAST_ID = 62
    X_BURST_STREAMING = 63
    X_NOTICE = 64
    X_PLAYER_LAG_TIME = 65
    X_PLAYLIST = 66
    X_PLAYLIST_CHANGE_NOTICE = 67
    X_PLAYLIST_GEN_ID = 68
    X_PLAYLIST_SEEK_ID = 69
    X_PROXY_CLIENT_AGENT = 70
    X_PROXY_CLIENT_VERB = 71
    X_RECEDING_PLAYLISTCHANGE = 72
    X_RTP_INFO = 73
    X_STARTUPPROFILE = 74
    TIMESTAMP = 75
    AUTHENTICATION_INFO = 76
    HOST = 77
    PRAGMA = 78
    X_SERVER_IP_ADDRESS = 79
    X_SESSIONCOOKIE = 80
    RTCP_INTERVAL = 81
    KEYMGMT = 82
    PIPELINED_REQUESTS = 83
    MEDIA_PROPERTIES = 84
    SEEK_STYLE = 85
    ACCEPT_RANGES = 86
    FRAMES = 87
    RATE_CONTROL = 88
    LAST = 89

class RTSPLowerTrans(GObject.GFlags):
    UNKNOWN = 0
    UDP = 1
    UDP_MCAST = 2
    TCP = 4
    HTTP = 16
    TLS = 32

class RTSPMethod(GObject.GFlags):
    INVALID = 0
    DESCRIBE = 1
    ANNOUNCE = 2
    GET_PARAMETER = 4
    OPTIONS = 8
    PAUSE = 16
    PLAY = 32
    RECORD = 64
    REDIRECT = 128
    SETUP = 256
    SET_PARAMETER = 512
    TEARDOWN = 1024
    GET = 2048
    POST = 4096

class RTSPMsgType(GObject.GEnum):
    INVALID = 0
    REQUEST = 1
    RESPONSE = 2
    HTTP_REQUEST = 3
    HTTP_RESPONSE = 4
    DATA = 5

class RTSPProfile(GObject.GFlags):
    UNKNOWN = 0
    AVP = 1
    SAVP = 2
    AVPF = 4
    SAVPF = 8

class RTSPRangeUnit(GObject.GEnum):
    SMPTE = 0
    SMPTE_30_DROP = 1
    SMPTE_25 = 2
    NPT = 3
    CLOCK = 4

class RTSPResult(GObject.GEnum):
    OK = 0
    OK_REDIRECT = 1
    ERROR = -1
    EINVAL = -2
    EINTR = -3
    ENOMEM = -4
    ERESOLV = -5
    ENOTIMPL = -6
    ESYS = -7
    EPARSE = -8
    EWSASTART = -9
    EWSAVERSION = -10
    EEOF = -11
    ENET = -12
    ENOTIP = -13
    ETIMEOUT = -14
    ETGET = -15
    ETPOST = -16
    ELAST = -17

class RTSPState(GObject.GEnum):
    INVALID = 0
    INIT = 1
    READY = 2
    SEEKING = 3
    PLAYING = 4
    RECORDING = 5

class RTSPStatusCode(GObject.GEnum):
    INVALID = 0
    CONTINUE = 100
    OK = 200
    CREATED = 201
    LOW_ON_STORAGE = 250
    MULTIPLE_CHOICES = 300
    MOVED_PERMANENTLY = 301
    MOVE_TEMPORARILY = 302
    SEE_OTHER = 303
    NOT_MODIFIED = 304
    USE_PROXY = 305
    REDIRECT_TEMPORARILY = 307
    REDIRECT_PERMANENTLY = 308
    BAD_REQUEST = 400
    UNAUTHORIZED = 401
    PAYMENT_REQUIRED = 402
    FORBIDDEN = 403
    NOT_FOUND = 404
    METHOD_NOT_ALLOWED = 405
    NOT_ACCEPTABLE = 406
    PROXY_AUTH_REQUIRED = 407
    REQUEST_TIMEOUT = 408
    GONE = 410
    LENGTH_REQUIRED = 411
    PRECONDITION_FAILED = 412
    REQUEST_ENTITY_TOO_LARGE = 413
    REQUEST_URI_TOO_LARGE = 414
    UNSUPPORTED_MEDIA_TYPE = 415
    PARAMETER_NOT_UNDERSTOOD = 451
    CONFERENCE_NOT_FOUND = 452
    NOT_ENOUGH_BANDWIDTH = 453
    SESSION_NOT_FOUND = 454
    METHOD_NOT_VALID_IN_THIS_STATE = 455
    HEADER_FIELD_NOT_VALID_FOR_RESOURCE = 456
    INVALID_RANGE = 457
    PARAMETER_IS_READONLY = 458
    AGGREGATE_OPERATION_NOT_ALLOWED = 459
    ONLY_AGGREGATE_OPERATION_ALLOWED = 460
    UNSUPPORTED_TRANSPORT = 461
    DESTINATION_UNREACHABLE = 462
    KEY_MANAGEMENT_FAILURE = 463
    INTERNAL_SERVER_ERROR = 500
    NOT_IMPLEMENTED = 501
    BAD_GATEWAY = 502
    SERVICE_UNAVAILABLE = 503
    GATEWAY_TIMEOUT = 504
    RTSP_VERSION_NOT_SUPPORTED = 505
    OPTION_NOT_SUPPORTED = 551

class RTSPTimeType(GObject.GEnum):
    SECONDS = 0
    NOW = 1
    END = 2
    FRAMES = 3
    UTC = 4

class RTSPTransMode(GObject.GFlags):
    UNKNOWN = 0
    RTP = 1
    RDT = 2

class RTSPVersion(GObject.GEnum):
    INVALID = 0
    _1_0 = 16  # [1_0]: changed because started with a number
    _1_1 = 17  # [1_1]: changed because started with a number
    _2_0 = 32  # [2_0]: changed because started with a number

###############################################################
# classes
###############################################################

class RTSPAuthCredential(GObject.GBoxed):
    # gi Fields
    authorization: str = ...
    params: RTSPAuthParam | None = ...
    scheme: RTSPAuthMethod = ...
    # gi Methods
    def __init__(self) -> None:
        """
        Generated __init__ stub method. order not guaranteed.
        """

    ...

class RTSPAuthParam(GObject.GBoxed):
    # gi Fields
    name: str = ...
    value: str = ...
    # gi Methods
    def __init__(self) -> None:
        """
        Generated __init__ stub method. order not guaranteed.
        """
    def copy(self) -> RTSPAuthParam: ...
    def free(self) -> None: ...

    ...

class RTSPConnection(GObject.GPointer):
    # gi Methods
    def __init__(self) -> None:
        """
        Generated __init__ stub method. order not guaranteed.
        """
    @staticmethod
    def accept(
        socket: Gio.Socket, cancellable: Gio.Cancellable | None = None
    ) -> tuple[RTSPResult, RTSPConnection | None]: ...
    def add_extra_http_request_header(self, key: str, value: str) -> None: ...
    def clear_auth_params(self) -> None: ...
    def close(self) -> RTSPResult: ...
    @deprecated("deprecated")
    def connect(self, timeout: GLib.TimeVal) -> RTSPResult:
        """
        [note from gi-stub-gen] RTSPConnection has a connect() method which shadows the signal connect() method to add handlers to GObject.Signals. You can still connect to signals using: GObject.Object.connect(object, 'signal-name', handler)
        """
    def connect_usec(self, timeout: int) -> RTSPResult: ...
    @deprecated("deprecated")
    def connect_with_response(self, timeout: GLib.TimeVal, response: RTSPMessage) -> RTSPResult: ...
    def connect_with_response_usec(self, timeout: int, response: RTSPMessage) -> RTSPResult: ...
    @staticmethod
    def create(url: RTSPUrl) -> tuple[RTSPResult, RTSPConnection]: ...
    @staticmethod
    def create_from_socket(
        socket: Gio.Socket, ip: str, port: int, initial_buffer: str
    ) -> tuple[RTSPResult, RTSPConnection | None]: ...
    def do_tunnel(self, conn2: RTSPConnection | None = None) -> RTSPResult: ...
    def flush(self, flush: bool) -> RTSPResult: ...
    def free(self) -> RTSPResult: ...
    def get_ignore_x_server_reply(self) -> bool: ...
    def get_ip(self) -> str: ...
    def get_read_socket(self) -> Gio.Socket | None: ...
    def get_remember_session_id(self) -> bool: ...
    def get_tls(self) -> Gio.TlsConnection: ...
    def get_tls_database(self) -> Gio.TlsDatabase | None: ...
    def get_tls_interaction(self) -> Gio.TlsInteraction | None: ...
    def get_tls_validation_flags(self) -> Gio.TlsCertificateFlags: ...
    def get_tunnelid(self) -> str | None: ...
    def get_url(self) -> RTSPUrl: ...
    def get_write_socket(self) -> Gio.Socket | None: ...
    def is_tunneled(self) -> bool: ...
    @deprecated("deprecated")
    def next_timeout(self, timeout: GLib.TimeVal) -> RTSPResult: ...
    def next_timeout_usec(self) -> int: ...
    @deprecated("deprecated")
    def poll(self, events: RTSPEvent, timeout: GLib.TimeVal) -> tuple[RTSPResult, RTSPEvent]: ...
    def poll_usec(self, events: RTSPEvent, timeout: int) -> tuple[RTSPResult, RTSPEvent]: ...
    @deprecated("deprecated")
    def read(self, data: list, size: int, timeout: GLib.TimeVal) -> RTSPResult: ...
    def read_usec(self, data: list, size: int, timeout: int) -> RTSPResult: ...
    @deprecated("deprecated")
    def receive(self, message: RTSPMessage, timeout: GLib.TimeVal) -> RTSPResult: ...
    def receive_usec(self, message: RTSPMessage, timeout: int) -> RTSPResult: ...
    def reset_timeout(self) -> RTSPResult: ...
    @deprecated("deprecated")
    def send(self, message: RTSPMessage, timeout: GLib.TimeVal) -> RTSPResult: ...
    @deprecated("deprecated")
    def send_messages(self, messages: list, n_messages: int, timeout: GLib.TimeVal) -> RTSPResult: ...
    def send_messages_usec(self, messages: list, n_messages: int, timeout: int) -> RTSPResult: ...
    def send_usec(self, message: RTSPMessage, timeout: int) -> RTSPResult: ...
    def set_accept_certificate_func(
        self, func: RTSPConnectionAcceptCertificateFunc, user_data: object | None, destroy_notify: GLib.DestroyNotify
    ) -> None: ...
    def set_auth(self, method: RTSPAuthMethod, user: str, pass_: str) -> RTSPResult: ...
    def set_auth_param(self, param: str, value: str) -> None: ...
    def set_content_length_limit(self, limit: int) -> None: ...
    def set_http_mode(self, enable: bool) -> None: ...
    def set_ignore_x_server_reply(self, ignore: bool) -> None: ...
    def set_ip(self, ip: str) -> None: ...
    def set_proxy(self, host: str, port: int) -> RTSPResult: ...
    def set_qos_dscp(self, qos_dscp: int) -> RTSPResult: ...
    def set_remember_session_id(self, remember: bool) -> None: ...
    def set_tls_database(self, database: Gio.TlsDatabase | None = None) -> None: ...
    def set_tls_interaction(self, interaction: Gio.TlsInteraction | None = None) -> None: ...
    def set_tls_validation_flags(self, flags: Gio.TlsCertificateFlags) -> bool: ...
    def set_tunneled(self, tunneled: bool) -> None: ...
    @deprecated("deprecated")
    def write(self, data: list, size: int, timeout: GLib.TimeVal) -> RTSPResult: ...
    def write_usec(self, data: list, size: int, timeout: int) -> RTSPResult: ...

    ...

class RTSPExtension(GObject.GInterface):
    # gi Methods
    def __init__(self) -> None:
        """
        Generated __init__ stub method. order not guaranteed.
        """
    def after_send(self, req: RTSPMessage, resp: RTSPMessage) -> RTSPResult: ...
    def before_send(self, req: RTSPMessage) -> RTSPResult: ...
    def configure_stream(self, caps: Gst.Caps) -> bool: ...
    def detect_server(self, resp: RTSPMessage) -> bool: ...
    def get_transports(self, protocols: RTSPLowerTrans, transport: str) -> RTSPResult: ...
    def parse_sdp(self, sdp: GstSdp.SDPMessage, s: Gst.Structure) -> RTSPResult: ...
    def receive_request(self, req: RTSPMessage) -> RTSPResult: ...
    def send(self, req: RTSPMessage, resp: RTSPMessage) -> RTSPResult: ...
    def setup_media(self, media: GstSdp.SDPMedia) -> RTSPResult: ...
    def stream_select(self, url: RTSPUrl) -> RTSPResult: ...

    # Signals
    @typing.overload
    def connect(
        self,
        detailed_signal: typing.Literal["send"],
        handler: typing.Callable[[typing_extensions.Self, object | None, object | None], RTSPResult],
        *args: typing.Any,
    ) -> int: ...
    @typing.overload
    def connect(self, detailed_signal: str, handler: typing.Callable[..., typing.Any], *args: typing.Any) -> int: ...
    ...

class RTSPExtensionInterface(GObject.GPointer):
    # gi Fields
    after_send: after_sendRTSPExtensionInterfaceCB = ...
    before_send: before_sendRTSPExtensionInterfaceCB = ...
    configure_stream: configure_streamRTSPExtensionInterfaceCB = ...
    detect_server: detect_serverRTSPExtensionInterfaceCB = ...
    get_transports: get_transportsRTSPExtensionInterfaceCB = ...
    parse_sdp: parse_sdpRTSPExtensionInterfaceCB = ...
    receive_request: receive_requestRTSPExtensionInterfaceCB = ...
    send: sendRTSPExtensionInterfaceCB = ...
    setup_media: setup_mediaRTSPExtensionInterfaceCB = ...
    stream_select: stream_selectRTSPExtensionInterfaceCB = ...
    # gi Methods
    def __init__(self) -> None:
        """
        Generated __init__ stub method. order not guaranteed.
        """

    ...

class RTSPMessage(GObject.GBoxed):
    # gi Fields
    body: int = ...
    body_buffer: Gst.Buffer | None = ...  # type: ignore
    body_size: int = ...
    hdr_fields: list | None = ...
    type: RTSPMsgType = ...
    # gi Methods
    def __init__(self) -> None:
        """
        Generated __init__ stub method. order not guaranteed.
        """
    def add_header(self, field: RTSPHeaderField, value: str) -> RTSPResult: ...
    def add_header_by_name(self, header: str, value: str) -> RTSPResult: ...
    def append_headers(self, str: GLib.String) -> RTSPResult: ...
    def copy(self) -> tuple[RTSPResult, RTSPMessage | None]: ...
    def dump(self) -> RTSPResult: ...
    def free(self) -> RTSPResult: ...
    def get_body(self) -> tuple[RTSPResult, list, int]: ...
    def get_body_buffer(self) -> tuple[RTSPResult, Gst.Buffer]: ...
    def get_header(self, field: RTSPHeaderField, indx: int) -> tuple[RTSPResult, str | None]: ...
    def get_header_by_name(self, header: str, index: int) -> tuple[RTSPResult, str | None]: ...
    def get_type(self) -> RTSPMsgType: ...
    def has_body_buffer(self) -> bool: ...
    def init(self) -> RTSPResult: ...
    def init_data(self, channel: int) -> RTSPResult: ...
    def init_request(self, method: RTSPMethod, uri: str) -> RTSPResult: ...
    def init_response(
        self, code: RTSPStatusCode, reason: str | None = None, request: RTSPMessage | None = None
    ) -> RTSPResult: ...
    def parse_auth_credentials(self, field: RTSPHeaderField) -> list: ...
    def parse_data(self) -> tuple[RTSPResult, int | None]: ...
    def parse_request(self) -> tuple[RTSPResult, RTSPMethod | None, str | None, RTSPVersion | None]: ...
    def parse_response(self) -> tuple[RTSPResult, RTSPStatusCode | None, str | None, RTSPVersion | None]: ...
    def remove_header(self, field: RTSPHeaderField, indx: int) -> RTSPResult: ...
    def remove_header_by_name(self, header: str, index: int) -> RTSPResult: ...
    def set_body(self, data: list, size: int) -> RTSPResult: ...
    def set_body_buffer(self, buffer: Gst.Buffer) -> RTSPResult: ...
    def steal_body(self) -> tuple[RTSPResult, list, int]: ...
    def steal_body_buffer(self) -> tuple[RTSPResult, Gst.Buffer]: ...
    def take_body(self, data: list, size: int) -> RTSPResult: ...
    def take_body_buffer(self, buffer: Gst.Buffer) -> RTSPResult: ...
    def take_header(self, field: RTSPHeaderField, value: str) -> RTSPResult: ...
    def take_header_by_name(self, header: str, value: str) -> RTSPResult: ...
    def unset(self) -> RTSPResult: ...

    ...

class RTSPRange(GObject.GPointer):
    # gi Fields
    max: int = ...
    min: int = ...
    # gi Methods
    def __init__(self) -> None:
        """
        Generated __init__ stub method. order not guaranteed.
        """
    @staticmethod
    def convert_units(range: RTSPTimeRange, unit: RTSPRangeUnit) -> bool: ...
    @staticmethod
    def free(range: RTSPTimeRange) -> None: ...
    @staticmethod
    def get_times(range: RTSPTimeRange) -> tuple[bool, int, int]: ...
    @staticmethod
    def parse(rangestr: str) -> tuple[RTSPResult, RTSPTimeRange]: ...
    @staticmethod
    def to_string(range: RTSPTimeRange) -> str: ...

    ...

class RTSPTime(GObject.GPointer):
    # gi Fields
    seconds: float = ...
    type: RTSPTimeType = ...
    # gi Methods
    def __init__(self) -> None:
        """
        Generated __init__ stub method. order not guaranteed.
        """

    ...

class RTSPTime2(GObject.GPointer):
    # gi Fields
    day: int = ...
    frames: float = ...
    month: int = ...
    year: int = ...
    # gi Methods
    def __init__(self) -> None:
        """
        Generated __init__ stub method. order not guaranteed.
        """

    ...

class RTSPTimeRange(GObject.GPointer):
    # gi Fields
    max: RTSPTime | None = ...
    max2: RTSPTime2 | None = ...
    min: RTSPTime | None = ...
    min2: RTSPTime2 | None = ...
    unit: RTSPRangeUnit = ...
    # gi Methods
    def __init__(self) -> None:
        """
        Generated __init__ stub method. order not guaranteed.
        """

    ...

class RTSPTransport(GObject.GPointer):
    # gi Fields
    append: bool = ...
    client_port: RTSPRange | None = ...
    destination: str = ...
    interleaved: RTSPRange | None = ...
    layers: int = ...
    lower_transport: RTSPLowerTrans = ...
    mode_play: bool = ...
    mode_record: bool = ...
    port: RTSPRange | None = ...
    profile: RTSPProfile = ...
    server_port: RTSPRange | None = ...
    source: str = ...
    ssrc: int = ...
    trans: RTSPTransMode = ...
    ttl: int = ...
    # gi Methods
    def __init__(self) -> None:
        """
        Generated __init__ stub method. order not guaranteed.
        """
    def as_text(self) -> str | None: ...
    def free(self) -> RTSPResult: ...
    @staticmethod
    def get_manager(trans: RTSPTransMode, option: int) -> tuple[RTSPResult, str | None]: ...
    def get_media_type(self) -> tuple[RTSPResult, str]: ...
    @deprecated("deprecated")
    @staticmethod
    def get_mime(trans: RTSPTransMode) -> tuple[RTSPResult, str]: ...
    @staticmethod
    def init() -> tuple[RTSPResult, RTSPTransport]: ...
    @staticmethod
    def new() -> tuple[RTSPResult, RTSPTransport]: ...
    @staticmethod
    def parse(str: str) -> tuple[RTSPResult, RTSPTransport]: ...

    ...

class RTSPUrl(GObject.GBoxed):
    # gi Fields
    abspath: str = ...
    family: RTSPFamily = ...
    host: str = ...
    passwd: str = ...
    port: int = ...
    query: str = ...
    transports: RTSPLowerTrans = ...
    user: str = ...
    # gi Methods
    def __init__(self) -> None:
        """
        Generated __init__ stub method. order not guaranteed.
        """
    def copy(self) -> RTSPUrl: ...
    def decode_path_components(self) -> list: ...
    def free(self) -> None: ...
    def get_port(self) -> tuple[RTSPResult, int]: ...
    def get_request_uri(self) -> str: ...
    def get_request_uri_with_control(self, control_path: str) -> str: ...
    @staticmethod
    def parse(urlstr: str) -> tuple[RTSPResult, RTSPUrl | None]: ...
    def set_port(self, port: int) -> RTSPResult: ...

    ...

class RTSPWatch(GObject.GPointer):
    # gi Methods
    def __init__(self) -> None:
        """
        Generated __init__ stub method. order not guaranteed.
        """
    def attach(self, context: GLib.MainContext | None = None) -> int: ...
    def get_send_backlog(self) -> tuple[int | None, int | None]: ...
    def reset(self) -> None: ...
    def send_message(self, message: RTSPMessage) -> tuple[RTSPResult, int | None]: ...
    def send_messages(self, messages: list, n_messages: int) -> tuple[RTSPResult, int | None]: ...
    def set_flushing(self, flushing: bool) -> None: ...
    def set_send_backlog(self, bytes: int, messages: int) -> None: ...
    def unref(self) -> None: ...
    @deprecated("deprecated")
    def wait_backlog(self, timeout: GLib.TimeVal) -> RTSPResult: ...
    def wait_backlog_usec(self, timeout: int) -> RTSPResult: ...
    def write_data(self, data: list, size: int) -> tuple[RTSPResult, int | None]: ...

    ...

class RTSPWatchFuncs(GObject.GPointer):
    # gi Fields
    closed: closedRTSPWatchFuncsCB = ...
    error: errorRTSPWatchFuncsCB = ...
    error_full: error_fullRTSPWatchFuncsCB = ...
    message_received: message_receivedRTSPWatchFuncsCB = ...
    message_sent: message_sentRTSPWatchFuncsCB = ...
    tunnel_complete: tunnel_completeRTSPWatchFuncsCB = ...
    tunnel_http_response: tunnel_http_responseRTSPWatchFuncsCB = ...
    tunnel_lost: tunnel_lostRTSPWatchFuncsCB = ...
    tunnel_start: tunnel_startRTSPWatchFuncsCB = ...
    # gi Methods
    def __init__(self) -> None:
        """
        Generated __init__ stub method. order not guaranteed.
        """

    ...

###############################################################
# Callbacks
###############################################################

class RTSPConnectionAcceptCertificateFunc(typing.Protocol):
    """
    This callback was used in:
        GstRtsp.set_accept_certificate_func
    """
    #  conn
    def __call__(
        self,
        conn: Gio.TlsConnection,
        peer_cert: Gio.TlsCertificate,
        errors: Gio.TlsCertificateFlags,
        user_data: object | None = None,
    ) -> bool: ...

class detect_serverRTSPExtensionInterfaceCB(typing.Protocol):
    """
    This callback was used in:
        RTSPExtensionInterface.detect_server
    """
    #  ext
    def __call__(
        self,
        ext: RTSPExtension,
        resp: RTSPMessage,
    ) -> bool: ...

class before_sendRTSPExtensionInterfaceCB(typing.Protocol):
    """
    This callback was used in:
        RTSPExtensionInterface.before_send
    """
    #  ext
    def __call__(
        self,
        ext: RTSPExtension,
        req: RTSPMessage,
    ) -> RTSPResult: ...

class after_sendRTSPExtensionInterfaceCB(typing.Protocol):
    """
    This callback was used in:
        RTSPExtensionInterface.after_send
    """
    #  ext
    def __call__(
        self,
        ext: RTSPExtension,
        req: RTSPMessage,
        resp: RTSPMessage,
    ) -> RTSPResult: ...

class parse_sdpRTSPExtensionInterfaceCB(typing.Protocol):
    """
    This callback was used in:
        RTSPExtensionInterface.parse_sdp
    """
    #  ext
    def __call__(
        self,
        ext: RTSPExtension,
        sdp: GstSdp.SDPMessage,
        s: Gst.Structure,
    ) -> RTSPResult: ...

class setup_mediaRTSPExtensionInterfaceCB(typing.Protocol):
    """
    This callback was used in:
        RTSPExtensionInterface.setup_media
    """
    #  ext
    def __call__(
        self,
        ext: RTSPExtension,
        media: GstSdp.SDPMedia,
    ) -> RTSPResult: ...

class configure_streamRTSPExtensionInterfaceCB(typing.Protocol):
    """
    This callback was used in:
        RTSPExtensionInterface.configure_stream
    """
    #  ext
    def __call__(
        self,
        ext: RTSPExtension,
        caps: Gst.Caps,
    ) -> bool: ...

class get_transportsRTSPExtensionInterfaceCB(typing.Protocol):
    """
    This callback was used in:
        RTSPExtensionInterface.get_transports
    """
    #  ext
    def __call__(
        self,
        ext: RTSPExtension,
        protocols: RTSPLowerTrans,
        transport: str,
    ) -> RTSPResult: ...

class stream_selectRTSPExtensionInterfaceCB(typing.Protocol):
    """
    This callback was used in:
        RTSPExtensionInterface.stream_select
    """
    #  ext
    def __call__(
        self,
        ext: RTSPExtension,
        url: RTSPUrl,
    ) -> RTSPResult: ...

class sendRTSPExtensionInterfaceCB(typing.Protocol):
    """
    This callback was used in:
        RTSPExtensionInterface.send
    """
    #  ext
    def __call__(
        self,
        ext: RTSPExtension,
        req: RTSPMessage,
        resp: RTSPMessage,
    ) -> RTSPResult: ...

class receive_requestRTSPExtensionInterfaceCB(typing.Protocol):
    """
    This callback was used in:
        RTSPExtensionInterface.receive_request
    """
    #  ext
    def __call__(
        self,
        ext: RTSPExtension,
        req: RTSPMessage,
    ) -> RTSPResult: ...

class message_receivedRTSPWatchFuncsCB(typing.Protocol):
    """
    This callback was used in:
        RTSPWatchFuncs.message_received
    """
    #  watch
    def __call__(
        self,
        watch: RTSPWatch,
        message: RTSPMessage,
        user_data: object | None = None,
    ) -> RTSPResult: ...

class message_sentRTSPWatchFuncsCB(typing.Protocol):
    """
    This callback was used in:
        RTSPWatchFuncs.message_sent
    """
    #  watch
    def __call__(
        self,
        watch: RTSPWatch,
        id: int,
        user_data: object | None = None,
    ) -> RTSPResult: ...

class closedRTSPWatchFuncsCB(typing.Protocol):
    """
    This callback was used in:
        RTSPWatchFuncs.closed
    """
    #  watch
    def __call__(
        self,
        watch: RTSPWatch,
        user_data: object | None = None,
    ) -> RTSPResult: ...

class errorRTSPWatchFuncsCB(typing.Protocol):
    """
    This callback was used in:
        RTSPWatchFuncs.error
    """
    #  watch
    def __call__(
        self,
        watch: RTSPWatch,
        result: RTSPResult,
        user_data: object | None = None,
    ) -> RTSPResult: ...

class tunnel_startRTSPWatchFuncsCB(typing.Protocol):
    """
    This callback was used in:
        RTSPWatchFuncs.tunnel_start
    """
    #  watch
    def __call__(
        self,
        watch: RTSPWatch,
        user_data: object | None = None,
    ) -> RTSPStatusCode: ...

class tunnel_completeRTSPWatchFuncsCB(typing.Protocol):
    """
    This callback was used in:
        RTSPWatchFuncs.tunnel_complete
    """
    #  watch
    def __call__(
        self,
        watch: RTSPWatch,
        user_data: object | None = None,
    ) -> RTSPResult: ...

class error_fullRTSPWatchFuncsCB(typing.Protocol):
    """
    This callback was used in:
        RTSPWatchFuncs.error_full
    """
    #  watch
    def __call__(
        self,
        watch: RTSPWatch,
        result: RTSPResult,
        message: RTSPMessage,
        id: int,
        user_data: object | None = None,
    ) -> RTSPResult: ...

class tunnel_lostRTSPWatchFuncsCB(typing.Protocol):
    """
    This callback was used in:
        RTSPWatchFuncs.tunnel_lost
    """
    #  watch
    def __call__(
        self,
        watch: RTSPWatch,
        user_data: object | None = None,
    ) -> RTSPResult: ...

class tunnel_http_responseRTSPWatchFuncsCB(typing.Protocol):
    """
    This callback was used in:
        RTSPWatchFuncs.tunnel_http_response
    """
    #  watch
    def __call__(
        self,
        watch: RTSPWatch,
        request: RTSPMessage,
        response: RTSPMessage,
        user_data: object | None = None,
    ) -> RTSPResult: ...

###############################################################
# Aliases
###############################################################

_lock = _thread._lock  # type: ignore
###############################################################
# Constants
###############################################################

RTSP_DEFAULT_PORT: int = ...
_namespace: str = ...
_version: str = ...
###############################################################
# Unknowns/Not Parsed
###############################################################
