# pyright: reportIncompatibleMethodOverride=false
"""
Stub template for a GI Repository Module.

Generated by gi-stub-gen, version 0.0.1.
Module: GstRtsp
Date: 2026-06-28
"""
# we disable method override report for pyright in generated stubs,
# causes too many false positives

from __future__ import annotations
from typing_extensions import deprecated  # noqa: F401
import typing_extensions  # noqa: F401

import _thread
import builtins
import typing

# gi.repository imports needed by this Stub
from gi.repository import GLib
from gi.repository import GObject
from gi.repository import Gio
from gi.repository import Gst
from gi.repository import GstSdp
###############################################################
# Functions
###############################################################

def rtsp_auth_credentials_free(
    credentials: RTSPAuthCredential,
) -> None:
    """
    Free a None-terminated array of credentials returned from
    `gst_rtsp_message_parse_auth_credentials`.
    """
    ...

def rtsp_connection_accept(
    socket: Gio.Socket,
    cancellable: Gio.Cancellable | None = None,
) -> tuple[RTSPResult, RTSPConnection | None]:
    """
    Accept a new connection on `socket` and create a new GstRTSPConnection for
    handling communication on new socket.
    """
    ...

def rtsp_connection_create(
    url: RTSPUrl,
) -> tuple[RTSPResult, RTSPConnection]:
    """
    Create a newly allocated GstRTSPConnection from `url` and store it in `conn`.
    The connection will not yet attempt to connect to `url`, use
    `gst_rtsp_connection_connect`.

    A copy of `url` will be made.
    """
    ...

def rtsp_connection_create_from_socket(
    socket: Gio.Socket,
    ip: str,
    port: int,
    initial_buffer: str,
) -> tuple[RTSPResult, RTSPConnection | None]:
    """
    Create a new GstRTSPConnection for handling communication on the existing
    socket `socket`. The `initial_buffer` contains zero terminated data already
    read from `socket` which should be used before starting to read new data.
    """
    ...

def rtsp_find_header_field(
    header: str,
) -> RTSPHeaderField:
    """
    Convert `header` to a GstRTSPHeaderField.
    """
    ...

def rtsp_find_method(
    method: str,
) -> RTSPMethod:
    """
    Convert `method` to a GstRTSPMethod.
    """
    ...

def rtsp_generate_digest_auth_response(
    algorithm: str | None,
    method: str,
    realm: str,
    username: str,
    password: str,
    uri: str,
    nonce: str,
) -> str | None:
    """
    Calculates the digest auth response from the values given by the server and
    the username and password. See RFC2069 for details.

    Currently only supported algorithm "md5".
    """
    ...

def rtsp_generate_digest_auth_response_from_md5(
    algorithm: str | None,
    method: str,
    md5: str,
    uri: str,
    nonce: str,
) -> str | None:
    """
    Calculates the digest auth response from the values given by the server and
    the md5sum. See RFC2069 for details.

    This function is useful when the passwords are not stored in clear text,
    but instead in the same format as the .htdigest file.

    Currently only supported algorithm "md5".
    """
    ...

def rtsp_header_allow_multiple(
    field: RTSPHeaderField,
) -> bool:
    """
    Check whether `field` may appear multiple times in a message.
    """
    ...

def rtsp_header_as_text(
    field: RTSPHeaderField,
) -> str | None:
    """
    Convert `field` to a string.
    """
    ...

def rtsp_message_new() -> tuple[RTSPResult, RTSPMessage]:
    """
    Create a new initialized GstRTSPMessage. Free with `gst_rtsp_message_free`.
    """
    ...

def rtsp_message_new_data(
    channel: int,
) -> tuple[RTSPResult, RTSPMessage]:
    """
    Create a new data GstRTSPMessage with `channel` and store the
    result message in `msg`. Free with `gst_rtsp_message_free`.
    """
    ...

def rtsp_message_new_request(
    method: RTSPMethod,
    uri: str,
) -> tuple[RTSPResult, RTSPMessage]:
    """
    Create a new GstRTSPMessage with `method` and `uri` and store the result
    request message in `msg`. Free with `gst_rtsp_message_free`.
    """
    ...

def rtsp_message_new_response(
    code: RTSPStatusCode,
    reason: str | None = None,
    request: RTSPMessage | None = None,
) -> tuple[RTSPResult, RTSPMessage]:
    """
    Create a new response GstRTSPMessage with `code` and `reason` and store the
    result message in `msg`. Free with `gst_rtsp_message_free`.

    When `reason` is None, the default reason for `code` will be used.

    When `request` is not None, the relevant headers will be copied to the new
    response message.
    """
    ...

def rtsp_method_as_text(
    method: RTSPMethod,
) -> str | None:
    """
    Convert `method` to a string.
    """
    ...

def rtsp_options_as_text(
    options: RTSPMethod,
) -> str:
    """
    Convert `options` to a string.
    """
    ...

def rtsp_options_from_text(
    options: str,
) -> RTSPMethod:
    """
    Convert the comma separated list `options` to a GstRTSPMethod bitwise or
    of methods. This functions is the reverse of `gst_rtsp_options_as_text`.
    """
    ...

def rtsp_range_convert_units(
    range: RTSPTimeRange,
    unit: RTSPRangeUnit,
) -> bool:
    """
    Converts the range in-place between different types of units.
    Ranges containing the special value GST_RTSP_TIME_NOW can not be
    converted as these are only valid for GST_RTSP_RANGE_NPT.
    """
    ...

def rtsp_range_free(
    range: RTSPTimeRange,
) -> None:
    """
    Free the memory allocated by `range`.
    """
    ...

def rtsp_range_get_times(
    range: RTSPTimeRange,
) -> tuple[bool, int, int]:
    """
    Retrieve the minimum and maximum values from `range` converted to
    GstClockTime in `min` and `max`.

    A value of GST_CLOCK_TIME_NONE will be used to signal GST_RTSP_TIME_NOW
    and GST_RTSP_TIME_END for `min` and `max` respectively.

    UTC times will be converted to nanoseconds since 1900.
    """
    ...

def rtsp_range_parse(
    rangestr: str,
) -> tuple[RTSPResult, RTSPTimeRange]:
    """
    Parse `rangestr` to a GstRTSPTimeRange.
    """
    ...

def rtsp_range_to_string(
    range: RTSPTimeRange,
) -> str:
    """
    Convert `range` into a string representation.
    """
    ...

def rtsp_status_as_text(
    code: RTSPStatusCode,
) -> str:
    """
    Convert `code` to a string.
    """
    ...

def rtsp_strresult(
    result: RTSPResult,
) -> str:
    """
    Convert `result` in a human readable string.
    """
    ...

def rtsp_transport_get_manager(
    trans: RTSPTransMode,
    option: int,
) -> tuple[RTSPResult, str | None]:
    """
    Get the GstElement that can handle the buffers transported over `trans`.

    It is possible that there are several managers available, use `option` to
    selected one.

    `manager` will contain an element name or None when no manager is
    needed/available for `trans`.
    """
    ...

@deprecated("deprecated")
def rtsp_transport_get_mime(
    trans: RTSPTransMode,
) -> tuple[RTSPResult, str]:
    """
    Get the mime type of the transport mode `trans`. This mime type is typically
    used to generate GstCaps events.
    """
    ...

def rtsp_transport_init() -> tuple[RTSPResult, RTSPTransport]:
    """
    Initialize `transport` so that it can be used.
    """
    ...

def rtsp_transport_new() -> tuple[RTSPResult, RTSPTransport]:
    """
    Allocate a new initialized GstRTSPTransport. Use `gst_rtsp_transport_free`
    after usage.
    """
    ...

def rtsp_transport_parse(
    str: str,
) -> tuple[RTSPResult, RTSPTransport]:
    """
    Parse the RTSP transport string `str` into `transport`.
    """
    ...

def rtsp_url_parse(
    urlstr: str,
) -> tuple[RTSPResult, RTSPUrl | None]:
    """
    Parse the RTSP `urlstr` into a newly allocated GstRTSPUrl. Free after usage
    with `gst_rtsp_url_free`.
    """
    ...

def rtsp_version_as_text(
    version: RTSPVersion,
) -> str:
    """
    Convert `version` to a string.
    """
    ...

###############################################################
# Enums/Flags
###############################################################

class RTSPAuthMethod(GObject.GEnum):
    """
    Authentication methods, ordered by strength"""

    NONE = 0
    """
    no authentication
    """
    BASIC = 1
    """
    basic authentication
    """
    DIGEST = 2
    """
    digest authentication
    """

class RTSPEvent(GObject.GFlags):
    """
    The possible events for the connection."""

    READ = 1
    """
    connection is readable
    """
    WRITE = 2
    """
    connection is writable
    """

class RTSPFamily(GObject.GEnum):
    """
    The possible network families."""

    NONE = 0
    """
    unknown network family
    """
    INET = 1
    """
    internet
    """
    INET6 = 2
    """
    internet V6
    """

class RTSPHeaderField(GObject.GEnum):
    """
    Enumeration of rtsp header fields"""

    INVALID = 0
    ACCEPT = 1
    ACCEPT_ENCODING = 2
    ACCEPT_LANGUAGE = 3
    ALLOW = 4
    AUTHORIZATION = 5
    BANDWIDTH = 6
    BLOCKSIZE = 7
    CACHE_CONTROL = 8
    CONFERENCE = 9
    CONNECTION = 10
    CONTENT_BASE = 11
    CONTENT_ENCODING = 12
    CONTENT_LANGUAGE = 13
    CONTENT_LENGTH = 14
    CONTENT_LOCATION = 15
    CONTENT_TYPE = 16
    CSEQ = 17
    DATE = 18
    EXPIRES = 19
    FROM = 20
    IF_MODIFIED_SINCE = 21
    LAST_MODIFIED = 22
    PROXY_AUTHENTICATE = 23
    PROXY_REQUIRE = 24
    PUBLIC = 25
    RANGE = 26
    REFERER = 27
    REQUIRE = 28
    RETRY_AFTER = 29
    RTP_INFO = 30
    SCALE = 31
    SESSION = 32
    SERVER = 33
    SPEED = 34
    TRANSPORT = 35
    UNSUPPORTED = 36
    USER_AGENT = 37
    VIA = 38
    WWW_AUTHENTICATE = 39
    CLIENT_CHALLENGE = 40
    REAL_CHALLENGE1 = 41
    REAL_CHALLENGE2 = 42
    REAL_CHALLENGE3 = 43
    SUBSCRIBE = 44
    ALERT = 45
    CLIENT_ID = 46
    COMPANY_ID = 47
    GUID = 48
    REGION_DATA = 49
    MAX_ASM_WIDTH = 50
    LANGUAGE = 51
    PLAYER_START_TIME = 52
    LOCATION = 53
    ETAG = 54
    IF_MATCH = 55
    ACCEPT_CHARSET = 56
    SUPPORTED = 57
    VARY = 58
    X_ACCELERATE_STREAMING = 59
    X_ACCEPT_AUTHENT = 60
    X_ACCEPT_PROXY_AUTHENT = 61
    X_BROADCAST_ID = 62
    X_BURST_STREAMING = 63
    X_NOTICE = 64
    X_PLAYER_LAG_TIME = 65
    X_PLAYLIST = 66
    X_PLAYLIST_CHANGE_NOTICE = 67
    X_PLAYLIST_GEN_ID = 68
    X_PLAYLIST_SEEK_ID = 69
    X_PROXY_CLIENT_AGENT = 70
    X_PROXY_CLIENT_VERB = 71
    X_RECEDING_PLAYLISTCHANGE = 72
    X_RTP_INFO = 73
    X_STARTUPPROFILE = 74
    TIMESTAMP = 75
    AUTHENTICATION_INFO = 76
    HOST = 77
    PRAGMA = 78
    X_SERVER_IP_ADDRESS = 79
    X_SESSIONCOOKIE = 80
    RTCP_INTERVAL = 81
    KEYMGMT = 82
    PIPELINED_REQUESTS = 83
    MEDIA_PROPERTIES = 84
    SEEK_STYLE = 85
    ACCEPT_RANGES = 86
    FRAMES = 87
    RATE_CONTROL = 88
    LAST = 89

class RTSPLowerTrans(GObject.GFlags):
    """
    The different transport methods."""

    UNKNOWN = 0
    """
    invalid transport flag
    """
    UDP = 1
    """
    stream data over UDP
    """
    UDP_MCAST = 2
    """
    stream data over UDP multicast
    """
    TCP = 4
    """
    stream data over TCP
    """
    HTTP = 16
    """
    stream data tunneled over HTTP.
    """
    TLS = 32
    """
    encrypt TCP and HTTP with TLS
    """

class RTSPMethod(GObject.GFlags):
    """
    The different supported RTSP methods."""

    INVALID = 0
    """
    invalid method
    """
    DESCRIBE = 1
    """
    the DESCRIBE method
    """
    ANNOUNCE = 2
    """
    the ANNOUNCE method
    """
    GET_PARAMETER = 4
    """
    the GET_PARAMETER method
    """
    OPTIONS = 8
    """
    the OPTIONS method
    """
    PAUSE = 16
    """
    the PAUSE method
    """
    PLAY = 32
    """
    the PLAY method
    """
    RECORD = 64
    """
    the RECORD method
    """
    REDIRECT = 128
    """
    the REDIRECT method
    """
    SETUP = 256
    """
    the SETUP method
    """
    SET_PARAMETER = 512
    """
    the SET_PARAMETER method
    """
    TEARDOWN = 1024
    """
    the TEARDOWN method
    """
    GET = 2048
    """
    the GET method (HTTP).
    """
    POST = 4096
    """
    the POST method (HTTP).
    """

class RTSPMsgType(GObject.GEnum):
    """
    The type of a message."""

    INVALID = 0
    """
    invalid message type
    """
    REQUEST = 1
    """
    RTSP request message
    """
    RESPONSE = 2
    """
    RTSP response message
    """
    HTTP_REQUEST = 3
    """
    HTTP request message.
    """
    HTTP_RESPONSE = 4
    """
    HTTP response message.
    """
    DATA = 5
    """
    data message
    """

class RTSPProfile(GObject.GFlags):
    """
    The transfer profile to use."""

    UNKNOWN = 0
    """
    invalid profile
    """
    AVP = 1
    """
    the Audio/Visual profile (RFC 3551)
    """
    SAVP = 2
    """
    the secure Audio/Visual profile (RFC 3711)
    """
    AVPF = 4
    """
    the Audio/Visual profile with feedback (RFC 4585)
    """
    SAVPF = 8
    """
    the secure Audio/Visual profile with feedback (RFC 5124)
    """

class RTSPRangeUnit(GObject.GEnum):
    """
    Different possible time range units."""

    SMPTE = 0
    """
    SMPTE timecode
    """
    SMPTE_30_DROP = 1
    """
    29.97 frames per second
    """
    SMPTE_25 = 2
    """
    25 frames per second
    """
    NPT = 3
    """
    Normal play time
    """
    CLOCK = 4
    """
    Absolute time expressed as ISO 8601 timestamps
    """

class RTSPResult(GObject.GEnum):
    """
    Result codes from the RTSP functions."""

    OK = 0
    """
    no error
    """
    OK_REDIRECT = 1
    """
    RTSP request is successful, but was redirected.
    """
    ERROR = -1
    """
    some unspecified error occurred
    """
    EINVAL = -2
    """
    invalid arguments were provided to a function
    """
    EINTR = -3
    """
    an operation was canceled
    """
    ENOMEM = -4
    """
    no memory was available for the operation
    """
    ERESOLV = -5
    """
    a host resolve error occurred
    """
    ENOTIMPL = -6
    """
    function not implemented
    """
    ESYS = -7
    """
    a system error occurred, errno contains more details
    """
    EPARSE = -8
    """
    a parsing error occurred
    """
    EWSASTART = -9
    """
    windows networking could not start
    """
    EWSAVERSION = -10
    """
    windows networking stack has wrong version
    """
    EEOF = -11
    """
    end-of-file was reached
    """
    ENET = -12
    """
    a network problem occurred, h_errno contains more details
    """
    ENOTIP = -13
    """
    the host is not an IP host
    """
    ETIMEOUT = -14
    """
    a timeout occurred
    """
    ETGET = -15
    """
    the tunnel GET request has been performed
    """
    ETPOST = -16
    """
    the tunnel POST request has been performed
    """
    ELAST = -17
    """
    last error
    """

class RTSPState(GObject.GEnum):
    """
    The different RTSP states."""

    INVALID = 0
    """
    invalid state
    """
    INIT = 1
    """
    initializing
    """
    READY = 2
    """
    ready for operation
    """
    SEEKING = 3
    """
    seeking in progress
    """
    PLAYING = 4
    """
    playing
    """
    RECORDING = 5
    """
    recording
    """

class RTSPStatusCode(GObject.GEnum):
    """
    Enumeration of rtsp status codes"""

    INVALID = 0
    CONTINUE = 100
    OK = 200
    CREATED = 201
    LOW_ON_STORAGE = 250
    MULTIPLE_CHOICES = 300
    MOVED_PERMANENTLY = 301
    MOVE_TEMPORARILY = 302
    SEE_OTHER = 303
    NOT_MODIFIED = 304
    USE_PROXY = 305
    REDIRECT_TEMPORARILY = 307
    """
    RTSP request is temporarily redirected
    """
    REDIRECT_PERMANENTLY = 308
    """
    RTSP request is permanently redirected
    """
    BAD_REQUEST = 400
    UNAUTHORIZED = 401
    PAYMENT_REQUIRED = 402
    FORBIDDEN = 403
    NOT_FOUND = 404
    METHOD_NOT_ALLOWED = 405
    NOT_ACCEPTABLE = 406
    PROXY_AUTH_REQUIRED = 407
    REQUEST_TIMEOUT = 408
    GONE = 410
    LENGTH_REQUIRED = 411
    PRECONDITION_FAILED = 412
    REQUEST_ENTITY_TOO_LARGE = 413
    REQUEST_URI_TOO_LARGE = 414
    UNSUPPORTED_MEDIA_TYPE = 415
    PARAMETER_NOT_UNDERSTOOD = 451
    CONFERENCE_NOT_FOUND = 452
    NOT_ENOUGH_BANDWIDTH = 453
    SESSION_NOT_FOUND = 454
    METHOD_NOT_VALID_IN_THIS_STATE = 455
    HEADER_FIELD_NOT_VALID_FOR_RESOURCE = 456
    INVALID_RANGE = 457
    PARAMETER_IS_READONLY = 458
    AGGREGATE_OPERATION_NOT_ALLOWED = 459
    ONLY_AGGREGATE_OPERATION_ALLOWED = 460
    UNSUPPORTED_TRANSPORT = 461
    DESTINATION_UNREACHABLE = 462
    KEY_MANAGEMENT_FAILURE = 463
    INTERNAL_SERVER_ERROR = 500
    NOT_IMPLEMENTED = 501
    BAD_GATEWAY = 502
    SERVICE_UNAVAILABLE = 503
    GATEWAY_TIMEOUT = 504
    RTSP_VERSION_NOT_SUPPORTED = 505
    OPTION_NOT_SUPPORTED = 551

class RTSPTimeType(GObject.GEnum):
    """
    Possible time types."""

    SECONDS = 0
    """
    seconds
    """
    NOW = 1
    """
    now
    """
    END = 2
    """
    end
    """
    FRAMES = 3
    """
    frames and subframes
    """
    UTC = 4
    """
    UTC time
    """

class RTSPTransMode(GObject.GFlags):
    """
    The transfer mode to use."""

    UNKNOWN = 0
    """
    invalid tansport mode
    """
    RTP = 1
    """
    transfer RTP data
    """
    RDT = 2
    """
    transfer RDT (RealMedia) data
    """

class RTSPVersion(GObject.GEnum):
    """
    The supported RTSP versions."""

    INVALID = 0
    """
    unknown/invalid version
    """
    _1_0 = 16  # [1_0]: changed because started with a number
    """
    version 1.0
    """
    _1_1 = 17  # [1_1]: changed because started with a number
    """
    version 1.1.
    """
    _2_0 = 32  # [2_0]: changed because started with a number
    """
    version 2.0.
    """

###############################################################
# classes
###############################################################

class RTSPAuthCredential(GObject.GBoxed, metaclass=GObject.GType):
    """
    RTSP Authentication credentials
    """

    # gi Fields
    authorization: str = ...
    """
    The authorization for the basic schem
    """
    params: RTSPAuthParam | None = ...
    """
    A None-terminated array of GstRTSPAuthParam
    """
    scheme: RTSPAuthMethod = ...
    """
    a GstRTSPAuthMethod
    """

class RTSPAuthParam(GObject.GBoxed, metaclass=GObject.GType):
    """
    RTSP Authentication parameter
    """

    # gi Fields
    name: str = ...
    """
    The name of the parameter
    """
    value: str = ...
    """
    The value of the parameter
    """

    # gi Methods
    def copy(self) -> RTSPAuthParam: ...
    def free(self) -> None: ...

class RTSPConnection(GObject.GPointer, metaclass=GObject.GType):
    """
    This object manages the RTSP connection to the server. It provides function
    to receive and send bytes and messages.
    """

    # gi Methods
    @staticmethod
    def accept(
        socket: Gio.Socket, cancellable: Gio.Cancellable | None = None
    ) -> tuple[RTSPResult, RTSPConnection | None]:
        """
            Accept a new connection on `socket` and create a new GstRTSPConnection for
        handling communication on new socket.
        """
    def add_extra_http_request_header(self, key: str, value: str) -> None:
        """
            Add header to be appended to any HTTP request made by connection.
        If the header already exists then the old header is replaced by the new header.

        Only applicable in HTTP tunnel mode.
        """
    def clear_auth_params(self) -> None:
        """
        Clear the list of authentication directives stored in `conn`.
        """
    def close(self) -> RTSPResult:
        """
            Close the connected `conn`. After this call, the connection is in the same
        state as when it was first created.
        """
    @deprecated("deprecated")
    def connect(self, timeout: GLib.TimeVal) -> RTSPResult:
        """
            Attempt to connect to the url of `conn` made with
        `gst_rtsp_connection_create`. If `timeout` is None this function can block
        forever. If `timeout` contains a valid timeout, this function will return
        GST_RTSP_ETIMEOUT after the timeout expired.

        This function can be cancelled with `gst_rtsp_connection_flush`.

        [note from gi-stub-gen] RTSPConnection has a connect() method which shadows the signal connect() method to add handlers to GObject.Signals. You can still connect to signals using: GObject.Object.connect(object, 'signal-name', handler)
        """
    def connect_usec(self, timeout: int) -> RTSPResult:
        """
            Attempt to connect to the url of `conn` made with
        `gst_rtsp_connection_create`. If `timeout` is 0 this function can block
        forever. If `timeout` contains a valid timeout, this function will return
        GST_RTSP_ETIMEOUT after the timeout expired.

        This function can be cancelled with `gst_rtsp_connection_flush`.
        """
    @deprecated("deprecated")
    def connect_with_response(self, timeout: GLib.TimeVal, response: RTSPMessage) -> RTSPResult:
        """
            Attempt to connect to the url of `conn` made with
        `gst_rtsp_connection_create`. If `timeout` is None this function can block
        forever. If `timeout` contains a valid timeout, this function will return
        GST_RTSP_ETIMEOUT after the timeout expired.  If `conn` is set to tunneled,
        `response` will contain a response to the tunneling request messages.

        This function can be cancelled with `gst_rtsp_connection_flush`.
        """
    def connect_with_response_usec(self, timeout: int, response: RTSPMessage) -> RTSPResult:
        """
            Attempt to connect to the url of `conn` made with
        `gst_rtsp_connection_create`. If `timeout` is 0 this function can block
        forever. If `timeout` contains a valid timeout, this function will return
        GST_RTSP_ETIMEOUT after the timeout expired.  If `conn` is set to tunneled,
        `response` will contain a response to the tunneling request messages.

        This function can be cancelled with `gst_rtsp_connection_flush`.
        """
    @staticmethod
    def create(url: RTSPUrl) -> tuple[RTSPResult, RTSPConnection]:
        """
            Create a newly allocated GstRTSPConnection from `url` and store it in `conn`.
        The connection will not yet attempt to connect to `url`, use
        `gst_rtsp_connection_connect`.

        A copy of `url` will be made.
        """
    @staticmethod
    def create_from_socket(
        socket: Gio.Socket, ip: str, port: int, initial_buffer: str
    ) -> tuple[RTSPResult, RTSPConnection | None]:
        """
            Create a new GstRTSPConnection for handling communication on the existing
        socket `socket`. The `initial_buffer` contains zero terminated data already
        read from `socket` which should be used before starting to read new data.
        """
    def do_tunnel(self, conn2: RTSPConnection | None = None) -> RTSPResult:
        """
            If `conn` received the first tunnel connection and `conn2` received
        the second tunnel connection, link the two connections together so that
        `conn` manages the tunneled connection.

        After this call, `conn2` cannot be used anymore and must be freed with
        `gst_rtsp_connection_free`.

        If `conn2` is None then only the base64 decoding context will be setup for
        `conn`.
        """
    def flush(self, flush: bool) -> RTSPResult:
        """
            Start or stop the flushing action on `conn`. When flushing, all current
        and future actions on `conn` will return GST_RTSP_EINTR until the connection
        is set to non-flushing mode again.
        """
    def free(self) -> RTSPResult:
        """
        Close and free `conn`.
        """
    def get_ignore_x_server_reply(self) -> bool:
        """
        Get the ignore_x_server_reply value.
        """
    def get_ip(self) -> str | None:
        """
        Retrieve the IP address of the other end of `conn`.
        """
    def get_read_socket(self) -> Gio.Socket | None:
        """
        Get the file descriptor for reading.
        """
    def get_remember_session_id(self) -> bool: ...
    def get_tls(self) -> Gio.TlsConnection:
        """
            Get the TLS connection of `conn`.

        For client side this will return the GTlsClientConnection when connected
        over TLS.

        For server side connections, this function will create a GTlsServerConnection
        when called the first time and will return that same connection on subsequent
        calls. The server is then responsible for configuring the TLS connection.
        """
    def get_tls_database(self) -> Gio.TlsDatabase | None:
        """
            Gets the anchor certificate authorities database that will be used
        after a server certificate can't be verified with the default
        certificate database.
        """
    def get_tls_interaction(self) -> Gio.TlsInteraction | None:
        """
            Gets a GTlsInteraction object to be used when the connection or certificate
        database need to interact with the user. This will be used to prompt the
        user for passwords where necessary.
        """
    def get_tls_validation_flags(self) -> Gio.TlsCertificateFlags:
        """
            Gets the TLS validation flags used to verify the peer certificate
        when a TLS connection is established.

        GLib guarantees that if certificate verification fails, at least one error
        will be set, but it does not guarantee that all possible errors will be
        set. Accordingly, you may not safely decide to ignore any particular type
        of error.

        For example, it would be incorrect to ignore G_TLS_CERTIFICATE_EXPIRED if
        you want to allow expired certificates, because this could potentially be
        the only error flag set even if other problems exist with the certificate.
        """
    def get_tunnelid(self) -> str | None:
        """
        Get the tunnel session id the connection.
        """
    def get_url(self) -> RTSPUrl:
        """
        Retrieve the URL of the other end of `conn`.
        """
    def get_write_socket(self) -> Gio.Socket | None:
        """
        Get the file descriptor for writing.
        """
    def is_tunneled(self) -> bool:
        """
        Get the tunneling state of the connection.
        """
    @deprecated("deprecated")
    def next_timeout(self, timeout: GLib.TimeVal) -> RTSPResult:
        """
        Calculate the next timeout for `conn`, storing the result in `timeout`.
        """
    def next_timeout_usec(self) -> int:
        """
        Calculate the next timeout for `conn`
        """
    @deprecated("deprecated")
    def poll(self, events: RTSPEvent, timeout: GLib.TimeVal) -> tuple[RTSPResult, RTSPEvent]:
        """
            Wait up to the specified `timeout` for the connection to become available for
        at least one of the operations specified in `events`. When the function returns
        with GST_RTSP_OK, `revents` will contain a bitmask of available operations on
        `conn`.

        `timeout` can be None, in which case this function might block forever.

        This function can be cancelled with `gst_rtsp_connection_flush`.
        """
    def poll_usec(self, events: RTSPEvent, timeout: int) -> tuple[RTSPResult, RTSPEvent]:
        """
            Wait up to the specified `timeout` for the connection to become available for
        at least one of the operations specified in `events`. When the function returns
        with GST_RTSP_OK, `revents` will contain a bitmask of available operations on
        `conn`.

        `timeout` can be 0, in which case this function might block forever.

        This function can be cancelled with `gst_rtsp_connection_flush`.
        """
    @deprecated("deprecated")
    def read(self, data: bytes, size: int, timeout: GLib.TimeVal) -> RTSPResult:
        """
            Attempt to read `size` bytes into `data` from the connected `conn`, blocking up to
        the specified `timeout`. `timeout` can be None, in which case this function
        might block forever.

        This function can be cancelled with `gst_rtsp_connection_flush`.
        """
    def read_usec(self, data: bytes, size: int, timeout: int) -> RTSPResult:
        """
            Attempt to read `size` bytes into `data` from the connected `conn`, blocking up to
        the specified `timeout`. `timeout` can be 0, in which case this function
        might block forever.

        This function can be cancelled with `gst_rtsp_connection_flush`.
        """
    @deprecated("deprecated")
    def receive(self, message: RTSPMessage, timeout: GLib.TimeVal) -> RTSPResult:
        """
            Attempt to read into `message` from the connected `conn`, blocking up to
        the specified `timeout`. `timeout` can be None, in which case this function
        might block forever.

        This function can be cancelled with `gst_rtsp_connection_flush`.
        """
    def receive_usec(self, message: RTSPMessage, timeout: int) -> RTSPResult:
        """
            Attempt to read into `message` from the connected `conn`, blocking up to
        the specified `timeout`. `timeout` can be 0, in which case this function
        might block forever.

        This function can be cancelled with `gst_rtsp_connection_flush`.
        """
    def reset_timeout(self) -> RTSPResult:
        """
        Reset the timeout of `conn`.
        """
    @deprecated("deprecated")
    def send(self, message: RTSPMessage, timeout: GLib.TimeVal) -> RTSPResult:
        """
            Attempt to send `message` to the connected `conn`, blocking up to
        the specified `timeout`. `timeout` can be None, in which case this function
        might block forever.

        This function can be cancelled with `gst_rtsp_connection_flush`.
        """
    @deprecated("deprecated")
    def send_messages(self, messages: list, n_messages: int, timeout: GLib.TimeVal) -> RTSPResult:
        """
            Attempt to send `messages` to the connected `conn`, blocking up to
        the specified `timeout`. `timeout` can be None, in which case this function
        might block forever.

        This function can be cancelled with `gst_rtsp_connection_flush`.
        """
    def send_messages_usec(self, messages: list, n_messages: int, timeout: int) -> RTSPResult:
        """
            Attempt to send `messages` to the connected `conn`, blocking up to
        the specified `timeout`. `timeout` can be 0, in which case this function
        might block forever.

        This function can be cancelled with `gst_rtsp_connection_flush`.
        """
    def send_usec(self, message: RTSPMessage, timeout: int) -> RTSPResult:
        """
            Attempt to send `message` to the connected `conn`, blocking up to
        the specified `timeout`. `timeout` can be 0, in which case this function
        might block forever.

        This function can be cancelled with `gst_rtsp_connection_flush`.
        """
    def set_accept_certificate_func(self, func: RTSPConnectionAcceptCertificateFunc, *user_data: object | None) -> None:
        """
            Sets a custom accept-certificate function for checking certificates for
        validity. This will directly map to GTlsConnection 's "accept-certificate"
        signal and be performed after the default checks of GstRTSPConnection
        (checking against the GTlsDatabase with the given GTlsCertificateFlags)
        have failed. If no GTlsDatabase is set on this connection, only `func` will
        be called.
        """
    def set_auth(self, method: RTSPAuthMethod, user: str, pass_: str) -> RTSPResult:
        """
            Configure `conn` for authentication mode `method` with `user` and `pass` as the
        user and password respectively.
        """
    def set_auth_param(self, param: str, value: str) -> None:
        """
            Setup `conn` with authentication directives. This is not necessary for
        methods GST_RTSP_AUTH_NONE and GST_RTSP_AUTH_BASIC. For
        GST_RTSP_AUTH_DIGEST, directives should be taken from the digest challenge
        in the WWW-Authenticate response header and can include realm, domain,
        nonce, opaque, stale, algorithm, qop as per RFC2617.
        """
    def set_content_length_limit(self, limit: int) -> None:
        """
            Configure `conn` to use the specified Content-Length limit.
        Both requests and responses are validated. If content-length is
        exceeded, ENOMEM error will be returned.
        """
    def set_http_mode(self, enable: bool) -> None:
        """
            By setting the HTTP mode to True the message parsing will support HTTP
        messages in addition to the RTSP messages. It will also disable the
        automatic handling of setting up an HTTP tunnel.
        """
    def set_ignore_x_server_reply(self, ignore: bool) -> None:
        """
            Set whether to ignore the x-server-ip-address header reply or not. If the
        header is ignored, the original address will be used instead.
        """
    def set_ip(self, ip: str) -> None:
        """
        Set the IP address of the server.
        """
    def set_proxy(self, host: str, port: int) -> RTSPResult:
        """
        Set the proxy host and port.
        """
    def set_qos_dscp(self, qos_dscp: int) -> RTSPResult:
        """
        Configure `conn` to use the specified DSCP value.
        """
    def set_remember_session_id(self, remember: bool) -> None:
        """
            Sets if the GstRTSPConnection should remember the session id from the last
        response received and force it onto any further requests.

        The default value is True
        """
    def set_tls_database(self, database: Gio.TlsDatabase | None = None) -> None:
        """
            Sets the anchor certificate authorities database. This certificate
        database will be used to verify the server's certificate in case it
        can't be verified with the default certificate database first.
        """
    def set_tls_interaction(self, interaction: Gio.TlsInteraction | None = None) -> None:
        """
            Sets a GTlsInteraction object to be used when the connection or certificate
        database need to interact with the user. This will be used to prompt the
        user for passwords where necessary.
        """
    def set_tls_validation_flags(self, flags: Gio.TlsCertificateFlags) -> bool:
        """
            Sets the TLS validation flags to be used to verify the peer
        certificate when a TLS connection is established.

        GLib guarantees that if certificate verification fails, at least one error
        will be set, but it does not guarantee that all possible errors will be
        set. Accordingly, you may not safely decide to ignore any particular type
        of error.

        For example, it would be incorrect to mask G_TLS_CERTIFICATE_EXPIRED if
        you want to allow expired certificates, because this could potentially be
        the only error flag set even if other problems exist with the certificate.
        """
    def set_tunneled(self, tunneled: bool) -> None:
        """
            Set the HTTP tunneling state of the connection. This must be configured before
        the `conn` is connected.
        """
    @deprecated("deprecated")
    def write(self, data: bytes, size: int, timeout: GLib.TimeVal) -> RTSPResult:
        """
            Attempt to write `size` bytes of `data` to the connected `conn`, blocking up to
        the specified `timeout`. `timeout` can be None, in which case this function
        might block forever.

        This function can be cancelled with `gst_rtsp_connection_flush`.
        """
    def write_usec(self, data: bytes, size: int, timeout: int) -> RTSPResult:
        """
            Attempt to write `size` bytes of `data` to the connected `conn`, blocking up to
        the specified `timeout`. `timeout` can be 0, in which case this function
        might block forever.

        This function can be cancelled with `gst_rtsp_connection_flush`.
        """

class RTSPExtension(builtins.object, metaclass=GObject.GType):
    """
    This interface is implemented e.g. by the Windows Media Streaming RTSP
     exentension (rtspwms) and the RealMedia RTSP extension (rtspreal).
    """

    # gi Methods
    def __init__(self) -> None:
        """
        Initialize RTSPExtension object with properties.
        """
    def after_send(self, req: RTSPMessage, resp: RTSPMessage) -> RTSPResult: ...
    def before_send(self, req: RTSPMessage) -> RTSPResult: ...
    def configure_stream(self, caps: Gst.Caps) -> bool: ...
    def detect_server(self, resp: RTSPMessage) -> bool: ...
    def get_transports(self, protocols: RTSPLowerTrans, transport: str) -> RTSPResult: ...
    def parse_sdp(self, sdp: GstSdp.SDPMessage, s: Gst.Structure) -> RTSPResult: ...
    def receive_request(self, req: RTSPMessage) -> RTSPResult: ...
    def send(self, req: RTSPMessage, resp: RTSPMessage) -> RTSPResult: ...
    def setup_media(self, media: GstSdp.SDPMedia) -> RTSPResult: ...
    def stream_select(self, url: RTSPUrl) -> RTSPResult: ...

    # Signals
    @typing.overload
    def connect(
        self,
        detailed_signal: typing.Literal["send"],
        handler: typing.Callable[[typing_extensions.Self, object | None, object | None], RTSPResult],
        *args: typing.Any,
    ) -> int: ...
    @typing.overload
    def connect(  # type: ignore otherwise pylance will complain and we should repeat all parent overloads here..
        self, detailed_signal: str, handler: typing.Callable[..., typing.Any], *args: typing.Any
    ) -> int: ...

class RTSPExtensionInterface(GObject.GPointer, metaclass=GObject.GType):
    """
    An interface representing RTSP extensions.
    """

    # gi Fields
    @builtins.property
    def _gst_reserved(self) -> list | None: ...
    @builtins.property
    def after_send(self) -> after_sendRTSPExtensionInterfaceCB: ...
    @builtins.property
    def before_send(self) -> before_sendRTSPExtensionInterfaceCB: ...
    @builtins.property
    def configure_stream(self) -> configure_streamRTSPExtensionInterfaceCB: ...
    @builtins.property
    def detect_server(self) -> detect_serverRTSPExtensionInterfaceCB: ...
    @builtins.property
    def get_transports(self) -> get_transportsRTSPExtensionInterfaceCB: ...
    @builtins.property
    def parent(self) -> GObject.TypeInterface | None: ...
    @builtins.property
    def parse_sdp(self) -> parse_sdpRTSPExtensionInterfaceCB: ...
    @builtins.property
    def receive_request(self) -> receive_requestRTSPExtensionInterfaceCB: ...
    @builtins.property
    def send(self) -> sendRTSPExtensionInterfaceCB: ...
    @builtins.property
    def setup_media(self) -> setup_mediaRTSPExtensionInterfaceCB: ...
    @builtins.property
    def stream_select(self) -> stream_selectRTSPExtensionInterfaceCB: ...

class RTSPMessage(GObject.GBoxed, metaclass=GObject.GType):
    """
    Provides methods for creating and parsing request, response and data messages.
    """

    # gi Fields
    @builtins.property
    def _gst_reserved(self) -> list | None: ...
    @builtins.property
    def body(self) -> int: ...
    @builtins.property
    def body_buffer(self) -> Gst.Buffer | None: ...
    @builtins.property
    def body_size(self) -> int: ...
    @builtins.property
    def hdr_fields(self) -> list | None: ...
    type: RTSPMsgType = ...
    """
    the message type
    """

    # gi Methods
    def add_header(self, field: RTSPHeaderField, value: str) -> RTSPResult:
        """
            Add a header with key `field` and `value` to `msg`. This function takes a copy
        of `value`.
        """
    def add_header_by_name(self, header: str, value: str) -> RTSPResult:
        """
            Add a header with key `header` and `value` to `msg`. This function takes a copy
        of `value`.
        """
    def append_headers(self, str: GLib.String) -> RTSPResult:
        """
            Append the currently configured headers in `msg` to the GString `str` suitable
        for transmission.
        """
    def copy(self) -> tuple[RTSPResult, RTSPMessage | None]:
        """
            Allocate a new copy of `msg` and store the result in `copy`. The value in
        `copy` should be release with gst_rtsp_message_free function.
        """
    def dump(self) -> RTSPResult:
        """
        Dump the contents of `msg` to stdout.
        """
    def free(self) -> RTSPResult:
        """
        Free the memory used by `msg`.
        """
    def get_body(self) -> tuple[RTSPResult, bytes, int]:
        """
            Get the body of `msg`. `data` remains valid for as long as `msg` is valid and
        unchanged.

        If the message body was set as a GstBuffer before this will cause the data
        to be copied and stored in the message. The GstBuffer will no longer be
        kept in the message.
        """
    def get_body_buffer(self) -> tuple[RTSPResult, Gst.Buffer]:
        """
            Get the body of `msg`. `buffer` remains valid for as long as `msg` is valid and
        unchanged.

        If body data was set from raw memory instead of a GstBuffer this function
        will always return None. The caller can check if there is a body buffer by
        calling `gst_rtsp_message_has_body_buffer`.
        """
    def get_header(self, field: RTSPHeaderField, indx: int) -> tuple[RTSPResult, str | None]:
        """
            Get the `indx` header value with key `field` from `msg`. The result in `value`
        stays valid as long as it remains present in `msg`.
        """
    def get_header_by_name(self, header: str, index: int) -> tuple[RTSPResult, str | None]:
        """
            Get the `index` header value with key `header` from `msg`. The result in `value`
        stays valid as long as it remains present in `msg`.
        """
    def get_type(self) -> RTSPMsgType:
        """
        Get the message type of `msg`.
        """
    def has_body_buffer(self) -> bool:
        """
        Checks if `msg` has a body and the body is stored as GstBuffer.
        """
    def init(self) -> RTSPResult:
        """
            Initialize `msg`. This function is mostly used when `msg` is allocated on the
        stack. The reverse operation of this is `gst_rtsp_message_unset`.
        """
    def init_data(self, channel: int) -> RTSPResult:
        """
        Initialize a new data GstRTSPMessage for `channel`.
        """
    def init_request(self, method: RTSPMethod, uri: str) -> RTSPResult:
        """
            Initialize `msg` as a request message with `method` and `uri`. To clear `msg`
        again, use `gst_rtsp_message_unset`.
        """
    def init_response(
        self, code: RTSPStatusCode, reason: str | None = None, request: RTSPMessage | None = None
    ) -> RTSPResult:
        """
            Initialize `msg` with `code` and `reason`.

        When `reason` is None, the default reason for `code` will be used.

        When `request` is not None, the relevant headers will be copied to the new
        response message.
        """
    def parse_auth_credentials(self, field: RTSPHeaderField) -> list:
        """
        Parses the credentials given in a WWW-Authenticate or Authorization header.
        """
    def parse_data(self) -> tuple[RTSPResult, int]:
        """
        Parse the data message `msg` and store the channel in `channel`.
        """
    def parse_request(self) -> tuple[RTSPResult, RTSPMethod, str, RTSPVersion]:
        """
            Parse the request message `msg` and store the values `method`, `uri` and
        `version`. The result locations can be None if one is not interested in its
        value.

        `uri` remains valid for as long as `msg` is valid and unchanged.
        """
    def parse_response(self) -> tuple[RTSPResult, RTSPStatusCode, str, RTSPVersion]:
        """
            Parse the response message `msg` and store the values `code`, `reason` and
        `version`. The result locations can be None if one is not interested in its
        value.

        `reason` remains valid for as long as `msg` is valid and unchanged.
        """
    def remove_header(self, field: RTSPHeaderField, indx: int) -> RTSPResult:
        """
            Remove the `indx` header with key `field` from `msg`. If `indx` equals -1, all
        headers will be removed.
        """
    def remove_header_by_name(self, header: str, index: int) -> RTSPResult:
        """
            Remove the `index` header with key `header` from `msg`. If `index` equals -1,
        all matching headers will be removed.
        """
    def set_body(self, data: bytes, size: int) -> RTSPResult:
        """
            Set the body of `msg` to a copy of `data`. Any existing body or body buffer
        will be replaced by the new body.
        """
    def set_body_buffer(self, buffer: Gst.Buffer) -> RTSPResult:
        """
            Set the body of `msg` to `buffer`. Any existing body or body buffer
        will be replaced by the new body.
        """
    def steal_body(self) -> tuple[RTSPResult, bytes, int]:
        """
            Take the body of `msg` and store it in `data` and `size`. After this method,
        the body and size of `msg` will be set to None and 0 respectively.
        """
    def steal_body_buffer(self) -> tuple[RTSPResult, Gst.Buffer]:
        """
            Take the body of `msg` and store it in `buffer`. After this method,
        the body and size of `msg` will be set to None and 0 respectively.

        If body data was set from raw memory instead of a GstBuffer this function
        will always return None. The caller can check if there is a body buffer by
        calling `gst_rtsp_message_has_body_buffer`.
        """
    def take_body(self, data: bytes, size: int) -> RTSPResult:
        """
            Set the body of `msg` to `data` and `size`. This method takes ownership of
        `data`. Any existing body or body buffer will be replaced by the new body.
        """
    def take_body_buffer(self, buffer: Gst.Buffer) -> RTSPResult:
        """
            Set the body of `msg` to `buffer`. This method takes ownership of `buffer`.
        Any existing body or body buffer will be replaced by the new body.
        """
    def take_header(self, field: RTSPHeaderField, value: str) -> RTSPResult:
        """
            Add a header with key `field` and `value` to `msg`. This function takes
        ownership of `value`.
        """
    def take_header_by_name(self, header: str, value: str) -> RTSPResult:
        """
            Add a header with key `header` and `value` to `msg`. This function takes
        ownership of `value`, but not of `header`.
        """
    def unset(self) -> RTSPResult:
        """
            Unset the contents of `msg` so that it becomes an uninitialized
        GstRTSPMessage again. This function is mostly used in combination with
        `gst_rtsp_message_init_request`, `gst_rtsp_message_init_response` and
        `gst_rtsp_message_init_data` on stack allocated GstRTSPMessage structures.
        """

class RTSPRange(GObject.GPointer, metaclass=GObject.GType):
    """
    Provides helper functions to deal with time ranges.
    """

    # gi Fields
    max: int = ...
    """
    maximum value of the range
    """
    min: int = ...
    """
    minimum value of the range
    """

    # gi Methods
    @staticmethod
    def convert_units(range: RTSPTimeRange, unit: RTSPRangeUnit) -> bool:
        """
            Converts the range in-place between different types of units.
        Ranges containing the special value GST_RTSP_TIME_NOW can not be
        converted as these are only valid for GST_RTSP_RANGE_NPT.
        """
    @staticmethod
    def free(range: RTSPTimeRange) -> None:
        """
        Free the memory allocated by `range`.
        """
    @staticmethod
    def get_times(range: RTSPTimeRange) -> tuple[bool, int, int]:
        """
            Retrieve the minimum and maximum values from `range` converted to
        GstClockTime in `min` and `max`.

        A value of GST_CLOCK_TIME_NONE will be used to signal GST_RTSP_TIME_NOW
        and GST_RTSP_TIME_END for `min` and `max` respectively.

        UTC times will be converted to nanoseconds since 1900.
        """
    @staticmethod
    def parse(rangestr: str) -> tuple[RTSPResult, RTSPTimeRange]:
        """
        Parse `rangestr` to a GstRTSPTimeRange.
        """
    @staticmethod
    def to_string(range: RTSPTimeRange) -> str:
        """
        Convert `range` into a string representation.
        """

class RTSPTime(GObject.GPointer, metaclass=GObject.GType):
    """
    A time indication.
    """

    # gi Fields
    seconds: float = ...
    """
    seconds when `type` is GST_RTSP_TIME_SECONDS,
              GST_RTSP_TIME_UTC and GST_RTSP_TIME_FRAMES
    """
    type: RTSPTimeType = ...
    """
    the time of the time
    """

class RTSPTime2(GObject.GPointer, metaclass=GObject.GType):
    """
    Extra fields for a time indication.
    """

    # gi Fields
    day: int = ...
    """
    day when type is GST_RTSP_TIME_UTC
    """
    frames: float = ...
    """
    frames and subframes when type in GstRTSPTime is
             GST_RTSP_TIME_FRAMES
    """
    month: int = ...
    """
    month when type is GST_RTSP_TIME_UTC
    """
    year: int = ...
    """
    year when type is GST_RTSP_TIME_UTC
    """

class RTSPTimeRange(GObject.GPointer, metaclass=GObject.GType):
    """
    A time range.
    """

    # gi Fields
    max: RTSPTime | None = ...
    """
    the maximum interval
    """
    max2: RTSPTime2 | None = ...
    """
    extra fields in the maximum interval (Since: 1.2)
    """
    min: RTSPTime | None = ...
    """
    the minimum interval
    """
    min2: RTSPTime2 | None = ...
    """
    extra fields in the minimum interval (Since: 1.2)
    """
    unit: RTSPRangeUnit = ...
    """
    the time units used
    """

class RTSPTransport(GObject.GPointer, metaclass=GObject.GType):
    """
    Provides helper functions to deal with RTSP transport strings.
    """

    # gi Fields
    @builtins.property
    def _gst_reserved(self) -> list | None: ...
    append: bool = ...
    """
    is append mode was selected
    """
    client_port: RTSPRange | None = ...
    """
    the client port pair for receiving data. For TCP
      based transports, applications can use this field to store the
      sender and receiver ports of the client.
    """
    destination: str = ...
    """
    the destination ip/hostname
    """
    interleaved: RTSPRange | None = ...
    """
    the interleave range
    """
    layers: int = ...
    """
    the number of layers
    """
    lower_transport: RTSPLowerTrans = ...
    """
    the lower transport
    """
    mode_play: bool = ...
    """
    if play mode was selected
    """
    mode_record: bool = ...
    """
    if record mode was selected
    """
    port: RTSPRange | None = ...
    """
    the port pair for multicast sessions
    """
    profile: RTSPProfile = ...
    """
    the tansport profile
    """
    server_port: RTSPRange | None = ...
    """
    the server port pair for receiving data. For TCP
      based transports, applications can use this field to store the
      sender and receiver ports of the server.
    """
    source: str = ...
    """
    the source ip/hostname
    """
    ssrc: int = ...
    """
    the ssrc that the sender/receiver will use
    """
    trans: RTSPTransMode = ...
    """
    the transport mode
    """
    ttl: int = ...
    """
    the time to live for multicast UDP
    """

    # gi Methods
    def as_text(self) -> str | None:
        """
            Convert `transport` into a string that can be used to signal the transport in
        an RTSP SETUP response.
        """
    def free(self) -> RTSPResult:
        """
        Free the memory used by `transport`.
        """
    @staticmethod
    def get_manager(trans: RTSPTransMode, option: int) -> tuple[RTSPResult, str | None]:
        """
            Get the GstElement that can handle the buffers transported over `trans`.

        It is possible that there are several managers available, use `option` to
        selected one.

        `manager` will contain an element name or None when no manager is
        needed/available for `trans`.
        """
    def get_media_type(self) -> tuple[RTSPResult, str]:
        """
            Get the media type of `transport`. This media type is typically
        used to generate GstCaps events.
        """
    @deprecated("deprecated")
    @staticmethod
    def get_mime(trans: RTSPTransMode) -> tuple[RTSPResult, str]:
        """
            Get the mime type of the transport mode `trans`. This mime type is typically
        used to generate GstCaps events.
        """
    @staticmethod
    def init() -> tuple[RTSPResult, RTSPTransport]:
        """
        Initialize `transport` so that it can be used.
        """
    @staticmethod
    def new() -> tuple[RTSPResult, RTSPTransport]:
        """
            Allocate a new initialized GstRTSPTransport. Use `gst_rtsp_transport_free`
        after usage.
        """
    @staticmethod
    def parse(str: str) -> tuple[RTSPResult, RTSPTransport]:
        """
        Parse the RTSP transport string `str` into `transport`.
        """

class RTSPUrl(GObject.GBoxed, metaclass=GObject.GType):
    """
    Provides helper functions to handle RTSP urls.
    """

    # gi Fields
    abspath: str = ...
    """
    the absolute path
    """
    family: RTSPFamily = ...
    """
    the family
    """
    host: str = ...
    """
    the host
    """
    passwd: str = ...
    """
    the password
    """
    port: int = ...
    """
    the port
    """
    query: str = ...
    """
    additional query parameters
    """
    transports: RTSPLowerTrans = ...
    """
    the transports allowed
    """
    user: str = ...
    """
    the user
    """

    # gi Methods
    def copy(self) -> RTSPUrl:
        """
        Make a copy of `url`.
        """
    def decode_path_components(self) -> list:
        """
            Splits the path of `url` on '/' boundaries, decoding the resulting components,

        The decoding performed by this routine is "URI decoding", as defined in RFC
        3986, commonly known as percent-decoding. For example, a string "foo\\2fbar"
        will decode to "foo/bar" -- the \\2f being replaced by the corresponding byte
        with hex value 0x2f. Note that there is no guarantee that the resulting byte
        sequence is valid in any given encoding. As a special case, \\00 is not
        unescaped to NUL, as that would prematurely terminate the string.

        Also note that since paths usually start with a slash, the first component
        will usually be the empty string.
        """
    def free(self) -> None:
        """
        Free the memory used by `url`.
        """
    def get_port(self) -> tuple[RTSPResult, int]:
        """
        Get the port number of `url`.
        """
    def get_request_uri(self) -> str:
        """
        Get a newly allocated string describing the request URI for `url`.
        """
    def get_request_uri_with_control(self, control_path: str) -> str:
        """
            Get a newly allocated string describing the request URI for `url`
        combined with the control path for `control_path`
        """
    @staticmethod
    def parse(urlstr: str) -> tuple[RTSPResult, RTSPUrl | None]:
        """
            Parse the RTSP `urlstr` into a newly allocated GstRTSPUrl. Free after usage
        with `gst_rtsp_url_free`.
        """
    def set_port(self, port: int) -> RTSPResult:
        """
        Set the port number in `url` to `port`.
        """

class RTSPWatch(GObject.GPointer, metaclass=GObject.GType):
    """
    Opaque RTSP watch object that can be used for asynchronous RTSP
    operations.
    """

    # gi Methods
    def attach(self, context: GLib.MainContext | None = None) -> int:
        """
        Adds a GstRTSPWatch to a context so that it will be executed within that context.
        """
    def get_send_backlog(self) -> tuple[int, int]:
        """
            Get the maximum amount of bytes and messages that will be queued in `watch`.
        See `gst_rtsp_watch_set_send_backlog`.
        """
    def reset(self) -> None:
        """
            Reset `watch`, this is usually called after `gst_rtsp_connection_do_tunnel`
        when the file descriptors of the connection might have changed.
        """
    def send_message(self, message: RTSPMessage) -> tuple[RTSPResult, int]:
        """
            Send a `message` using the connection of the `watch`. If it cannot be sent
        immediately, it will be queued for transmission in `watch`. The contents of
        `message` will then be serialized and transmitted when the connection of the
        `watch` becomes writable. In case the `message` is queued, the ID returned in
        `id` will be non-zero and used as the ID argument in the message_sent
        callback.
        """
    def send_messages(self, messages: list, n_messages: int) -> tuple[RTSPResult, int]:
        """
            Sends `messages` using the connection of the `watch`. If they cannot be sent
        immediately, they will be queued for transmission in `watch`. The contents of
        `messages` will then be serialized and transmitted when the connection of the
        `watch` becomes writable. In case the `messages` are queued, the ID returned in
        `id` will be non-zero and used as the ID argument in the message_sent
        callback once the last message is sent. The callback will only be called
        once for the last message.
        """
    def set_flushing(self, flushing: bool) -> None:
        """
            When `flushing` is True, abort a call to `gst_rtsp_watch_wait_backlog`
        and make sure `gst_rtsp_watch_write_data` returns immediately with
        GST_RTSP_EINTR. And empty the queue.
        """
    def set_send_backlog(self, bytes: int, messages: int) -> None:
        """
            Set the maximum amount of bytes and messages that will be queued in `watch`.
        When the maximum amounts are exceeded, `gst_rtsp_watch_write_data` and
        `gst_rtsp_watch_send_message` will return GST_RTSP_ENOMEM.

        A value of 0 for `bytes` or `messages` means no limits.
        """
    def unref(self) -> None:
        """
            Decreases the reference count of `watch` by one. If the resulting reference
        count is zero the watch and associated memory will be destroyed.
        """
    @deprecated("deprecated")
    def wait_backlog(self, timeout: GLib.TimeVal) -> RTSPResult:
        """
            Wait until there is place in the backlog queue, `timeout` is reached
        or `watch` is set to flushing.

        If `timeout` is None this function can block forever. If `timeout`
        contains a valid timeout, this function will return GST_RTSP_ETIMEOUT
        after the timeout expired.

        The typically use of this function is when gst_rtsp_watch_write_data
        returns GST_RTSP_ENOMEM. The caller then calls this function to wait for
        free space in the backlog queue and try again.
        """
    def wait_backlog_usec(self, timeout: int) -> RTSPResult:
        """
            Wait until there is place in the backlog queue, `timeout` is reached
        or `watch` is set to flushing.

        If `timeout` is 0 this function can block forever. If `timeout`
        contains a valid timeout, this function will return GST_RTSP_ETIMEOUT
        after the timeout expired.

        The typically use of this function is when gst_rtsp_watch_write_data
        returns GST_RTSP_ENOMEM. The caller then calls this function to wait for
        free space in the backlog queue and try again.
        """
    def write_data(self, data: bytes, size: int) -> tuple[RTSPResult, int]:
        """
            Write `data` using the connection of the `watch`. If it cannot be sent
        immediately, it will be queued for transmission in `watch`. The contents of
        `message` will then be serialized and transmitted when the connection of the
        `watch` becomes writable. In case the `message` is queued, the ID returned in
        `id` will be non-zero and used as the ID argument in the message_sent
        callback.

        This function will take ownership of `data` and `g_free` it after use.

        If the amount of queued data exceeds the limits set with
        `gst_rtsp_watch_set_send_backlog`, this function will return
        GST_RTSP_ENOMEM.
        """

class RTSPWatchFuncs(GObject.GPointer, metaclass=GObject.GType):
    """
    Callback functions from a GstRTSPWatch.
    """

    # gi Fields
    @builtins.property
    def _gst_reserved(self) -> list | None: ...
    @builtins.property
    def closed(self) -> closedRTSPWatchFuncsCB:
        """
        callback when the connection is closed
        """
    @builtins.property
    def error(self) -> errorRTSPWatchFuncsCB:
        """
        callback when an error occurred
        """
    @builtins.property
    def error_full(self) -> error_fullRTSPWatchFuncsCB:
        """
          callback when an error occurred with more information than
        the `error` callback.
        """
    @builtins.property
    def message_received(self) -> message_receivedRTSPWatchFuncsCB:
        """
        callback when a message was received
        """
    @builtins.property
    def message_sent(self) -> message_sentRTSPWatchFuncsCB:
        """
        callback when a message was sent
        """
    @builtins.property
    def tunnel_complete(self) -> tunnel_completeRTSPWatchFuncsCB:
        """
          a client finished a tunneled connection. In this callback
        you usually pair the tunnelid of this connection with the saved one using
        `gst_rtsp_connection_do_tunnel`.
        """
    @builtins.property
    def tunnel_http_response(self) -> tunnel_http_responseRTSPWatchFuncsCB:
        """
          callback when an HTTP response to the GET request
        is about to be sent for a tunneled connection. The response can be
        modified in the callback. Since: 1.4.
        """
    @builtins.property
    def tunnel_lost(self) -> tunnel_lostRTSPWatchFuncsCB:
        """
        callback when the post connection of a tunnel is closed.
        """
    @builtins.property
    def tunnel_start(self) -> tunnel_startRTSPWatchFuncsCB:
        """
          a client started a tunneled connection. The tunnelid of the
        connection must be saved.
        """

###############################################################
# Callbacks
###############################################################

class RTSPConnectionAcceptCertificateFunc(typing.Protocol):
    """
    This callback was used in:
        GstRtsp.set_accept_certificate_func
    """
    #  conn
    def __call__(
        self,
        conn: Gio.TlsConnection,
        peer_cert: Gio.TlsCertificate,
        errors: Gio.TlsCertificateFlags,
        *user_data: object | None,
    ) -> bool: ...

class detect_serverRTSPExtensionInterfaceCB(typing.Protocol):
    """
    This callback was used in:
        RTSPExtensionInterface.detect_server
    """
    #  ext
    def __call__(
        self,
        ext: RTSPExtension,
        resp: RTSPMessage,
    ) -> bool: ...

class before_sendRTSPExtensionInterfaceCB(typing.Protocol):
    """
    This callback was used in:
        RTSPExtensionInterface.before_send
    """
    #  ext
    def __call__(
        self,
        ext: RTSPExtension,
        req: RTSPMessage,
    ) -> RTSPResult: ...

class after_sendRTSPExtensionInterfaceCB(typing.Protocol):
    """
    This callback was used in:
        RTSPExtensionInterface.after_send
    """
    #  ext
    def __call__(
        self,
        ext: RTSPExtension,
        req: RTSPMessage,
        resp: RTSPMessage,
    ) -> RTSPResult: ...

class parse_sdpRTSPExtensionInterfaceCB(typing.Protocol):
    """
    This callback was used in:
        RTSPExtensionInterface.parse_sdp
    """
    #  ext
    def __call__(
        self,
        ext: RTSPExtension,
        sdp: GstSdp.SDPMessage,
        s: Gst.Structure,
    ) -> RTSPResult: ...

class setup_mediaRTSPExtensionInterfaceCB(typing.Protocol):
    """
    This callback was used in:
        RTSPExtensionInterface.setup_media
    """
    #  ext
    def __call__(
        self,
        ext: RTSPExtension,
        media: GstSdp.SDPMedia,
    ) -> RTSPResult: ...

class configure_streamRTSPExtensionInterfaceCB(typing.Protocol):
    """
    This callback was used in:
        RTSPExtensionInterface.configure_stream
    """
    #  ext
    def __call__(
        self,
        ext: RTSPExtension,
        caps: Gst.Caps,
    ) -> bool: ...

class get_transportsRTSPExtensionInterfaceCB(typing.Protocol):
    """
    This callback was used in:
        RTSPExtensionInterface.get_transports
    """
    #  ext
    def __call__(
        self,
        ext: RTSPExtension,
        protocols: RTSPLowerTrans,
        transport: str,
    ) -> RTSPResult: ...

class stream_selectRTSPExtensionInterfaceCB(typing.Protocol):
    """
    This callback was used in:
        RTSPExtensionInterface.stream_select
    """
    #  ext
    def __call__(
        self,
        ext: RTSPExtension,
        url: RTSPUrl,
    ) -> RTSPResult: ...

class sendRTSPExtensionInterfaceCB(typing.Protocol):
    """
    This callback was used in:
        RTSPExtensionInterface.send
    """
    #  ext
    def __call__(
        self,
        ext: RTSPExtension,
        req: RTSPMessage,
        resp: RTSPMessage,
    ) -> RTSPResult: ...

class receive_requestRTSPExtensionInterfaceCB(typing.Protocol):
    """
    This callback was used in:
        RTSPExtensionInterface.receive_request
    """
    #  ext
    def __call__(
        self,
        ext: RTSPExtension,
        req: RTSPMessage,
    ) -> RTSPResult: ...

class message_receivedRTSPWatchFuncsCB(typing.Protocol):
    """
    This callback was used in:
        RTSPWatchFuncs.message_received
    """
    #  watch
    def __call__(
        self,
        watch: RTSPWatch,
        message: RTSPMessage,
        *user_data: object | None,
    ) -> RTSPResult: ...

class message_sentRTSPWatchFuncsCB(typing.Protocol):
    """
    This callback was used in:
        RTSPWatchFuncs.message_sent
    """
    #  watch
    def __call__(
        self,
        watch: RTSPWatch,
        id: int,
        *user_data: object | None,
    ) -> RTSPResult: ...

class closedRTSPWatchFuncsCB(typing.Protocol):
    """
    This callback was used in:
        RTSPWatchFuncs.closed
    """
    #  watch
    def __call__(
        self,
        watch: RTSPWatch,
        *user_data: object | None,
    ) -> RTSPResult: ...

class errorRTSPWatchFuncsCB(typing.Protocol):
    """
    This callback was used in:
        RTSPWatchFuncs.error
    """
    #  watch
    def __call__(
        self,
        watch: RTSPWatch,
        result: RTSPResult,
        *user_data: object | None,
    ) -> RTSPResult: ...

class tunnel_startRTSPWatchFuncsCB(typing.Protocol):
    """
    This callback was used in:
        RTSPWatchFuncs.tunnel_start
    """
    #  watch
    def __call__(
        self,
        watch: RTSPWatch,
        *user_data: object | None,
    ) -> RTSPStatusCode: ...

class tunnel_completeRTSPWatchFuncsCB(typing.Protocol):
    """
    This callback was used in:
        RTSPWatchFuncs.tunnel_complete
    """
    #  watch
    def __call__(
        self,
        watch: RTSPWatch,
        *user_data: object | None,
    ) -> RTSPResult: ...

class error_fullRTSPWatchFuncsCB(typing.Protocol):
    """
    This callback was used in:
        RTSPWatchFuncs.error_full
    """
    #  watch
    def __call__(
        self,
        watch: RTSPWatch,
        result: RTSPResult,
        message: RTSPMessage,
        id: int,
        *user_data: object | None,
    ) -> RTSPResult: ...

class tunnel_lostRTSPWatchFuncsCB(typing.Protocol):
    """
    This callback was used in:
        RTSPWatchFuncs.tunnel_lost
    """
    #  watch
    def __call__(
        self,
        watch: RTSPWatch,
        *user_data: object | None,
    ) -> RTSPResult: ...

class tunnel_http_responseRTSPWatchFuncsCB(typing.Protocol):
    """
    This callback was used in:
        RTSPWatchFuncs.tunnel_http_response
    """
    #  watch
    def __call__(
        self,
        watch: RTSPWatch,
        request: RTSPMessage,
        response: RTSPMessage,
        *user_data: object | None,
    ) -> RTSPResult: ...

###############################################################
# Aliases
###############################################################

_lock = _thread._lock  # type: ignore
###############################################################
# Constants
###############################################################

RTSP_DEFAULT_PORT: int = ...
_namespace: str = ...
_version: str = ...
