# pyright: reportIncompatibleMethodOverride=false
"""
Stub template for a GI Repository Module.

Generated by gi-stub-gen, version 0.0.1.
Module: GstTranscoder
Date: 2026-07-02
"""
# we disable method override report for pyright in generated stubs,
# causes too many false positives

from __future__ import annotations
from typing_extensions import deprecated  # noqa: F401
import typing_extensions  # noqa: F401

import _thread
import builtins
import enum
import typing

# gi.repository imports needed by this Stub
from gi.repository import GLib
from gi.repository import GObject
from gi.repository import Gst
from gi.repository import GstPbutils
###############################################################
# Functions
###############################################################

def transcoder_error_get_name(
    error: TranscoderError,
) -> str:
    """
    Gets a string representing the given error.
    """
    ...

def transcoder_error_quark() -> int: ...
def transcoder_message_get_name(
    message: TranscoderMessage,
) -> str:
    """
    Returns (transfer none): The message name
    """
    ...

def transcoder_message_parse_duration(
    msg: Gst.Message,
) -> int:
    """
    Parse the given duration `msg` and extract the corresponding GstClockTime
    """
    ...

def transcoder_message_parse_error(
    msg: Gst.Message,
) -> tuple[GLib.Error, Gst.Structure]:
    """
    Parse the given error `msg` and extract the corresponding GError
    """
    ...

def transcoder_message_parse_position(
    msg: Gst.Message,
) -> int:
    """
    Parse the given position `msg` and extract the corresponding GstClockTime
    """
    ...

def transcoder_message_parse_state(
    msg: Gst.Message,
) -> TranscoderState:
    """
    Parse the given state `msg` and extract the corresponding GstTranscoder.State
    """
    ...

def transcoder_message_parse_warning(
    msg: Gst.Message,
) -> tuple[GLib.Error, Gst.Structure]:
    """
    Parse the given error `msg` and extract the corresponding GError warning
    """
    ...

def transcoder_state_get_name(
    state: TranscoderState,
) -> str:
    """
    Gets a string representing the given state.
    """
    ...

###############################################################
# Enums/Flags
###############################################################

class TranscoderError(GObject.GEnum, enum.IntEnum):
    FAILED = 0
    """
    generic error.
    """
    # gi Methods
    @staticmethod
    def get_name(error: TranscoderError) -> str: ...
    @staticmethod
    def quark() -> int: ...

class TranscoderMessage(GObject.GEnum, enum.IntEnum):
    """
    Types of messages that will be posted on the transcoder API bus.

    See also #`gst_transcoder_get_message_bus`"""

    POSITION_UPDATED = 0
    """
    Sink position changed
    """
    DURATION_CHANGED = 1
    """
    Duration of stream changed
    """
    STATE_CHANGED = 2
    """
    Pipeline state changed
    """
    DONE = 3
    """
    Transcoding is done
    """
    ERROR = 4
    """
    Message contains an error
    """
    WARNING = 5
    """
    Message contains an error
    """
    # gi Methods
    @staticmethod
    def get_name(message: TranscoderMessage) -> str: ...
    @staticmethod
    def parse_duration(msg: Gst.Message) -> int: ...
    @staticmethod
    def parse_error(msg: Gst.Message) -> tuple[GLib.Error, Gst.Structure]: ...
    @staticmethod
    def parse_position(msg: Gst.Message) -> int: ...
    @staticmethod
    def parse_state(msg: Gst.Message) -> TranscoderState: ...
    @staticmethod
    def parse_warning(msg: Gst.Message) -> tuple[GLib.Error, Gst.Structure]: ...

class TranscoderState(GObject.GEnum, enum.IntEnum):
    """
    High level representation of the transcoder pipeline state."""

    STOPPED = 0
    """
    the transcoder is stopped.
    """
    PAUSED = 1
    """
    the transcoder is paused.
    """
    PLAYING = 2
    """
    the transcoder is currently transcoding a
    stream.
    """
    # gi Methods
    @staticmethod
    def get_name(state: TranscoderState) -> str: ...

###############################################################
# classes
###############################################################

class Transcoder(Gst.Object):
    class Props(Gst.Object.Props):
        avoid_reencoding: bool  # [avoid-reencoding]: changed because contained invalid characters
        """
        See #encodebin:avoid-reencoding
        """
        dest_uri: str  # [dest-uri]: changed because contained invalid characters
        duration: int
        pipeline: Gst.Element | None
        position: int
        position_update_interval: int  # [position-update-interval]: changed because contained invalid characters
        profile: GstPbutils.EncodingProfile | None
        src_uri: str  # [src-uri]: changed because contained invalid characters

    @builtins.property
    def props(self) -> Props: ...

    # gi Methods
    def __init__(
        self,
        avoid_reencoding: bool | None = None,
        dest_uri: str | None = None,
        name: str | None = None,
        parent: Gst.Object | None = None,
        position_update_interval: int | None = None,
        profile: GstPbutils.EncodingProfile | None = None,
        src_uri: str | None = None,
    ) -> None:
        """
        Initialize Transcoder object with properties.
        """
    def get_avoid_reencoding(self) -> bool: ...
    def get_dest_uri(self) -> str:
        """
        Gets the URI of the destination of the transcoded stream.
        """
    def get_duration(self) -> int:
        """
        Retrieves the duration of the media stream that self represents.
        """
    def get_message_bus(self) -> Gst.Bus:
        """
            GstTranscoder API exposes a GstBus instance which purpose is to provide data
        structures representing transcoder-internal events in form of GstMessage-s of
        type GST_MESSAGE_APPLICATION.

        Each message carries a "transcoder-message" field of type GstTranscoder.Message.
        Further fields of the message data are specific to each possible value of
        that enumeration.

        Applications can consume the messages asynchronously within their own
        event-loop / UI-thread etc. Note that in case the application does not
        consume the messages, the bus will accumulate these internally and eventually
        fill memory. To avoid that, the bus has to be set "flushing".
        """
    def get_pipeline(self) -> Gst.Element: ...
    def get_position(self) -> int: ...
    def get_position_update_interval(self) -> int: ...
    def get_signal_adapter(self, context: GLib.MainContext | None = None) -> TranscoderSignalAdapter | None:
        """
            Gets the GstTranscoder.SignalAdapter attached to `self` if it is attached to
        the right GMainContext. If no GstTranscoder.SignalAdapter has been created
        yet, it will be created and returned, other calls will return that same
        adapter until it is destroyed, at which point, a new one can be attached the
        same way.
        """
    def get_source_uri(self) -> str:
        """
        Gets the URI of the currently-transcoding stream.
        """
    def get_sync_signal_adapter(self) -> TranscoderSignalAdapter:
        """
            Gets the GstTranscoder.SignalAdapter attached to `self` to emit signals from
        its thread of emission.
        """
    @staticmethod
    def is_transcoder_message(msg: Gst.Message) -> bool: ...
    def run(self) -> bool:
        """
            Run the transcoder task synchonously. You can connect
        to the 'position' signal to get information about the
        progress of the transcoding.
        """
    def run_async(self) -> None:
        """
            Run the transcoder task asynchronously. You should connect
        to the 'done' signal to be notified about when the
        transcoding is done, and to the 'error' signal to be
        notified about any error.
        """
    def set_avoid_reencoding(self, avoid_reencoding: bool) -> None: ...
    def set_cpu_usage(self, cpu_usage: int) -> None:
        """
            Sets `cpu_usage` as target percentage CPU usage of the process running the
        transcoding task. It will modulate the transcoding speed to reach that target
        usage.
        """
    def set_position_update_interval(self, interval: int) -> None:
        """
            Set interval in milliseconds between two position-updated signals.
        Pass 0 to stop updating the position.
        """

    # python methods (overrides?)
    @classmethod
    def new(
        cls,
        source_uri: str,
        dest_uri: str,
        encoding_profile: str,
    ) -> Transcoder:
        """
        [is-override: Note this method is an override in Python of the original gi implementation.]

        new(source_uri:str, dest_uri:str, encoding_profile:str) -> GstTranscoder.Transcoder
        """
    @classmethod
    def new_full(
        cls,
        source_uri: str,
        dest_uri: str,
        profile: GstPbutils.EncodingProfile,
    ) -> Transcoder:
        """
        [is-override: Note this method is an override in Python of the original gi implementation.]

        new_full(source_uri:str, dest_uri:str, profile:GstPbutils.EncodingProfile) -> GstTranscoder.Transcoder
        """

    # Signals
    @typing.overload
    def connect(
        self,
        detailed_signal: typing.Literal["deep-notify"],
        handler: typing.Callable[[typing_extensions.Self, Gst.Object, GObject.ParamSpec], None],
        *args: typing.Any,
    ) -> int: ...
    @typing.overload
    def connect(
        self,
        detailed_signal: typing.Literal["notify"],
        handler: typing.Callable[[typing_extensions.Self, GObject.ParamSpec], None],
        *args: typing.Any,
    ) -> int: ...
    @typing.overload
    def connect(
        self,
        detailed_signal: typing.Literal["notify::avoid_reencoding"],
        handler: typing.Callable[[typing_extensions.Self, GObject.ParamSpec, typing.Any], None],
        *args: typing.Any,
    ) -> int: ...
    @typing.overload
    def connect(
        self,
        detailed_signal: typing.Literal["notify::dest_uri"],
        handler: typing.Callable[[typing_extensions.Self, GObject.ParamSpec, typing.Any], None],
        *args: typing.Any,
    ) -> int: ...
    @typing.overload
    def connect(
        self,
        detailed_signal: typing.Literal["notify::duration"],
        handler: typing.Callable[[typing_extensions.Self, GObject.ParamSpec, typing.Any], None],
        *args: typing.Any,
    ) -> int: ...
    @typing.overload
    def connect(
        self,
        detailed_signal: typing.Literal["notify::pipeline"],
        handler: typing.Callable[[typing_extensions.Self, GObject.ParamSpec, typing.Any], None],
        *args: typing.Any,
    ) -> int: ...
    @typing.overload
    def connect(
        self,
        detailed_signal: typing.Literal["notify::position"],
        handler: typing.Callable[[typing_extensions.Self, GObject.ParamSpec, typing.Any], None],
        *args: typing.Any,
    ) -> int: ...
    @typing.overload
    def connect(
        self,
        detailed_signal: typing.Literal["notify::position_update_interval"],
        handler: typing.Callable[[typing_extensions.Self, GObject.ParamSpec, typing.Any], None],
        *args: typing.Any,
    ) -> int: ...
    @typing.overload
    def connect(
        self,
        detailed_signal: typing.Literal["notify::profile"],
        handler: typing.Callable[[typing_extensions.Self, GObject.ParamSpec, typing.Any], None],
        *args: typing.Any,
    ) -> int: ...
    @typing.overload
    def connect(
        self,
        detailed_signal: typing.Literal["notify::src_uri"],
        handler: typing.Callable[[typing_extensions.Self, GObject.ParamSpec, typing.Any], None],
        *args: typing.Any,
    ) -> int: ...
    @typing.overload
    def connect(
        self,
        detailed_signal: typing.Literal["notify::name"],
        handler: typing.Callable[[typing_extensions.Self, GObject.ParamSpec, typing.Any], None],
        *args: typing.Any,
    ) -> int: ...
    @typing.overload
    def connect(
        self,
        detailed_signal: typing.Literal["notify::parent"],
        handler: typing.Callable[[typing_extensions.Self, GObject.ParamSpec, typing.Any], None],
        *args: typing.Any,
    ) -> int: ...
    @typing.overload
    def connect(  # type: ignore otherwise pylance will complain and we should repeat all parent overloads here..
        self, detailed_signal: str, handler: typing.Callable[..., typing.Any], *args: typing.Any
    ) -> int: ...

class TranscoderClass(GObject.GPointer, metaclass=GObject.GType):
    # gi Fields
    @builtins.property
    def parent_class(self) -> Gst.ObjectClass | None: ...

class TranscoderSignalAdapter(GObject.Object):
    """
    Transforms GstTranscoder. bus messages to signals from the adapter object.
    """

    class Props(GObject.Object.Props):
        transcoder: Transcoder | None
        """
        The GstTranscoder. tracked by the adapter.
        """

    @builtins.property
    def props(self) -> Props: ...

    # gi Methods
    def __init__(self) -> None:
        """
        Initialize TranscoderSignalAdapter object with properties.
        """
    def get_transcoder(self) -> Transcoder | None: ...

    # Signals
    @typing.overload
    def connect(
        self, detailed_signal: typing.Literal["done"], handler: typing.Callable[..., None], *args: typing.Any
    ) -> int: ...
    @typing.overload
    def connect(
        self,
        detailed_signal: typing.Literal["duration-changed"],
        handler: typing.Callable[[typing_extensions.Self, int], None],
        *args: typing.Any,
    ) -> int: ...
    @typing.overload
    def connect(
        self,
        detailed_signal: typing.Literal["error"],
        handler: typing.Callable[[typing_extensions.Self, GLib.Error, Gst.Structure], None],
        *args: typing.Any,
    ) -> int: ...
    @typing.overload
    def connect(
        self,
        detailed_signal: typing.Literal["position-updated"],
        handler: typing.Callable[[typing_extensions.Self, int], None],
        *args: typing.Any,
    ) -> int: ...
    @typing.overload
    def connect(
        self,
        detailed_signal: typing.Literal["state-changed"],
        handler: typing.Callable[[typing_extensions.Self, TranscoderState], None],
        *args: typing.Any,
    ) -> int: ...
    @typing.overload
    def connect(
        self,
        detailed_signal: typing.Literal["warning"],
        handler: typing.Callable[[typing_extensions.Self, GLib.Error, Gst.Structure], None],
        *args: typing.Any,
    ) -> int: ...
    @typing.overload
    def connect(
        self,
        detailed_signal: typing.Literal["notify"],
        handler: typing.Callable[[typing_extensions.Self, GObject.ParamSpec], None],
        *args: typing.Any,
    ) -> int: ...
    @typing.overload
    def connect(
        self,
        detailed_signal: typing.Literal["notify::transcoder"],
        handler: typing.Callable[[typing_extensions.Self, GObject.ParamSpec, typing.Any], None],
        *args: typing.Any,
    ) -> int: ...
    @typing.overload
    def connect(  # type: ignore otherwise pylance will complain and we should repeat all parent overloads here..
        self, detailed_signal: str, handler: typing.Callable[..., typing.Any], *args: typing.Any
    ) -> int: ...

class TranscoderSignalAdapterClass(GObject.GPointer, metaclass=GObject.GType):
    # gi Fields
    @builtins.property
    def parent_class(self) -> GObject.ObjectClass | None: ...

###############################################################
# Aliases
###############################################################

_lock = _thread._lock  # type: ignore
###############################################################
# Constants
###############################################################

_namespace: str = ...
_version: str = ...
