from gi_stub_gen.schema.function import FunctionArgumentSchema, FunctionSchema


GIO_TASK_RETURN_VALUE = FunctionSchema(
    name="return_value",
    namespace="Gio",
    is_method=True,
    is_class_member=True,
    is_deprecated=False,
    deprecation_warnings=None,
    docstring=None,
    args=[
        FunctionArgumentSchema(
            namespace="Gio",
            name="result",
            direction="IN",
            is_callback=False,
            may_be_null=True,
            is_optional=False,
            is_deprecated=False,
            is_caller_allocates=False,
            tag_as_string="",
            get_array_length=-1,
            py_type_name="Any",
            py_type_namespace="typing",
            line_comment=None,
            default_value="None",
            is_pointer=True,
            is_marshaled_gvalue_payload=True,
        ),
    ],
    is_callback=False,
    can_throw_gerror=False,
    is_async=False,
    is_constructor=False,
    is_getter=False,
    is_setter=False,
    may_return_null=False,
    return_hint=None,
    return_hint_namespace=None,
    skip_return=False,
    wrap_vfunc=False,
    line_comment=None,
    function_type="FunctionInfo",
    is_overload=False,
)
