from gi_stub_gen.schema.function import FunctionArgumentSchema, FunctionSchema


OBJECT_EMIT = FunctionSchema(
    name="emit",
    namespace="GObject",
    is_method=True,
    is_class_member=True,
    is_deprecated=False,
    deprecation_warnings=None,
    docstring="Emit a signal.",
    args=[
        FunctionArgumentSchema(
            namespace="GObject",
            name="detailed_signal",
            direction="IN",
            is_callback=False,
            may_be_null=False,
            is_optional=False,
            is_deprecated=False,
            is_caller_allocates=False,
            tag_as_string="",
            get_array_length=-1,
            py_type_name="str",
            py_type_namespace=None,
            line_comment=None,
            default_value=None,
            is_pointer=False,
        ),
        FunctionArgumentSchema(
            namespace="GObject",
            name="*args",
            direction="IN",
            is_callback=False,
            may_be_null=False,
            is_optional=False,
            is_deprecated=False,
            is_caller_allocates=False,
            tag_as_string="",
            get_array_length=-1,
            py_type_name="Any",
            py_type_namespace="typing",
            line_comment=None,
            default_value=None,
            is_pointer=False,
        ),
    ],
    is_callback=False,
    can_throw_gerror=False,
    is_async=False,
    is_constructor=False,
    is_getter=False,
    is_setter=False,
    may_return_null=False,
    return_hint="Any",
    return_hint_namespace="typing",
    skip_return=False,
    wrap_vfunc=False,
    line_comment=None,
    function_type="FunctionInfo",
    is_overload=False,
)
OBJECT_WEAK_REF = FunctionSchema(
    name="weak_ref",
    namespace="GObject",
    is_method=True,
    is_class_member=True,
    is_deprecated=False,
    deprecation_warnings=None,
    docstring="Creates a weak reference to the object.",
    args=[
        FunctionArgumentSchema(
            namespace="GObject",
            name="callback",
            direction="IN",
            is_callback=True,
            may_be_null=True,
            is_optional=True,
            is_deprecated=False,
            is_caller_allocates=False,
            tag_as_string="",
            get_array_length=-1,
            py_type_name="Callable[[typing.Any], None]",
            py_type_namespace="typing",
            line_comment=None,
            default_value="None",
            is_pointer=False,
        ),
    ],
    is_callback=False,
    can_throw_gerror=False,
    is_async=False,
    is_constructor=False,
    is_getter=False,
    is_setter=False,
    may_return_null=False,
    return_hint="Any",
    return_hint_namespace="typing",
    skip_return=False,
    wrap_vfunc=False,
    line_comment=None,
    function_type="FunctionInfo",
    is_overload=False,
)
# def get_property(self, property_name: str) -> any: ...

OBJECT_GET_PROPERTY = FunctionSchema(
    name="get_property",
    namespace="GObject",
    is_method=True,
    is_class_member=True,
    is_deprecated=False,
    deprecation_warnings=None,
    docstring="Get a property value by name.",
    args=[
        FunctionArgumentSchema(
            namespace="GObject",
            name="property_name",
            direction="IN",
            is_callback=False,
            may_be_null=False,
            is_optional=False,
            is_deprecated=False,
            is_caller_allocates=False,
            tag_as_string="",
            get_array_length=-1,
            py_type_name="str",
            py_type_namespace=None,
            line_comment=None,
            default_value=None,
            is_pointer=False,
        ),
    ],
    is_callback=False,
    can_throw_gerror=False,
    is_async=False,
    is_constructor=False,
    is_getter=False,
    is_setter=False,
    may_return_null=False,
    return_hint="Any",
    return_hint_namespace="typing",
    skip_return=False,
    wrap_vfunc=False,
    line_comment=None,
    function_type="FunctionInfo",
    is_overload=False,
)
# def set_property(self, property_name: str, value: any) -> None: ...

OBJECT_SET_PROPERTY = FunctionSchema(
    name="set_property",
    namespace="GObject",
    is_method=True,
    is_class_member=True,
    is_deprecated=False,
    deprecation_warnings=None,
    docstring="Set a property value by name.",
    args=[
        FunctionArgumentSchema(
            namespace="GObject",
            name="property_name",
            direction="IN",
            is_callback=False,
            may_be_null=False,
            is_optional=False,
            is_deprecated=False,
            is_caller_allocates=False,
            tag_as_string="",
            get_array_length=-1,
            py_type_name="str",
            py_type_namespace=None,
            line_comment=None,
            default_value=None,
            is_pointer=False,
        ),
        FunctionArgumentSchema(
            namespace="GObject",
            name="value",
            direction="IN",
            is_callback=False,
            may_be_null=False,
            is_optional=False,
            is_deprecated=False,
            is_caller_allocates=False,
            tag_as_string="",
            get_array_length=-1,
            py_type_name="object",
            py_type_namespace="builtins",
            line_comment=None,
            default_value=None,
            is_pointer=False,
        ),
    ],
    is_callback=False,
    can_throw_gerror=False,
    is_async=False,
    is_constructor=False,
    is_getter=False,
    is_setter=False,
    may_return_null=False,
    return_hint="None",
    return_hint_namespace=None,
    skip_return=False,
    wrap_vfunc=False,
    line_comment=None,
    function_type="FunctionInfo",
    is_overload=False,
)


# ============================================================================
# Object method_descriptor methods (PyGObject C implementations)
# ============================================================================


def _make_object_method(
    name: str, docstring: str, args: list[FunctionArgumentSchema], return_hint: str = "None"
) -> FunctionSchema:
    """Helper to create Object method overrides."""
    return FunctionSchema(
        name=name,
        namespace="GObject",
        is_method=True,
        is_class_member=True,
        is_deprecated=False,
        deprecation_warnings=None,
        docstring=docstring,
        args=args,
        is_callback=False,
        can_throw_gerror=False,
        is_async=False,
        is_constructor=False,
        is_getter=False,
        is_setter=False,
        may_return_null=False,
        return_hint=return_hint,
        return_hint_namespace="typing" if return_hint == "Any" else None,
        skip_return=False,
        wrap_vfunc=False,
        line_comment=None,
        function_type="FunctionInfo",
        is_overload=False,
    )


OBJECT_CHAIN = _make_object_method(
    name="chain",
    docstring="Chain up to parent class method implementation.",
    args=[
        FunctionArgumentSchema(
            namespace="GObject",
            name="*args",
            direction="IN",
            is_callback=False,
            may_be_null=False,
            is_optional=False,
            is_deprecated=False,
            is_caller_allocates=False,
            tag_as_string="",
            get_array_length=-1,
            py_type_name="Any",
            py_type_namespace="typing",
            line_comment=None,
            default_value=None,
            is_pointer=False,
        ),
        FunctionArgumentSchema(
            namespace="GObject",
            name="**kwargs",
            direction="IN",
            is_callback=False,
            may_be_null=False,
            is_optional=False,
            is_deprecated=False,
            is_caller_allocates=False,
            tag_as_string="",
            get_array_length=-1,
            py_type_name="Any",
            py_type_namespace="typing",
            line_comment=None,
            default_value=None,
            is_pointer=False,
        ),
    ],
    return_hint="Any",
)


OBJECT_CONNECT_AFTER = FunctionSchema(
    name="connect_after",
    namespace="GObject",
    is_method=True,
    is_class_member=True,
    is_deprecated=False,
    deprecation_warnings=None,
    docstring="Connect a handler to a signal, to be called after the default handler.",
    args=[
        FunctionArgumentSchema(
            namespace="GObject",
            name="detailed_signal",
            direction="IN",
            is_callback=False,
            may_be_null=False,
            is_optional=False,
            is_deprecated=False,
            is_caller_allocates=False,
            tag_as_string="",
            get_array_length=-1,
            py_type_name="str",
            py_type_namespace=None,
            line_comment=None,
            default_value=None,
            is_pointer=False,
        ),
        FunctionArgumentSchema(
            namespace="GObject",
            name="handler",
            direction="IN",
            is_callback=True,
            may_be_null=False,
            is_optional=False,
            is_deprecated=False,
            is_caller_allocates=False,
            tag_as_string="",
            get_array_length=-1,
            py_type_name="Callable[..., typing.Any]",
            py_type_namespace="typing",
            line_comment=None,
            default_value=None,
            is_pointer=False,
        ),
        FunctionArgumentSchema(
            namespace="GObject",
            name="*args",
            direction="IN",
            is_callback=False,
            may_be_null=False,
            is_optional=False,
            is_deprecated=False,
            is_caller_allocates=False,
            tag_as_string="",
            get_array_length=-1,
            py_type_name="Any",
            py_type_namespace="typing",
            line_comment=None,
            default_value=None,
            is_pointer=False,
        ),
    ],
    is_callback=False,
    can_throw_gerror=False,
    is_async=False,
    is_constructor=False,
    is_getter=False,
    is_setter=False,
    may_return_null=False,
    return_hint="int",
    return_hint_namespace=None,
    skip_return=False,
    wrap_vfunc=False,
    line_comment=None,
    function_type="FunctionInfo",
    is_overload=False,
)


OBJECT_CONNECT_OBJECT = _make_object_method(
    name="connect_object",
    docstring="Connect a handler to a signal with object as first argument.",
    args=[
        FunctionArgumentSchema(
            namespace="GObject",
            name="*args",
            direction="IN",
            is_callback=False,
            may_be_null=False,
            is_optional=False,
            is_deprecated=False,
            is_caller_allocates=False,
            tag_as_string="",
            get_array_length=-1,
            py_type_name="Any",
            py_type_namespace="typing",
            line_comment=None,
            default_value=None,
            is_pointer=False,
        ),
        FunctionArgumentSchema(
            namespace="GObject",
            name="**kwargs",
            direction="IN",
            is_callback=False,
            may_be_null=False,
            is_optional=False,
            is_deprecated=False,
            is_caller_allocates=False,
            tag_as_string="",
            get_array_length=-1,
            py_type_name="Any",
            py_type_namespace="typing",
            line_comment=None,
            default_value=None,
            is_pointer=False,
        ),
    ],
    return_hint="int",
)


OBJECT_CONNECT_OBJECT_AFTER = _make_object_method(
    name="connect_object_after",
    docstring="Connect a handler to a signal with object as first argument, called after default handler.",
    args=[
        FunctionArgumentSchema(
            namespace="GObject",
            name="*args",
            direction="IN",
            is_callback=False,
            may_be_null=False,
            is_optional=False,
            is_deprecated=False,
            is_caller_allocates=False,
            tag_as_string="",
            get_array_length=-1,
            py_type_name="Any",
            py_type_namespace="typing",
            line_comment=None,
            default_value=None,
            is_pointer=False,
        ),
        FunctionArgumentSchema(
            namespace="GObject",
            name="**kwargs",
            direction="IN",
            is_callback=False,
            may_be_null=False,
            is_optional=False,
            is_deprecated=False,
            is_caller_allocates=False,
            tag_as_string="",
            get_array_length=-1,
            py_type_name="Any",
            py_type_namespace="typing",
            line_comment=None,
            default_value=None,
            is_pointer=False,
        ),
    ],
    return_hint="int",
)


OBJECT_DISCONNECT_BY_FUNC = FunctionSchema(
    name="disconnect_by_func",
    namespace="GObject",
    is_method=True,
    is_class_member=True,
    is_deprecated=False,
    deprecation_warnings=None,
    docstring="Disconnect a handler by function reference.",
    args=[
        FunctionArgumentSchema(
            namespace="GObject",
            name="handler",
            direction="IN",
            is_callback=True,
            may_be_null=False,
            is_optional=False,
            is_deprecated=False,
            is_caller_allocates=False,
            tag_as_string="",
            get_array_length=-1,
            py_type_name="Callable[..., typing.Any]",
            py_type_namespace="typing",
            line_comment=None,
            default_value=None,
            is_pointer=False,
        ),
    ],
    is_callback=False,
    can_throw_gerror=False,
    is_async=False,
    is_constructor=False,
    is_getter=False,
    is_setter=False,
    may_return_null=False,
    return_hint="None",
    return_hint_namespace=None,
    skip_return=False,
    wrap_vfunc=False,
    line_comment=None,
    function_type="FunctionInfo",
    is_overload=False,
)


OBJECT_GET_PROPERTIES = _make_object_method(
    name="get_properties",
    docstring="Get multiple property values by name.",
    args=[
        FunctionArgumentSchema(
            namespace="GObject",
            name="*args",
            direction="IN",
            is_callback=False,
            may_be_null=False,
            is_optional=False,
            is_deprecated=False,
            is_caller_allocates=False,
            tag_as_string="",
            get_array_length=-1,
            py_type_name="str",
            py_type_namespace=None,
            line_comment=None,
            default_value=None,
            is_pointer=False,
        ),
    ],
    return_hint="Any",
)


OBJECT_SET_PROPERTIES = _make_object_method(
    name="set_properties",
    docstring="Set multiple property values by keyword arguments.",
    args=[
        FunctionArgumentSchema(
            namespace="GObject",
            name="**kwargs",
            direction="IN",
            is_callback=False,
            may_be_null=False,
            is_optional=False,
            is_deprecated=False,
            is_caller_allocates=False,
            tag_as_string="",
            get_array_length=-1,
            py_type_name="Any",
            py_type_namespace="typing",
            line_comment=None,
            default_value=None,
            is_pointer=False,
        ),
    ],
    return_hint="None",
)


OBJECT_HANDLER_BLOCK_BY_FUNC = _make_object_method(
    name="handler_block_by_func",
    docstring="Block handlers by function reference.",
    args=[
        FunctionArgumentSchema(
            namespace="GObject",
            name="*args",
            direction="IN",
            is_callback=False,
            may_be_null=False,
            is_optional=False,
            is_deprecated=False,
            is_caller_allocates=False,
            tag_as_string="",
            get_array_length=-1,
            py_type_name="Any",
            py_type_namespace="typing",
            line_comment=None,
            default_value=None,
            is_pointer=False,
        ),
        FunctionArgumentSchema(
            namespace="GObject",
            name="**kwargs",
            direction="IN",
            is_callback=False,
            may_be_null=False,
            is_optional=False,
            is_deprecated=False,
            is_caller_allocates=False,
            tag_as_string="",
            get_array_length=-1,
            py_type_name="Any",
            py_type_namespace="typing",
            line_comment=None,
            default_value=None,
            is_pointer=False,
        ),
    ],
    return_hint="Any",
)


OBJECT_HANDLER_UNBLOCK_BY_FUNC = _make_object_method(
    name="handler_unblock_by_func",
    docstring="Unblock handlers by function reference.",
    args=[
        FunctionArgumentSchema(
            namespace="GObject",
            name="*args",
            direction="IN",
            is_callback=False,
            may_be_null=False,
            is_optional=False,
            is_deprecated=False,
            is_caller_allocates=False,
            tag_as_string="",
            get_array_length=-1,
            py_type_name="Any",
            py_type_namespace="typing",
            line_comment=None,
            default_value=None,
            is_pointer=False,
        ),
        FunctionArgumentSchema(
            namespace="GObject",
            name="**kwargs",
            direction="IN",
            is_callback=False,
            may_be_null=False,
            is_optional=False,
            is_deprecated=False,
            is_caller_allocates=False,
            tag_as_string="",
            get_array_length=-1,
            py_type_name="Any",
            py_type_namespace="typing",
            line_comment=None,
            default_value=None,
            is_pointer=False,
        ),
    ],
    return_hint="Any",
)
