from gi_stub_gen.schema.builtin_function import ArgKind, BuiltinFunctionArgumentSchema, BuiltinFunctionSchema
from gi_stub_gen.schema.class_ import ClassSchema


CLASS_PROPERTY = ClassSchema(
    namespace="GObject",
    name="Property",
    super=["builtins.property"],
    docstring="Stub for GObject.Property.\n\n"
    "CRITICAL: This class inherits from the built-in 'property' class.\n"
    "This tells static analysis tools (Pylance/MyPy) that this object acts as a \n"
    'descriptor, preventing the "Method declaration is obscured" error when '
    "applying the decorator over a method.\n\n",
    props=[],
    required_gi_import="typing",
    fields=[],
    methods=[],
    python_methods=[
        BuiltinFunctionSchema(
            name="__init__",
            namespace="GObject",
            is_async=False,
            is_from_class=True,
            is_classmethod=False,
            is_staticmethod=False,
            docstring=None,
            return_hint_name="None",
            return_hint_namespace=None,
            return_is_optional=False,
            params=[
                BuiltinFunctionArgumentSchema(
                    name="getter",
                    kind=ArgKind.POSITIONAL_OR_KEYWORD,
                    type_hint_name="Callable[[typing.Any], typing.Any] | None",
                    type_hint_namespace="typing",
                    is_optional=False,
                    default_value="None",
                    line_comment=None,
                ),
                BuiltinFunctionArgumentSchema(
                    name="setter",
                    kind=ArgKind.POSITIONAL_OR_KEYWORD,
                    type_hint_name="Callable[[typing.Any, typing.Any], None] | None",
                    type_hint_namespace="typing",
                    is_optional=False,
                    default_value="None",
                    line_comment=None,
                ),
                BuiltinFunctionArgumentSchema(
                    name="type",
                    kind=ArgKind.POSITIONAL_OR_KEYWORD,
                    type_hint_name="type | GType | None",
                    type_hint_namespace=None,
                    is_optional=False,
                    default_value="None",
                    line_comment=None,
                ),
                BuiltinFunctionArgumentSchema(
                    name="default",
                    kind=ArgKind.POSITIONAL_OR_KEYWORD,
                    type_hint_name="Any",
                    type_hint_namespace="typing",
                    is_optional=False,
                    default_value="None",
                    line_comment=None,
                ),
                BuiltinFunctionArgumentSchema(
                    name="nick",
                    kind=ArgKind.POSITIONAL_OR_KEYWORD,
                    type_hint_name="str",
                    type_hint_namespace=None,
                    is_optional=False,
                    default_value="''",
                    line_comment=None,
                ),
                BuiltinFunctionArgumentSchema(
                    name="blurb",
                    kind=ArgKind.POSITIONAL_OR_KEYWORD,
                    type_hint_name="str",
                    type_hint_namespace=None,
                    is_optional=False,
                    default_value="''",
                    line_comment=None,
                ),
                BuiltinFunctionArgumentSchema(
                    name="flags",
                    kind=ArgKind.POSITIONAL_OR_KEYWORD,
                    type_hint_name="ParamFlags",
                    type_hint_namespace="GObject",
                    is_optional=False,
                    default_value="ParamFlags.READABLE | ParamFlags.WRITABLE",
                    line_comment=None,
                ),
                BuiltinFunctionArgumentSchema(
                    name="minimum",
                    kind=ArgKind.POSITIONAL_OR_KEYWORD,
                    type_hint_name="Any",
                    type_hint_namespace="typing",
                    is_optional=False,
                    default_value="None",
                    line_comment=None,
                ),
                BuiltinFunctionArgumentSchema(
                    name="maximum",
                    kind=ArgKind.POSITIONAL_OR_KEYWORD,
                    type_hint_name="Any",
                    type_hint_namespace="typing",
                    is_optional=False,
                    default_value="None",
                    line_comment=None,
                ),
            ],
        ),
        BuiltinFunctionSchema(
            name="get_pspec_args",
            namespace="GObject",
            is_async=False,
            is_from_class=True,
            is_classmethod=False,
            is_staticmethod=False,
            docstring="Get the arguments for the property specification.",
            return_hint_name="tuple[typing.Any, ...]",
            return_hint_namespace=None,
            return_is_optional=False,
            params=[],
        ),
        BuiltinFunctionSchema(
            name="__call__",
            namespace="GObject",
            is_async=False,
            is_from_class=True,
            is_classmethod=False,
            is_staticmethod=False,
            docstring="Allow using Property as a decorator.",
            return_hint_name="Property",
            return_hint_namespace="GObject",
            return_is_optional=False,
            params=[
                BuiltinFunctionArgumentSchema(
                    name="fget",
                    kind=ArgKind.POSITIONAL_OR_KEYWORD,
                    type_hint_name="Callable[[typing.Any], typing.Any]",
                    type_hint_namespace="typing",
                    is_optional=False,
                    default_value=None,
                    line_comment=None,
                ),
            ],
        ),
    ],
    signals=[],
    extra=[],
    is_deprecated=False,
)
